extends "res://tests/test_v010_rules.gd"
const Roster=preload("res://scripts/rules/excel_abilities.gd")
func roster_trigger(c: Dictionary,k: String,t: Dictionary={"none":true},data: Dictionary={}):
 Roster.resolve_trigger(e,{"roster":true,"extended":true,"source":c.duplicate(true),"effect":k,"owner":c.owner,"target":t,"data":data})
func resolve_spell(id: String,t: Dictionary={"none":true}):
 var c=e.make_card(id,0,"stack")
 e.damage_context={"source":c,"single":e.Pack.flatten(t).size()==1,"combat":false}
 var result=Roster.spell_resolve(e,{"card":c,"owner":0,"target":t,"kind":"card"})
 e.damage_context={};expect(result,"explicit resolution "+id);return c
func selection(id: String,picks: Array) -> Dictionary:return selected(e.targets_for(id,0),picks)
func act(c: Dictionary,k: String,t: Dictionary={"none":true}):
 e.priority=c.owner
 var error=e.commit_extension(c.owner,c.uid,t,e.payment(c.owner,e.Extra.activation_cost(k)).plan,k)
 expect(error.is_empty(),"activate "+k+" "+error);settle();e.priority=0
func run():
 var saved=FileAccess.get_file_as_string(Store.SAVE_PATH);var all=DB.load_cards()
 expect(all.size()==269,"269 validated definitions load")
 var ids=JSON.parse_string(FileAccess.get_file_as_string("res://work/v011/new-ids.json"))
 for id in ids:expect(all.has(id) and FileAccess.file_exists(all[id].image),"new definition/art "+id)
 fresh();var a=put("52");e.combat_hit(a,{"player":1},2);expect(e.players[0].life==23,"lifesteal 3 heals three once per damage batch")
 fresh();a=put("43");var b=put("50","field",1);e.combat_hit(a,e.ref_target(b),2)
 expect(b.damage==0 and b.minus_counters==2 and e.stat(b,"health")==e.cards[b.card_id].health-2,"Momoyo deals minus counters instead of marked damage")
 fresh();a=put("31");var base=e.stat(a,"power");mana();expect(e.stat(a,"power")==base+3 and e.Extra.keyword(e,a,"歼灭"),"Kasen twelve palette continuous stats and annihilate")
 fresh();a=put("74");a.leader_counters=1;b=put("43");expect(e.stat(b,"health")==e.cards[b.card_id].health+1,"Remilia leader black aura");e.move_to(a,"grave");expect(e.stat(b,"health")==e.cards[b.card_id].health,"aura ends when source leaves")
 fresh();a=put("80");b=put("2");expect(e.stat(b,"power")==e.cards[b.card_id].power+1 and e.stat(b,"health")==e.cards[b.card_id].health,"Cirno increases fairy power/spirit only")
 fresh();a=put("60");b=put("50","field",1);expect(e.stat(b,"power")==e.cards[b.card_id].power-1,"Murasa shrinks opposing units")
 fresh();a=put("24");var c=put("111","hand");expect(e.cast_cost(0,c,{"x":2}).get("蓝",0)==1,"Ran discounts blue component")
 fresh();mana();c=put("124","hand");var actual_cost=e.cast_cost(0,c,{"x":3});expect(actual_cost.get("绿",0)==1 and actual_cost.get("黄",0)==6,"2X costs six for X three: "+str(actual_cost))
 fresh();a=put("27","field",1);expect(not e.targets_for("104",0).any(func(t):return t.get("uid")==a.uid),"Nitori cannot be targeted by enemy spells")
 expect(e.targets_for("104",1).any(func(t):return t.get("uid")==a.uid),"Nitori can be targeted by own spell")
 fresh();a=put("44");b=put("50");Roster.plus(e,a,2);Roster.plus(e,a,1);expect(e.triggers.size()==1,"Akyuu triggers once per turn for counter placement")
 e.pump_choices();e.choose_effect(e.ref_target(b));settle();expect(b.plus_counters==1,"Akyuu grants one counter to another unit")
 fresh();a=put("45");b=put("46");b.plus_counters=4;roster_trigger(a,"keiki_copy",e.ref_target(b));settle()
 c=e.units(0).filter(func(u):return u.token)[0];expect(e.cards[c.card_id].name=="偶像" and e.cards[c.card_id].race==["埴轮"] and e.cards[c.card_id].power==e.cards[b.card_id].power and c.plus_counters<4,"Keiki copies printed characteristics, changes identity, excludes counters")
 fresh();a=put("2");put("3");roster_trigger(a,"luna_life");expect(e.players[0].life==22,"Luna counts both fairies")
 fresh();a=put("12");b=put("50","field",1);b.tapped=true;roster_trigger(a,"letty_freeze",e.ref_target(b));e.start_turn(1);expect(b.tapped,"Letty locks next reset");e.start_turn(1);expect(not b.tapped,"Letty lock expires")
 fresh();a=put("26");b=put("50","grave",1);var d=put("51","grave");roster_trigger(a,"komachi_exile",{"picks":[[e.Pack.ref(e,b),e.Pack.ref(e,d)]]});expect(b.zone=="exile" and d.zone=="exile" and e.players[0].life==22,"Komachi exiles up to two from both graves, heals once")
 fresh();a=put("17");b=put("50","field",1);e.combat_hit(a,e.ref_target(b),1);settle();expect(b.zone=="grave","Medicine damage destruction trigger")
 fresh();a=put("character-kmo-001");a.leader_counters=1;b=put("50","field",1);e.combat_hit(a,e.ref_target(b),1);settle();expect(b.zone=="grave","Komachi minus-three trigger performs state checks")
 for i in range(3):e.combat_hit(a,{"player":1},1);settle()
 expect(e.winner==0 and e.players[1].coins==3,"three Komachi coins lose the game")
 fresh();a=put("22");b=put("50");e.move_to(b,"grave");settle();expect(e.players[0].life==21,"Mystia gains life on own unit death")
 fresh();put("175");b=put("50");e.move_to(b,"grave");settle();expect(e.units(0).size()==1 and e.stat(e.units(0)[0],"spirit")==0 and e.field_slots(0)==0,"Nether field creates no-slot 1/1/0 ghost")
 fresh();a=put("82");roster_trigger(a,"kanako_pillar");expect(e.units(0).size()==2 and e.Extra.keyword(e,e.units(0)[1],"英勇"),"Kanako creates brave 2/2/1 pillar")
 fresh();a=put("77");a.leader_counters=1;mana();b=put("50");d=put("51","grave")
 expect(e.available_actions(0,a.uid).filter(func(x):return x.type=="extension").size()==2,"Alice exposes both ordinary and leader activation")
 var options=e.Extra.activation_options(e,a,"alice_recycle");act(a,"alice_recycle",selected(options,[[e.ref_target(b)],[e.Pack.ref(e,d)]]));expect(b.zone=="grave" and d.zone=="deck" and e.players[0].deck.back()==d,"Alice pays other unit sacrifice and bottoms chosen grave card")
 fresh();a=put("34");e.apply_turn_buff(e.ref_target(a),{"血量":3});b=put("50","field",1);act(a,"clown_sweep");expect(a.tapped and b.damage==1,"Clown taps to damage all units")
 fresh();a=put("90");a.leader_counters=1;a.plus_counters=2;b=put("50");act(a,"suika_counter",e.ref_target(b));expect(a.plus_counters==1 and b.plus_counters==1,"Suika moves one plus counter")
 fresh();a=put("character-smm07");a.leader_counters=1;b=put("166","hand");options=e.Extra.activation_options(e,a,"sanae_search");act(a,"sanae_search",selected(options,[[e.Pack.ref(e,b)]]));expect(b.zone=="grave" and e.players[0].sanae_used and not e.extension_activation_error(0,a,"sanae_search").is_empty(),"Sanae search pays green discard and is once per player per game")
 fresh();a=put("76");a.leader_counters=1;b=put("51","hand",1);act(a,"satori_discard",{"player":1});expect(a.zone=="exile" and b.zone=="grave","Satori exile cost and chosen opposing hand discard")
 fresh();a=put("85");a.leader_counters=1;act(a,"kaguya_end");expect(e.active==1 and e.players[0].hand.size()==1,"Kaguya draws and immediately ends own turn")
 fresh();a=put("50");resolve_spell("101",e.ref_target(a));expect(a.leader_counters==1,"leader counter placed")
 fresh();b=put("50","grave");resolve_spell("103",e.Pack.ref(e,b));expect(e.players[0].deck[0]==b,"grave card placed at deck top")
 fresh();a=put("50");resolve_spell("124",dict(e.ref_target(a),{"x":3}));expect(a.plus_counters==3 and e.Extra.keyword(e,a,"英勇"),"X counters plus temporary brave")
 fresh();a=put("50");a.tapped=true;resolve_spell("125",e.ref_target(a));expect(not a.tapped and e.Extra.keyword(e,a,"不能被阻挡"),"untap and unblockable")
 fresh();resolve_spell("129");expect(e.units(0).size()==2 and e.cards[e.units(0)[0].card_id].colors==["红","黑"],"create two 1/1/1 bats")
 fresh();b=put("50","grave",1);resolve_spell("132",e.Pack.ref(e,b));expect(b.zone=="exile" and e.units(0).size()==1 and e.has_haste(e.units(0)[0]) and e.delayed[0].owner==0,"Ghost spell creates cost-sized haste imp sacrificed at own end")
 fresh();a=put("50");a.plus_counters=2;b=put("51","field",1);b.plus_counters=3;resolve_spell("137",e.ref_target(a));expect(a.plus_counters==5 and b.plus_counters==0,"gather all plus counters")
 fresh();b=put("50","field",1);resolve_spell("140",e.ref_target(b));expect(b.owner==0 and e.has_haste(b),"temporary control grants haste");e.finish_turn();expect(b.owner==1 and b in e.players[1].field,"temporary control returns at cleanup")
 fresh();b=put("50","grave");resolve_spell("146",e.Pack.ref(e,b));expect(b.zone=="palette" and b.tapped,"grave to tapped palette")
 fresh();a=put("50");e.apply_turn_buff(e.ref_target(a),{"血量":10});a.damage=1;resolve_spell("148",e.ref_target(a));expect(a.damage==6,"Flower damage upgrades from two to five")
 fresh();e.players[0].life=4;resolve_spell("spell-smm-006");expect(e.players[0].life==12,"Rest heals eight at low life")
 fresh();a=put("50","grave");b=put("96","grave");e.players[0].life=3;c=resolve_spell("150");expect(a.zone=="palette" and b.tapped and e.players[0].life==20 and c.zone=="exile","Grace resets life, transfers entire grave to tapped palette, exiles itself")
 fresh();resolve_spell("151",{"none":true,"x":3});expect(e.units(0).size()==3 and e.field_slots(0)==0 and e.units(0).all(func(u):return e.stat(u,"power")==3 and e.Extra.keyword(e,u,"歼灭")),"X three frogs are 3/3/3 no-slot with annihilate")
 fresh();a=put("50","field",1);resolve_spell("156",e.ref_target(a));expect(a.tapped and not e.Pack.reset_allowed(e,a),"Perfect Freeze prevents reset");e.players[0].freeze_serial=1;expect(e.Pack.reset_allowed(e,a),"next same-name spell releases old freeze")
 fresh();a=put("50");resolve_spell("160");expect(e.targets_for("104",0).is_empty() and e.targets_for("104",1).is_empty(),"shroud blocks both players targeting own permanents")
 fresh();a=put("50");b=put("51");put("55","field",1);resolve_spell("spell-kmo-004");settle();expect(e.units(0).size()==1 and e.units(1).size()==1,"both players choose one survivor")
 fresh();a=put("50");e.move_to(a,"grave");expect(e.targets_for("spell-kmo-002",0).size()==1,"death return sees only units that died this turn");resolve_spell("spell-kmo-002",e.Pack.ref(e,a));expect(a.zone=="field","death return enters under caster control")
 fresh();mana();a=put("173");b=put("spell-smm-006","grave");expect(e.cast_error(0,b.uid).is_empty(),"Heart permits own grave small spell once");var err=e.commit_cast(0,b.uid,{"none":true},e.payment(0,e.cast_cost(0,b)).plan);settle();expect(err.is_empty() and b.zone=="exile" and e.players[0].heart_used_turn==e.turn,"grave spell exiles on resolution and consumes turn use")
 fresh();mana();b=put("107","hand");a=put("51","hand");options=e.targets_for("107",0);var t=selected(options,[[e.Pack.ref(e,a)]]);err=e.commit_cast(0,b.uid,t,e.payment(0,e.cast_cost(0,b)).plan);settle();expect(err.is_empty() and a.zone=="grave" and e.players[0].hand.size()==3,"additional discard is paid before drawing three")
 fresh();mana();put("74");b=put("109","hand");a=put("50","field",1);err=e.commit_cast(0,b.uid,e.ref_target(a),e.payment(0,e.cast_cost(0,b)).plan);expect(err.is_empty() and Pack.response_locked(e),"Gungnir cannot be responded to");settle();expect(a.zone=="grave","Gungnir deals four")
 fresh();b=put("spell-smm-006","grave",1);c=resolve_spell("157",e.Pack.ref(e,b));settle();expect(b.zone=="grave" and b.owner==1 and e.players[0].life==24,"memory casts opposing grave spell for free and returns to owner grave")
 fresh();a=put("121");a.timer=1;Roster.on_phase(e,"end");settle();e.finish_turn();expect(e.active==0,"extra turn inserts caster's next turn")
 fresh();a=put("171");b=put("50");expect(e.Extra.keyword(e,b,"歼灭"),"annihilate field aura")
 expect(saved==FileAccess.get_file_as_string(Store.SAVE_PATH),"player saved decks remain byte-for-byte unchanged")
 print("V011_RULES: %d checks; %d failures" % [checks,failures.size()]);quit(0 if failures.is_empty() else 1)
func dict(a: Dictionary,b: Dictionary) -> Dictionary:
 var result=a.duplicate(true);result.merge(b,true);return result
