extends "res://tests/test_v011_rules.gd"
func run():
 fresh();var a=put("3");var b=put("167","field",1);roster_trigger(a,"star_destroy",e.Pack.ref(e,b));expect(b.zone=="grave","Star destroys opposing artifact")
 fresh();a=put("77");b=enter("7");e.choose_effect({"player":1});settle();expect(e.players[1].life==19,"Hourai enters with Alice and can ping a player")
 b=put("8");e.move_to(b,"grave");settle();expect(e.players[0].hand.size()==1,"Shanghai draws on death while Alice is controlled")
 fresh();b=put("2","deck");a=enter("13");settle();expect(e.players[0].hand.any(func(u):return u.card_id=="2"),"Daiyousei searches and reveals fairy")
 fresh();mana();a=put("25");b=put("50","hand");act(a,"hatate_return");expect(a.zone=="hand" and b.zone=="field" and b.tapped,"Hatate bounce triggers own hand replacement")
 fresh();a=put("19");put("51","field",1);e.attack(0,a.uid);expect(e.legal_blockers().is_empty(),"Wriggle excludes black blockers")
 fresh();a=put("42");b=put("50","field",1);put("51","field",1);e.move_to(a,"grave");settle();expect(b.zone=="grave" and e.players[0].life==18,"Seiga opponent chooses highest-power sacrifice then controller loses two")
 fresh();a=enter("63");settle();expect(e.players[0].hand.size()==1,"Nazrin draws two and bottoms one")
 fresh();put("50","grave");put("51","grave");put("52","grave");a=enter("66");settle();expect(e.players[0].grave.is_empty() and e.players[0].life==21,"Kyouko shuffles exactly three then gains one")
 fresh();a=put("73");a.leader_counters=1;expect(e.Extra.keyword(e,a,"不能被阻挡"),"Koishi leader is unblockable");e.phase="possession";e.advance_phase();settle();expect(a.tapped or e.stat(a,"spirit")==e.cards[a.card_id].spirit+2,"Koishi coin at main phase start")
 fresh();a=put("74");b=put("50");e.combat_hit(b,{"player":1},1);expect(e.players[0].life==21,"Remilia grants lifesteal to another red unit")
 fresh();a=put("76");var top=e.players[1].deck.slice(0,3);roster_trigger(a,"satori_scry",{"player":1})
 var choices=e.pending.options;var target=selected(choices,[[e.Pack.ref(e,top[1])]]);e.choose_effect(target)
 choices=e.pending.options;e.choose_effect(selected(choices,[[e.Pack.ref(e,top[2]),e.Pack.ref(e,top[0])]]))
 expect(e.players[1].deck[0]==top[2] and top[1].zone=="grave","Satori preserves explicit chosen top order")
 fresh();a=put("80");a.leader=true;e.players[0].leader=a;e.move_to(a,"grave");e.pump_choices();e.choose_return(true);expect(a.zone=="leader" and a.timer==0,"Cirno returns to leader with zero timer")
 fresh();a=put("86");a.leader_counters=1;e.Roster.on_enter(e,a);settle();expect(e.players[0].palette.size()==1 and e.players[0].palette[0].tapped,"Yuuka ETB ramp")
 e.priority=0;e.attack(0,a.uid);settle();expect(e.players[0].palette.size()==2,"Yuuka attack ramp")
 fresh();a=put("93");a.leader_counters=1;b=put("166","field");expect(e.has_haste(b),"Suwako grants other green units haste")
 fresh();a=put("93");b=put("2","deck");e.players[0].deck.erase(b);e.players[0].deck.push_front(b);roster_trigger(a,"suwako_top");settle();expect(b.zone=="deck","Suwako cannot select a nongreen fairy")
 fresh();a=put("character-smm01");a.leader_counters=1;mana();b=put("51","hand");var err=e.commit_cast(0,b.uid,{},e.payment(0,e.cast_cost(0,b)).plan);settle();expect(err.is_empty() and e.units(0).any(func(u):return u.token and e.cards[u.card_id].character=="小人"),"Shinmyoumaru cast trigger creates kobito")
 fresh();a=put("47");a.tapped=true;mana();b=put("spell-smm-006","hand");err=e.commit_cast(0,b.uid,{"none":true},e.payment(0,e.cast_cost(0,b)).plan);settle();expect(not a.tapped and e.stat(a,"power")==e.cards[a.card_id].power+1,"Meiling untaps and gains power/health when spell is used")
 fresh();a=put("59","hand");mana();e.active=1;e.phase="main";e.priority=1;b=put("50","field",1);e.attack(1,b.uid);expect(e.cast_error(0,a.uid).is_empty(),"Kogasa gains legal fast timing while opponent attacks")
 fresh();a=put("32");b=put("50");var spell=e.make_card("96",1,"stack");e.stack=[{"id":41,"kind":"card","card":spell,"owner":1,"target":e.ref_target(b),"name":"damage"}];e.priority=0
 choices=e.Extra.activation_options(e,a,"hina_redirect");expect(not choices.is_empty(),"Hina finds legal stack target change");act(a,"hina_redirect",choices[0]);expect(e.players[0].life==18 and b.damage==0 and a.zone=="grave","Hina pays life and redirects lethal damage to herself")
 fresh();a=put("50");b=put("51","field",1);resolve_spell("98",{"parts":[e.ref_target(a),e.ref_target(b)]});expect(a.zone=="hand" and b.zone=="hand","Tengu pair bounces one same-category unit per player")
 fresh();a=put("2","grave");b=put("3","grave");resolve_spell("97",{"picks":[[e.Pack.ref(e,a),e.Pack.ref(e,b)]]});settle();expect(a.zone=="field" and b.zone=="field" and e.players[0].life==22,"simultaneous fairy return: Luna sees both returned units")
 fresh();a=put("50");var old_epoch=a.epoch;resolve_spell("114",{"picks":[[e.ref_target(a)]]});expect(a.zone=="field" and a.epoch>old_epoch,"blink creates a new field instance")
 fresh();a=e.players[0].leader;e.detach(a);e.enter_field(a,0);old_epoch=a.epoch;resolve_spell("114",{"picks":[[e.ref_target(a)]]});e.pump_choices();e.choose_return(false);expect(a.zone=="field" and a.epoch>old_epoch,"leader declining leader-zone replacement returns from blink")
 fresh();a=put("50","field",1);resolve_spell("105");expect(a.tapped,"miracle terminus taps all opposing units")
 fresh();a=put("50");b=put("51","field",1);resolve_spell("116");expect(a.zone=="grave" and b.zone=="grave","three damage sweep removes both sides simultaneously")
 fresh();a=put("51","hand");b=put("55","hand");resolve_spell("122");settle();expect(a.zone=="field" and b.zone=="field","hand army selects multiple units")
 fresh();a=put("51","palette");b=put("167","palette");resolve_spell("158");settle();expect(a.zone=="field" and b.zone=="field","palette army includes units and artifacts")
 fresh();a=put("96","grave");var s=resolve_spell("119");e.priority=0;expect(s.zone=="exile" and a.zone=="exile" and e.cast_cost(0,a).is_empty() and e.cast_error(0,a.uid).is_empty(),"history exile grants same-turn free use")
 e.turn+=1;expect(not e.cast_error(0,a.uid).is_empty(),"history access expires next turn")
 fresh();a=put("96","deck");e.players[0].deck.erase(a);e.players[0].deck.push_front(a);s=resolve_spell("128");expect(a.zone=="exile" and a.excel_access.ignore and s.zone=="exile","Philosopher exiles revealed spells with condition bypass")
 fresh();a=put("50","field",1);e.stack=[{"id":12,"kind":"ability","source":a,"owner":1,"target":{"player":0},"name":"ability","amount":1}];resolve_spell("123",{"stack_id":12});expect(e.stack.is_empty(),"counter ability removes ability from stack")
 fresh();a=put("50");b=e.make_card("96",1,"stack");e.stack=[{"id":13,"kind":"card","card":b,"owner":1,"target":e.ref_target(a),"name":"damage"}];expect(e.targets_for("136",0).size()==1,"counter targeting own unit is legal");resolve_spell("136",{"stack_id":13});expect(b.zone=="grave" and e.stack.is_empty(),"targeting counter sends spell to grave")
 fresh();a=put("50","field",1);e.apply_turn_buff(e.ref_target(a),{"血量":20});put("51","grave");resolve_spell("126",{"parts":[{"player":0},e.ref_target(a)]});expect(a.damage==2,"lake mills first then counts caster grave")
 fresh();a=put("50");b=put("52","field",1);resolve_spell("127",{"parts":[e.ref_target(a),e.ref_target(b)]});expect(b.zone=="grave","waterfall uses chosen unit power as spell damage")
 fresh();a=put("50");a.tapped=true;resolve_spell("144",dict(e.ref_target(a),{"mode":"重置单位"}));expect(not a.tapped,"crimson untap mode")
 fresh();resolve_spell("145",{"none":true,"mode":"抓三张再弃两张"});settle();expect(e.players[0].hand.size()==1 and e.players[0].grave.size()==3,"quiet draw-discard mode completes selected discard")
 fresh();a=put("74","deck");e.players[0].deck.erase(a);e.players[0].deck.push_front(a);resolve_spell("149",{"picks":[[]]});expect(a.zone=="field","Door reveals through self card and puts it on field")
 fresh();var before=e.players[0].deck.size();resolve_spell("152");choices=e.pending.options;e.choose_effect(selected(choices,[[]]));choices=e.pending.options;var order=choices[0].selection[0].pool.duplicate();order.reverse();e.choose_effect(selected(choices,[order]));expect(e.players[0].hand[0].uid==order[0].uid and e.players[0].deck.size()==before-1,"Fire scry supports choosing none to grave, ordering, then drawing")
 fresh();a=put("7","deck");b=put("8","deck");for i in range(6):put("51")
 resolve_spell("153");settle();expect(a.zone=="field" and b.zone=="field" and e.field_slots(0)==6,"Doll army bypasses slots for all dolls for rest of game")
 fresh();a=put("50","field",1);b=put("51","field",1);b.tapped=true;resolve_spell("154",e.ref_target(a));expect(e.units(1).is_empty(),"tap one then destroy all tapped opponents")
 fresh();a=put("2");resolve_spell("155");expect(e.stat(a,"spirit")==e.cards[a.card_id].spirit+3,"fairy festival buffs all three stats");e.phase="main";e.advance_phase();settle();expect(a.zone=="hand","fairy festival returns fairies at own end")
 fresh();a=put("50");b=put("51","grave");resolve_spell("161",{"parts":[{"none":true,"mode":"全体强化"},dict(e.Pack.ref(e,b),{"mode":"回收单位"})]});expect(e.stat(a,"power")==6 and b.zone=="hand","wheel resolves two different chosen modes")
 fresh();a=put("50","field",1);e.combat={"attacker":e.ref_target(a),"owner":1};b=put("51");old_epoch=b.epoch;resolve_spell("178",e.ref_target(a));settle();expect(a.zone=="grave" and b.zone=="field" and b.epoch>old_epoch,"cloud kills attacker then optionally blinks own unit")
 fresh();a=put("102");a.timer=2;b=put("51","hand");var palette=put("164","palette");roster_trigger(a,"kaleidoscope");choices=e.pending.options;e.choose_effect(selected(choices,[[e.Pack.ref(e,b)],[e.Pack.ref(e,palette)]]));expect(b.zone=="palette" and palette.zone=="hand" and e.players[0].hand.size()==2,"kaleidoscope draws and swaps hand/palette")
 fresh();a=put("113");a.timer=1;enter("51");settle();expect(e.players[0].hand.size()==1,"Activity records differently-named entry");enter("51");settle();expect(e.players[0].hand.size()==1,"Activity does not draw on same-name entry")
 fresh();a=put("172");b=put("2","deck");e.players[0].deck.erase(b);e.players[0].deck.push_front(b);roster_trigger(a,"mist_lake");settle();expect(b.zone=="field","Mist lake reveals top four and selects a fairy")
 fresh();a=put("spell-kmo-005");a.timer=2;b=put("50");Roster.on_phase(e,"end");settle();expect(b.damage==1,"Snow time spell damages all units at own end")
 fresh();a=put("85");a.leader_counters=1;b=e.make_card("96",1,"stack");e.stack=[{"id":99,"kind":"card","card":b,"owner":1,"target":{"player":0},"name":"damage"}];var ending=resolve_spell("159");expect(b.zone=="exile" and ending.zone=="exile" and e.active==1 and e.players[0].life==20,"end turn exiles unresolved stack and skips its damage")
 print("V011_EDGES: %d checks; %d failures" % [checks,failures.size()]);quit(0 if failures.is_empty() else 1)
