extends "res://tests/support/ui_base.gd"
const Archive=preload("res://scripts/replay_archive.gd")
const Observer=preload("res://net/observer_projection.gd")
const Player=preload("res://scripts/replay_player.gd")
func run():
 Store.Paths.root_override=ProjectSettings.globalize_path("res://work/replay-training-ui/"+str(Time.get_ticks_usec()))
 DirAccess.make_dir_recursive_absolute(Store.Paths.root())
 app=load("res://main.tscn").instantiate();app.settings_path=Store.Paths.root().path_join("settings.json");root.add_child(app);await process_frame
 expect(not app.replay_training_mode,"training setting defaults to off")
 app.settings()
 var toggle=find_button(app.screen,"回放训练模式：标注关键步骤与推荐招法")
 expect(toggle!=null,"settings has replay training toggle")
 toggle.button_pressed=true
 expect(app.replay_training_mode and JSON.parse_string(FileAccess.get_file_as_string(app.settings_path)).replay_training_mode,"training setting persists")
 app.setup();app.begin_battle(true);view=app.duel_view;e=view.engine;await settle();clean()
 put("18","hand");put("129","hand",1)
 for id in ["165","167","166","164","168"]:
  for i in range(3):put(id,"palette")
 var archive=Archive.new()
 var room={"status":"playing","names":["人机","对手"],"scores":[0,0],"format":1,"round":1}
 archive.record({"game_id":"ui","sequence":1,"room":room,"projection":Observer.build(e,[],0,true)},0)
 e.pass_priority(0)
 archive.record({"game_id":"ui","sequence":2,"room":room,"projection":Observer.build(e,[],0,true)},0)
 e.surrender(1)
 archive.record({"game_id":"ui","sequence":3,"room":room,"projection":Observer.build(e,[],0,true)},0)
 app.clear_page("battle")
 var player=Player.new();app.screen.add_child(player);app.replay_controller=player;player.build(app,archive);view=app.duel_view;await settle()
 expect(player.training_button.visible,"enabled replay has annotation button")
 player.seat=1;player.playing=true;player.open_training()
 expect(not player.playing and player.training_editor!=null,"opening annotation pauses playback")
 var editor=player.training_editor
 expect(editor.editing_seat==0 and editor.seat_choice.selected==0,"new computer-turn annotation selects computer instead of spectator's seat")
 player.seat=0
 expect(editor.shade.z_index>2 and editor.shade.size.x>=1600,"annotation modal covers card cost symbols and blocks background clicks")
 expect(editor.ctx.decision_available and editor.preferred.item_count>1,"editor provides verified next action choices")
 expect(editor.alternative.selected==1 and editor.alternative.get_item_text(1).begins_with("电脑实际操作"),"new annotation defaults comparison to recorded actual operation")
 expect(editor.selected_choice(editor.alternative).action.kind=="pass","actual operation selection points to the recorded pass")
 editor.comment.text="先保住颜色，别把费用用完。";editor.recommendation.text="先光之三妖精，再留费用。"
 editor.preferred.select(editor.preferred.item_count-1);editor.mark_dirty()
 expect(not editor.flush() and "不同" in editor.status.text,"same actions are rejected even when dropdown indices differ")
 editor.preferred.select(1);editor.alternative.select(1);editor.mark_dirty()
 expect(editor.flush(),"UI saves commentary and teacher preference")
 expect(player.training.annotations.size()==1,"one annotation saved")
 expect(player.training.find(0,0).comparison_action.get("source","")=="replay_actual","UI saves actual replay comparison metadata")
 await capture("replay-training-editor")
 editor.close();player.seek(2);view=app.duel_view;await settle();player.open_training();editor=player.training_editor
 expect(not editor.ctx.decision_available,"terminal steps allow notes without invented actions")
 editor.comment.text="终局复盘。";editor.mark_dirty();editor.close()
 expect(player.training.annotations.size()==2,"closing saves edited terminal commentary")
 player.seek(0);view=app.duel_view;await settle();player.open_training();editor=player.training_editor
 expect(editor.comment.text=="先保住颜色，别把费用用完。","returning to step restores text")
 expect(editor.alternative.selected==1 and editor.selected_choice(editor.alternative).get("source","")=="replay_actual","returning to step restores actual-computer comparison selection")
 # Preserve recorded comparison with a text-only recommendation too.
 editor.preferred.select(0);editor.mark_dirty()
 expect(editor.flush() and player.training.find(0,0).teacher_action.is_empty() and not player.training.find(0,0).comparison_action.is_empty(),"text recommendation can retain actual comparison without fabricated teacher action")
 editor.seat_choice.select(1);editor.seat_choice.item_selected.emit(1)
 editor.comment.text="对手的防守选择。";editor.mark_dirty();editor.close()
 expect(player.training.find(0,1).comment=="对手的防守选择。","evaluation seat has independent notes")
 player.open_training();editor=player.training_editor;editor.export_file()
 expect(FileAccess.file_exists(player.training.output_path),"export creates portable training file")
 editor.delete_row();expect(player.training.find(0,0).is_empty() and not player.training.find(0,1).is_empty(),"delete affects only current frame and seat")
 editor.close()
 var reopened=preload("res://scripts/ai/replay_training.gd").new();reopened.setup(archive)
 expect(reopened.find(0,1).get("comment","")=="对手的防守选择。","file reopening preserves evaluation seat and Chinese text")
 app.set_replay_training_mode(false)
 expect(not player.training_button.visible,"disabling mode hides annotation entry")
 app.is_test_build=false
 app.set_replay_training_mode(true)
 expect(not app.replay_training_mode and not player.training_button.visible,"release cannot enable replay training")
 view.settings_menu()
 expect(find_button(view.ui,"回放训练模式：标注步骤与推荐招法")==null,"release battle settings hide replay training toggle")
 app.settings()
 expect(find_button(app.screen,"回放训练模式：标注关键步骤与推荐招法")==null,"release settings hide replay training toggle")
 print("REPLAY TRAINING UI: ",checks," checks; ",failures.size()," failures")
 quit(0 if failures.is_empty() else 1)
