extends "res://tests/test_v0181_ui.gd"
func run():
 Store.Paths.root_override=ProjectSettings.globalize_path("res://work/update0921/net-ui/"+str(Time.get_ticks_usec()))
 app=load("res://main.tscn").instantiate();root.add_child(app);await process_frame
 authority_session=Session.new();client_session=Session.new()
 root.add_child(authority_session);root.add_child(client_session)
 authority_session.initialize("res://work/update0921/ui-host");client_session.initialize("res://work/update0921/ui-guest")
 app.lan_session=client_session
 expect(authority_session.create_room(3,false,47992,"127.0.0.1").is_empty(),"UI host opens")
 client_session.join_room("127.0.0.1",47992)
 await until(func():return not authority_session.applicant.is_empty());authority_session.accept_applicant(true)
 await until(func():return client_session.can_act())
 for seat in [0,1]:authority_session.handle_room_action(seat,{"name":"deck","deck":app.decks[seat]})
 for seat in [0,1]:authority_session.handle_room_action(seat,{"name":"ready"})
 authority_session.handle_room_action(authority_session.series.state.chooser,{"name":"first","first":true})
 await until(func():return not client_session.latest_snapshot.is_empty())
 app.return_network_battle();view=app.duel_view
 await until(func():return not view.revealing())
 expect(find_button(view.ui,"悔棋")!=null and find_button(view.ui,"悔棋").disabled,"initial UI undo disabled")
 await press("保留")
 expect(await until(func():return authority_session.authority.players[1].mulligan_done and not client_session.busy),"guest completes operation")
 await until(func():return client_session.view_sequence==authority_session.sequence);await settle()
 expect(not find_button(view.ui,"悔棋").disabled,"undo enabled after operation")
 await press("悔棋")
 expect(await until(func():return not authority_session.undo_request.is_empty() and not client_session.room.get("undo_request",{}).is_empty()),"UI requests agreement")
 expect(view.network_locked() and find_button(view.ui,"取消请求")!=null,"request locks actions and offers cancellation")
 await press("取消请求")
 expect(await until(func():return authority_session.undo_request.is_empty() and client_session.room.get("undo_request",{}).is_empty()),"UI cancels request")
 await settle()
 authority_session.view_sequence=authority_session.sequence
 authority_session.room_action({"name":"undo_request"})
 expect(await until(func():return find_button(view.ui,"同意悔棋")!=null),"opponent sees agreement buttons")
 expect(not find_button(view.ui,"同意悔棋").disabled and not find_button(view.ui,"拒绝悔棋").disabled,"agreement buttons work while match locked")
 view.inspect_card(view.engine.players[1].hand[0].card_id,view.engine.players[1].hand[0].uid)
 expect(view.inspection.visible,"card inspection remains available during agreement")
 await capture("update0921-undo-agreement")
 await press("同意悔棋")
 expect(await until(func():return authority_session.undo_request.is_empty() and not authority_session.authority.players[1].mulligan_done and client_session.view_sequence==authority_session.sequence),"UI approval restores prior operation")
 await settle()
 expect(not view.network_locked() and find_button(view.ui,"保留")!=null,"restored game is interactable")
 expect(authority_session.recording.frames.size()==1 and client_session.recording.frames.size()==1,"UI requests and discarded operation absent from replay")
 authority_session.leave(false);client_session.leave(false)
 print("UPDATE0921 NETWORK UI ",checks," checks; failures=",failures)
 quit(0 if failures.is_empty() else 1)
