extends "res://tests/support/network_base.gd"
const Series=preload("res://net/series_controller.gd")
const Fixtures=preload("res://tests/support/sideboard_fixtures.gd")

func swapped(original: Dictionary,count: int) -> Dictionary:
 return Fixtures.swapped(original,count)

func check_rules(decks: Array):
 var series=Series.new();series.setup(Series.BO1_SIDEBOARD,true,"test")
 for seat in [0,1]:check(series.set_deck(seat,decks[seat]).is_empty(),"register seat %d" % seat)
 check(not series.public_state(0).has("leaders"),"leaders remain hidden before both players register and ready")
 series.ready(0)
 check(not series.prepare_choice() and not series.start_game(),"one ready player cannot reveal or start")
 series.ready(1);series.prepare_choice()
 check(series.state.status=="sideboarding" and series.state.ready==[false,false] and series.state.round==0 and series.state.game_id.is_empty(),"registration opens a separate preparation phase")
 check(series.public_state(0).leaders==[decks[0].leader,decks[1].leader],"both leaders are revealed before sideboarding")
 var spectator=series.public_state(-1)
 check(spectator.own_deck.is_empty() and not spectator.has("own_registered") and not spectator.has("decks") and not spectator.has("registered"),"spectators receive leaders without either private deck")
 check(not series.start_game() and not series.choose_first(0,true).is_empty(),"game and first-player choice wait for sideboarding")
 check(series.set_deck(0,swapped(decks[0],0)).is_empty(),"zero swaps allowed")
 check(series.set_deck(0,swapped(decks[0],3)).is_empty(),"three copies of a reserve card allowed")
 var before=series.state.duplicate(true)
 check(series.set_deck(0,swapped(decks[0],4)).contains("3") and series.state==before,"fourth reserve copy rejected without changing state")
 check(series.public_state(0).own_registered==decks[0],"submitting swaps retains the original registration")
 var sorted=swapped(decks[0],3);sorted.main.reverse();sorted.side.reverse()
 check(Series.sideboard_additions(sorted,decks[0])==3 and series.set_deck(0,sorted).is_empty(),"sorting cannot change the count")
 var invalid=swapped(decks[0],3);invalid.leader=decks[1].leader
 check(not series.set_deck(0,invalid).is_empty(),"revealed leader cannot be replaced")
 invalid=swapped(decks[0],3);invalid.main[10]="164"
 check(not series.set_deck(0,invalid).is_empty(),"outside cards cannot enter the registered pool")
 invalid=decks[0].duplicate(true);invalid.side.append(invalid.main.pop_back())
 check(not series.set_deck(0,invalid).is_empty(),"main and side counts must be restored")
 series.ready(0)
 check(not series.set_deck(0,decks[0]).is_empty() and not series.prepare_choice(),"ready player is locked while opponent prepares")
 series.ready(1);series.prepare_choice()
 check(series.state.status=="choosing" and not series.start_game(),"second confirmation opens dice choice without starting early")
 series.choose_first(series.state.chooser,true)
 check(series.start_game() and series.state.registered==decks,"opening game preserves registration before swaps")
 check(series.record_result(0) and series.state.status=="complete" and series.state.scores==[1,0],"one victory completes BO1 with sideboarding")
 check(series.rematch().is_empty() and series.state.format==Series.BO1_SIDEBOARD and series.state.registered==[{},{}],"rematch resets registration and keeps the new format")
 for seat in [0,1]:series.ready(seat)
 series.prepare_choice()
 check(series.state.status=="sideboarding","rematch repeats the pregame preparation phase")
 for format_value in [Series.BO1,Series.BO3]:
  var plain=Series.new();plain.setup(format_value,true,"test")
  for seat in [0,1]:plain.set_deck(seat,decks[seat]);plain.ready(seat)
  plain.prepare_choice();plain.choose_first(plain.state.chooser,true);plain.start_game();plain.record_result(0)
  check(plain.state.status==("complete" if format_value==Series.BO1 else "between"),"existing %s keeps its opening and victory rules" % Series.format_label(format_value))
  if format_value==Series.BO3:check(plain.set_deck(1,swapped(decks[1],4)).is_empty(),"BO3 sideboarding still allows more than three cards")

func run():
 var decks=[Fixtures.deck("70"),Fixtures.deck("68")]
 check_rules(decks)
 host=Session.new();guest=Session.new();root.add_child(host);root.add_child(guest)
 var run_id=str(Time.get_ticks_usec())
 host.initialize("res://work/bo1-sideboard/%s-host" % run_id);guest.initialize("res://work/bo1-sideboard/%s-guest" % run_id)
 var rejections=[];host.error_raised.connect(func(message):rejections.append(message));guest.error_raised.connect(func(message):rejections.append(message))
 check(host.create_room(Series.BO1_SIDEBOARD,true,48031,"127.0.0.1","test").is_empty(),"new format host listens")
 check(guest.join_room("127.0.0.1",48031).is_empty(),"guest joins new format")
 if not await until(func():return not host.applicant.is_empty()):
  check(false,"approval arrives: "+host.notice+" / "+guest.notice);host.leave(false);guest.leave(false);quit(1);return
 check(true,"approval arrives")
 host.accept_applicant(true);check(await until(func():return host.can_act() and guest.can_act()),"both players connected")
 host.room_action({"name":"deck","deck":decks[0]});guest.room_action({"name":"deck","deck":decks[1]})
 check(await until(func():return guest.room.own_deck==decks[1] and host.can_act() and guest.can_act()),"decks synchronized")
 host.room_action({"name":"ready"});guest.room_action({"name":"ready"})
 check(await until(func():return guest.room.status=="sideboarding" and host.can_act() and guest.can_act()),"both clients enter pregame preparation")
 check(host.authority==null and guest.latest_snapshot.is_empty() and guest.room.leaders==host.room.leaders,"reveal arrives before any battle snapshot")
 var registration=host.series.state.registered.duplicate(true)
 guest.room_action({"name":"deck","deck":swapped(decks[1],3)})
 check(await until(func():return guest.room.own_deck==swapped(decks[1],3) and guest.can_act()),"three-card submission acknowledged")
 guest.room_action({"name":"deck","deck":swapped(decks[1],4)})
 check(await until(func():return not guest.busy and not rejections.is_empty()),"authority rejects fourth card")
 check(host.series.state.decks[1]==swapped(decks[1],3) and host.series.state.registered==registration,"repeated network submissions cannot bypass the limit")
 var restored=Series.new();restored.state=host.Journal.load_from(host.storage+"/host.bin").series
 check(restored.public_state(1).own_registered==decks[1] and restored.set_deck(1,swapped(decks[1],4)).contains("3"),"restored preparation preserves the limit and original registration")
 host.on_disconnect(host.remote_peer);host.transport.drop(host.remote_peer)
 check(await until(func():return host.can_act() and guest.can_act(),12),"reconnection resumes pregame preparation")
 check(guest.room.status=="sideboarding" and guest.room.own_registered==decks[1] and host.authority==null,"reconnection does not skip preparation or reset the count")
 guest.room_action({"name":"ready"});await until(func():return guest.room.ready[1] and guest.can_act())
 guest.room_action({"name":"unready"})
 check(await until(func():return not guest.room.ready[1] and guest.can_act()),"ready can be canceled during pregame preparation")
 await prepare(false)
 var cards=host.authority.players[1].deck+host.authority.players[1].hand
 check(host.series.state.registered==registration and cards.filter(func(card):return card.card_id=="100").size()==3,"engine starts with swapped cards and preserves the original pool")
 await concede(1)
 check(host.room.status=="complete" and guest.room.status=="complete","single result ends the new format on both clients")
 host.room_action({"name":"rematch"})
 check(await until(func():return guest.room.status=="lobby" and host.can_act() and guest.can_act()),"rematch returns both players to registration")
 host.room_action({"name":"ready"});guest.room_action({"name":"ready"})
 check(await until(func():return guest.room.status=="sideboarding" and host.can_act() and guest.can_act()),"rematch reveals leaders and prepares again")
 await prepare()
 check(host.series.state.round==1,"both players can skip swaps and start the rematch")
 host.leave(false);guest.leave(false)
 print("BO1 SIDEBOARD ",checks," checks; failures=",failures)
 quit(0 if failures.is_empty() else 1)
