extends "res://tests/test_v092.gd"
func run():
 var saved=FileAccess.get_file_as_string(Store.SAVE_PATH)
 app=load("res://main.tscn").instantiate()
 root.add_child(app)
 await process_frame
 app.load_test_decks()
 app.begin_battle(true)
 view=app.duel_view
 view.set_process(false)
 e=view.engine

 clean()
 var spell=put("96","hand")
 var friendly=put("53","field")
 var enemy=put("54","field",1)
 var red=put("165","palette")
 var yellow=put("164","palette")
 e.players[0].life=27
 e.players[1].life=8
 view.render()
 await settle()
 expect(view.life_widgets[0].bar.value==20 and "27" in view.life_widgets[0].button.text,"life above twenty displays its full value")
 expect(view.life_widgets[1].bar.value==8 and view.life_widgets[1].bar.max_value==20,"opponent life uses proportional fill")
 var before=snapshot()
 view.request_cast(spell.uid)
 expect(view.local.get("mode")=="target" and [friendly.uid,enemy.uid].all(func(uid):return uid in view.highlights()),"targeted spell highlights both battlefield units")
 expect(view.life_widgets[0].legal and view.life_widgets[1].legal,"both players are legal targets")
 await click(point(enemy.uid))
 expect(view.picker.ready() and enemy.uid in view.selected_uids() and snapshot()==before,"selecting enemy target is private")
 await click(view.life_widgets[0].button.get_global_rect().get_center())
 expect(view.picker.option()=={"player":0} and snapshot()==before,"player target replaces unit target privately")
 await click(point(enemy.uid))
 expect(view.picker.option().get("uid",-1)==enemy.uid,"unit target can be selected again")
 expect(find_button(view.ui,"发动")!=null and view.payment_ready(),"complete target and payment offer activate")
 await press("发动")
 await settle()
 expect(spell.zone=="stack" and e.stack.back().target.uid==enemy.uid and red.tapped and yellow.tapped,"activate commits target and colors once")
 expect(view.stack_target_arrows().size()==1 and view.stack_target_arrows()[0].target.uid==enemy.uid,"stack arrow follows selected unit")
 expect(not view.stack_panel.tiles[e.stack.back().id].tile.get_meta("selected"),"committed stack card has no private selection border")
 resolve()
 view.render()
 await settle()
 expect(view.stack_target_arrows().is_empty(),"resolved stack entry removes target arrow")

 clean()
 var hostile=put("96","hand",1)
 put("165","palette",1)
 put("164","palette",1)
 var counter=put("100","hand")
 put("70","field")
 put("164","palette")
 put("164","palette")
 e.priority=1
 var error=e.commit_cast(1,hostile.uid,{"player":0},e.payment(1,e.cards["96"].cost).plan)
 view.render()
 await settle()
 view.request_cast(counter.uid)
 expect(error.is_empty() and view.stack_panel.tiles[e.stack[0].id].tile.get_meta("legal"),"legal stack counter target is highlighted")
 await click(view.stack_panel.card_rect(hostile.uid).get_center())
 expect(view.picker.ready() and view.stack_panel.tiles[e.stack[0].id].tile.get_meta("selected"),"chosen stack counter target is selected")
 await press("发动")
 await settle()
 expect(counter.zone=="stack" and view.stack_target_arrows().size()==2,"counter has its own stack target arrow")
 resolve()
 view.render()
 await settle()
 expect(hostile.zone=="grave" and view.stack_target_arrows().is_empty(),"resolved counter leaves no dangling arrows")
 expect(FileAccess.get_file_as_string(Store.SAVE_PATH)==saved,"saved decks unchanged")
 print("V016_TARGETS: %d checks; %d failures" % [checks,failures.size()])
 quit(0 if failures.is_empty() else 1)
