extends "res://tests/support/rules_base.gd"
const Preview=preload("res://scripts/rules/spell_damage_preview.gd")
const UnknownArt=preload("res://scripts/unknown_card_art.gd")
const SeatView=preload("res://net/seat_projection.gd")
const Observer=preload("res://net/observer_projection.gd")
const Remote=preload("res://net/remote_duel.gd")
func run():
 fresh();mana();put("character-fdf-117")
 var spell=put("spell-fdf-071","hand")
 expect(Preview.caption(e,spell).begins_with("预计伤害：2 点"),"Barrage starts at two damage per target")
 var ufo=put("token-fdf-131");var alien=put("character-fdf-115")
 var aya=put("18");var ordinary=put("53");ordinary.plus_counters=10
 cast("spell-fdf-072",{"uid":aya.uid,"epoch":aya.epoch,"mode":"名称改为不明物体并抓牌"})
 put("token-fdf-131","field",1);put("token-fdf-131","grave");put("token-fdf-131","palette")
 expect(Preview.caption(e,spell).begins_with("预计伤害：5 点") and Preview.caption(e,spell).contains("己方不明物体：3 个"),"Barrage counts renamed units, native UFOs and aliens only on the controller's field")
 var before=JSON.stringify([e.players,e.stack,e.revision])
 Preview.caption(e,spell,{"uid":spell.uid,"mode":"target"})
 expect(JSON.stringify([e.players,e.stack,e.revision])==before,"Barrage preview does not change state")
 var target=e.targets_for(spell.card_id,0,spell.uid)[0].duplicate(true)
 target.erase("selection");target.picks=[[{"player":1},e.ref_target(ordinary),e.ref_target(aya)]]
 var error=e.commit_cast(0,spell.uid,target,e.payment(0,e.cast_cost(0,spell)).plan)
 expect(error.is_empty(),"Barrage commits three different targets: "+error)
 e.move_to(ufo,"grave")
 expect(Preview.caption(e,spell).begins_with("预计伤害：4 点"),"stack preview refreshes when an unknown leaves")
 for seat in range(2):
  var remote=Remote.new();remote.apply_snapshot(SeatView.build(e,seat))
  expect(Preview.caption(remote,remote.find_card(spell.uid)).begins_with("预计伤害：4 点"),"Barrage stack preview matches for network seat "+str(seat))
 var observer=Remote.new();observer.apply_snapshot(Observer.build(e))
 expect(Preview.caption(observer,observer.find_card(spell.uid)).begins_with("预计伤害：4 点"),"Barrage spectator preview matches")
 one()
 expect(e.players[1].life==16 and ordinary.damage==4 and aya.zone=="grave","Barrage deals the previewed four damage to each selected target")
 expect(not UnknownArt.active(e,aya) and aya.card_id=="18","leaving the field removes noise and restores the original card")
 var nightmare=put("spell-fdf-072","hand")
 for id in ["token-fdf-131","token_ufo","character-fdf-115"]:
  var native=put(id)
  e.Cat.Spells.resolve(e,{"owner":0,"card":nightmare,"target":{"uid":native.uid,"epoch":native.epoch,"mode":"名称改为不明物体并抓牌"}})
  expect(not UnknownArt.active(e,native),"Nightmare leaves native UFO art clear: "+id)
 expect(Preview.caption(e,{"card_id":"spell-fdf-071","network_hidden":true}).is_empty(),"hidden cards never expose their preview")
 print("WANDERING_BARRAGE: ",checks," checks; ",failures.size()," failures")
 quit(0 if failures.is_empty() else 1)
