extends "res://tests/support/rules_base.gd"
const Env=preload("res://scripts/ai/game_environment.gd")
const Actions=preload("res://scripts/ai/algorithm_actions.gd")
const Value=preload("res://scripts/ai/position_evaluator.gd")
const State=preload("res://scripts/ai/simulation_state.gd")
const Shared=preload("res://scripts/ai/action.gd")
const Pressure=preload("res://scripts/ai/pressure_policy.gd")
const Agent=preload("res://scripts/ai/decision_agent.gd")
func run():
 fresh()
 e.players[0].leader=e.make_card("74",0,"field",true);e.players[0].field.append(e.players[0].leader)
 put("165","palette");put("165","palette");put("168","palette");put("168","palette");put("168","palette")
 put("109","hand");put("spell-ucs-052","hand");put("143","hand")
 put("18","field",1);put("character-fdn-014","field",1)
 var fingerprint=JSON.stringify(State.capture(e));var f=Value.strategic_features(e,0)
 expect(f.size()==Value.DEFAULT_WEIGHTS.size()+Value.Strategic.KEYS.size(),"strategic feature schema includes all versioned features")
 expect(f.values().all(func(n):return is_finite(float(n))),"strategic features are finite")
 expect(f.gungnir_payable==1 and f.hard_removal_cards==1,"strategic features represent playable response and retained hard removal")
 expect(JSON.stringify(State.capture(e))==fingerprint,"feature extraction leaves gameplay, memory and RNG unchanged")
 var env=Env.new();env.setup(e)
 var menu=env.legal_actions()
 expect(menu.actions.size()>4,"algorithm menu includes targets and payment variants")
 expect(menu.actions.filter(func(a):return a.action.kind=="cast" and a.action.card_id=="109").size()>1,"Gungnir targets are not restricted to one heuristic choice")
 expect(menu.actions.filter(func(a):return a.action.kind=="cast" and a.action.card_id=="143").any(func(a):return a.action.target.get("mode","")=="失去生命"),"Aurora modes are represented")
 var ids=[]
 for row in menu.actions:
  expect(row.id not in ids,"action ids have no collision in the menu");ids.append(row.id)
  var probe=State.fork(e,0)
  expect(Shared.apply(probe,0,row.action),"enumerated action is accepted by the authority")
 expect(JSON.stringify(State.capture(e))==fingerprint,"enumeration and action validation leave original state unchanged")
 put("18","hand",1);var original_menu=Env.new();original_menu.setup(e)
 var before=original_menu.legal_actions();var before_features=Value.strategic_features(e,0)
 e.players[1].hand.back().card_id="109";e.players[1].deck[0].card_id="165"
 var hidden_menu=Env.new();hidden_menu.setup(e)
 expect(hidden_menu.legal_actions()==before and Value.strategic_features(e,0)==before_features,"unknown opponent identities and deck order cannot alter observed features or action mask")
 var clone=env.clone();var clone_life=e.players[0].life;clone.engine.players[0].life-=3
 expect(e.players[0].life==clone_life,"environment clone isolates live state")
 var invalid=env.apply_action(-7)
 expect(invalid.has("error") and e.players[0].life==clone_life,"invalid action id is rejected without changing state")
 expect(env.returns().is_empty(),"nonterminal states do not fabricate terminal rewards")
 e.winner=0
 expect(env.returns()==[1.0,-1.0],"terminal rewards are zero-sum actual outcomes")
 var deck=Store.blank("采样契约");deck.leader="70"
 for i in range(50):deck.main.append("164")
 var game=Env.new();var started=game.reset([deck,deck],0,23)
 expect(not started.has("error") and game.clean(),"reset advances actual rules to a main decision")
 var observer=game.current_player();var sample=game.resample_from_infostate(observer,919)
 expect(not sample.has("error"),"explicit deck priors produce a consistent hidden world")
 if not sample.has("error"):
  expect(sample.environment.observation(observer)==game.observation(observer),"resampling preserves the root observation")
  expect(sample.environment.information_state_string(observer)==game.information_state_string(observer),"resampling preserves root information history")
  expect(not sample.environment.engine.players[1-observer].hand.any(func(c):return c.get("ai_unknown",false)),"sampled hidden hand becomes a hypothetical playable world")
  var repeat=game.resample_from_infostate(observer,919)
  expect(State.capture(sample.environment.engine)==State.capture(repeat.environment.engine),"sample seed reproduces hypothetical world and RNG")
 var no_prior=Env.new();no_prior.setup(e)
 expect(no_prior.resample_from_infostate(0,3).has("error"),"information-set search refuses unspecified deck priors")
 fresh();e.players[0].leader=e.make_card("74",0,"field",true);e.players[0].field.append(e.players[0].leader)
 e.players[1].leader.timer=9
 for id in ["165","165","168","168"]:put(id,"palette")
 put("109","hand");var queen=put("spell-fdf-037","hand");put("169","hand")
 var aggro=Env.new();aggro.setup(e)
 var unrestricted=aggro.policy_actions()
 expect(unrestricted.guard=="none" and unrestricted.ids.size()==aggro.legal_actions().actions.size(),"without a forecast threat Castle/bats can spend response colors")
 var zero_weights={}
 for key in Value.DEFAULT_WEIGHTS.keys()+Value.Strategic.KEYS:zero_weights[key]=0.0
 var saved=State.capture(e);var trace=Agent.step(e,0,e.RemiliaAI,zero_weights)
 expect(trace.get("candidates",[]).any(func(row):return row.action.get("card_id","")=="spell-fdf-037"),"expanded offline agent considers the bats route without forecast risk")
 State.restore(e,saved)
 e.players[1].leader.timer=0;put("170","field",1)
 for id in ["165","165","165","167","167","167"]:put(id,"palette",1)
 var threatened=Env.new();threatened.setup(e)
 var forecast=Pressure.forecast(e,0)
 expect(forecast.risk and forecast.threats.any(func(t):return t.card_id=="70"),"public affordable Reimu is a forecast high-risk entry")
 var guard=threatened.policy_actions();var all_menu=threatened.legal_actions()
 var queen_ids=all_menu.actions.filter(func(a):return a.action.get("uid",-1)==queen.uid).map(func(a):return a.id)
 expect(guard.guard=="public_high_risk_gungnir_reserve" and not queen_ids.is_empty() and not queen_ids.any(func(id):return id in guard.ids),"predicted high-risk entry prevents Queen spending the last red/black response colors")
 expect(all_menu.actions.filter(func(a):return a.action.kind=="pass")[0].id in guard.ids,"conditional reserve always permits pass")
 var conditional=Value.strategic_features(e,0)
 expect(conditional.required_gungnir_reserve==1 and conditional.needless_gungnir_reserve==0,"training distinguishes necessary from unnecessary response reserve")
 saved=State.capture(e);trace=Agent.step(e,0,e.RemiliaAI,zero_weights)
 expect(not trace.get("fallback",false) and not trace.candidates.any(func(row):return row.action.get("card_id","")=="spell-fdf-037"),"expanded offline agent also protects red/black only at forecast high risk")
 State.restore(e,saved)
 fresh();e.players[1].leader.timer=9
 var flandre=put("character-fdf-ex01","field",1)
 expect(not Pressure.high_risk(e,flandre,0),"ordinary Flandre without commander abilities is not an automatic high-risk core")
 put("170","field",1)
 expect(Pressure.high_risk(e,flandre,0),"Shrine-enabled Flandre is a high-risk core")
 expect(Pressure.high_risk(e,put("39","field",1),0),"small Youmu is included in the requested risk set")
 fresh();e.players[0].leader=e.make_card("74",0,"field",true);e.players[0].field.append(e.players[0].leader);e.players[1].leader.timer=9
 for id in ["167","167","166","166"]:put(id,"palette",1)
 var cloud=put("character-fdf-046","hand",1)
 expect(not Pressure.forecast(e,0).risk,"hidden Cloud alone cannot cause forced reserve")
 e.reveal_card(cloud)
 expect(Pressure.forecast(e,0).risk,"public known Cloud with payable duel can cause reserve")
 print("AI environment: ",checks," checks, ",failures.size()," failures")
 quit(0 if failures.is_empty() else 1)
