extends "res://tests/support/rules_base.gd"
const Picker=preload("res://scripts/target_picker.gd")
const StackPanel=preload("res://scripts/duel_stack.gd")
const SeatView=preload("res://net/seat_projection.gd")
const Remote=preload("res://net/remote_duel.gd")

func run():
 fresh();mana()
 e.players[0].leader=e.make_card("character-fdf-117",0,"leader",true)
 var unknown=put("token-fdf-131")
 var ally=put("53")
 put("53","field",1)
 var spell=put("spell-fdf-072","hand")
 var options=e.targets_for(spell.card_id,0,spell.uid)
 var picker=Picker.new()
 picker.configure(options,"nightmare")
 var modes=picker.available()
 expect(modes.size()==2 and modes[0].value=="名称改为不明物体并抓牌" and modes[1].value=="牺牲并放入封兽鵺","Nightmare first shows exactly its two printed modes")
 picker.select(modes[0])
 expect(picker.available_refs().size()==3 and picker.prompt()=="名称改为不明物体并抓牌","rename mode then asks for a unit")
 picker.select_target(e.ref_target(ally))
 expect(picker.ready() and picker.option().uid==ally.uid and picker.option().mode=="名称改为不明物体并抓牌","rename mode returns the chosen legal target")
 var target=picker.option()
 var error=e.commit_cast(0,spell.uid,target,e.payment(0,e.cast_cost(0,spell,target)).plan)
 expect(error.is_empty(),"Nightmare rename mode casts: "+error)
 var remote=Remote.new();remote.apply_snapshot(SeatView.build(e,1))
 var stack=StackPanel.new()
 expect(stack.chosen_mode(remote.stack.back())=="已选择：名称改为不明物体并抓牌","opponent sees the declared mode on the stack")
 one()
 expect(e.cards[ally.card_id].name=="不明物体" and unknown.zone=="field","rename mode resolves without sacrificing an unknown")

 fresh();mana()
 e.players[0].leader=e.make_card("character-fdf-117",0,"leader",true)
 unknown=put("token-fdf-131")
 put("53")
 spell=put("spell-fdf-072","hand")
 picker=Picker.new();picker.configure(e.targets_for(spell.card_id,0,spell.uid),"nightmare-sacrifice")
 modes=picker.available();expect(modes.size()==2,"one unknown still offers exactly two modes")
 picker.select(modes[1])
 expect(picker.prompt()=="牺牲一个不明物体" and picker.available_refs().size()==1,"sacrifice mode asks for an unknown")
 picker.select_target(e.ref_target(unknown))
 var finish=picker.available().filter(func(atom):return atom.kind=="finish_group")
 if not finish.is_empty():picker.select(finish[0])
 expect(picker.ready() and picker.option().mode=="牺牲并放入封兽鵺","sacrifice mode returns a complete choice")
 target=picker.option()
 error=e.commit_cast(0,spell.uid,target,e.payment(0,e.cast_cost(0,spell,target)).plan)
 expect(error.is_empty() and unknown.zone!="field","sacrifice mode pays its unknown cost: "+error)
 remote=Remote.new();remote.apply_snapshot(SeatView.build(e,1))
 expect(stack.chosen_mode(remote.stack.back())=="已选择：牺牲并放入封兽鵺","opponent sees the sacrifice mode on the stack")
 stack.free()
 print("MODAL_SPELL_CHOICES: ",checks," checks; ",failures.size()," failures")
 quit(0 if failures.is_empty() else 1)
