extends "res://tests/test_v0181_series.gd"
const Archive=preload("res://scripts/replay_archive.gd")
const Observer=preload("res://net/observer_projection.gd")
var spectator
func run():
 Store.Paths.root_override=ProjectSettings.globalize_path("res://work/portable-tests/"+str(Time.get_ticks_usec()))
 var loaded=Store.load_decks()
 check(not loaded.has("error") and loaded.decks.size()==4,"first launch creates four mdeck files")
 check(DirAccess.dir_exists_absolute(Store.Paths.root().path_join("replay")),"replay directory created at startup")
 check(Store.scan_files(Store.folder()).size()==4,"four individual UTF-8 deck files")
 var imported=loaded.decks[0].duplicate(true);imported.id="external-test";imported.name="外部导入"
 var path=Store.folder().path_join("收到的卡组.mdeck")
 check(Store.save_file(imported,path).is_empty(),"shareable deck written")
 var result=Store.load_decks()
 check(result.decks.size()==5 and result.decks.any(func(d):return d.id==imported.id),"re-enter discovers copied deck")
 var malformed=FileAccess.open(Store.folder().path_join("损坏.mdeck"),FileAccess.WRITE);malformed.store_string("bad");malformed.close()
 result=Store.load_decks()
 check(result.decks.size()==5 and result.warnings.size()==1,"bad import isolated from healthy decks")
 imported.name="重命名";check(Store.save_file(imported).is_empty() and Store.read_file(path).deck.name=="重命名","save updates original individual file")
 check(Store.delete_file(imported.id).is_empty() and Store.load_decks().decks.size()==4,"delete removes only selected file")
 for d in Store.load_decks().decks:Store.delete_file(d.id)
 check(Store.load_decks().decks.is_empty(),"deleted presets do not reappear on restart")
 check(Store.persist(loaded.decks).is_empty(),"restore test decks")
 host=Session.new();guest=Session.new();spectator=Session.new()
 for net in [host,guest,spectator]:root.add_child(net)
 host.initialize(Store.Paths.root().path_join("host"));guest.initialize(Store.Paths.root().path_join("guest"));spectator.initialize(Store.Paths.root().path_join("spectator"))
 var offers=[0,0,0]
 host.replay_finished.connect(func(_a):offers[0]+=1)
 guest.replay_finished.connect(func(_a):offers[1]+=1)
 spectator.replay_finished.connect(func(_a):offers[2]+=1)
 check(host.create_room(3,false,47981,"127.0.0.1").is_empty(),"host opens duel and spectator transports")
 check(host.spectator_hub.listening,"separate spectator port listening")
 guest.join_room("127.0.0.1",47981)
 check(await until(func():return not host.applicant.is_empty()),"player requests seat")
 host.accept_applicant(true)
 check(await until(func():return host.can_act() and guest.can_act()),"players synchronized")
 spectator.join_spectator("127.0.0.1",47981)
 check(await until(func():return spectator.connected),"observer joins full room")
 check(spectator.read_only and not spectator.can_act() and not spectator.can_act(true),"observer never receives action authority")
 for seat in [0,1]:host.handle_room_action(seat,{"name":"deck","deck":loaded.decks[seat]})
 await until(func():return guest.sequence==host.sequence)
 await prepare()
 check(await until(func():return not spectator.latest_snapshot.is_empty()),"observer receives authoritative battlefield")
 var view=spectator.latest_snapshot.projection
 check(view.state.players.all(func(p):return p.hand.all(func(c):return c.card_id=="back") and p.deck.all(func(c):return c.card_id=="back")),"both hands and libraries hidden from spectator")
 check(view.queries.get("actions",{}).is_empty() and view.queries.get("lookup",{}).is_empty() and spectator.room.own_deck.is_empty(),"no private choices or registered deck leak")
 var saved=host.Codec.capture(host.authority);var seq=host.sequence
 spectator.transport.send_to(1,{"type":"command","command":{"name":"surrender","args":[]}})
 await create_timer(0.3).timeout
 check(host.sequence==seq and host.Codec.capture(host.authority)==saved,"observer packet cannot alter game")
 spectator.leave(false)
 await create_timer(0.25).timeout
 check(host.can_act() and guest.can_act() and host.disconnected_at==0,"observer departure never pauses players")
 spectator.join_spectator("127.0.0.1",47981)
 check(await until(func():return not spectator.latest_snapshot.is_empty()),"observer may rejoin during play")
 spectator.transport.set_process(false)
 var started=Time.get_ticks_msec()
 for i in range(24):
  host.authority.note("观战队列测试 "+str(i));host.sequence+=1;host.publish()
 check(await until(func():return guest.sequence==host.sequence and host.can_act()),"player sync never waits for slow spectator acknowledgments")
 check(Time.get_ticks_msec()-started<5000,"spectator backpressure cannot stall player acknowledgments")
 spectator.transport.set_process(true)
 check(await until(func():return spectator.sequence==host.sequence),"slow observer catches up to authoritative state")
 check(spectator.snapshots.size()<=4 and spectator.latest_snapshot.projection.state.history==preload("res://net/observer_projection.gd").build(host.authority).state.history,"bounded observer queue preserves accurate final state and public log")
 spectator.leave(false)
 sync_views()
 await concede(1)
 check(offers==[0,0,0],"no replay prompt after BO3 game one")
 await prepare();await concede(0)
 check(offers==[0,0,0],"no replay prompt after BO3 game two")
 await prepare();await concede(1)
 check(offers==[1,1,0],"each player prompted once at series end")
 var archive=host.recording
 var restored=Archive.new();restored.begin_capture(host.storage+"/capture.bin",host.series.state.match_id)
 check(restored.frames.size()==archive.frames.size() and restored.frame(0)==archive.frame(0),"process recovery retains earlier games and recorded states")
 var rounds={}
 for f in archive.frames:rounds[f.round]=true
 check(rounds.size()==3 and archive.metadata.room.winner==0,"all three games stored in one replay")
 var file=archive.save(Store.Paths.root().path_join("replay/test.mreply"))
 check(file.has("path"),"mreply file saved")
 var readback=Archive.read(file.get("path",""))
 check(readback.has("archive"),"saved replay passes checksum and schema")
 if readback.has("archive"):
  check(readback.archive.frames.size()==archive.frames.size(),"replay retains every recorded state")
  for i in range(archive.frames.size()):check(readback.archive.frame(i)==archive.frame(i),"exact state playback step "+str(i))
 var bytes=FileAccess.get_file_as_bytes(file.path);bytes[bytes.size()-1]=bytes[bytes.size()-1]^1
 var broken=FileAccess.open(Store.Paths.root().path_join("replay/broken.mreply"),FileAccess.WRITE);broken.store_buffer(bytes);broken.close()
 check(Archive.read(Store.Paths.root().path_join("replay/broken.mreply")).has("error"),"damaged replay refused")
 host.leave(false);guest.leave(false)
 host.create_room(3,false,47981,"127.0.0.1")
 host.series.state.status="playing";host.series.state.scores=[0,1];host.room=host.series.public_state(0)
 host.disconnected_at=1;host.disconnect_deadline_unix=Time.get_unix_time_from_system()-1
 check(host.check_reconnect_timeout(Time.get_ticks_msec()) and host.room.winner==0 and host.room.status=="complete","30 second timeout awards entire BO3 to remaining host")
 check(host.room.scores==[0,1] and host.room.forfeit==1,"forfeit preserves played scores, marks actual loser")
 guest.room={"status":"playing","names":["房主","客机"],"ready":[false,false],"winner":-2,"format":3,"scores":[1,0]};guest.room_id="local-record"
 guest.end_disconnected_match()
 check(guest.room.winner==1 and guest.room.local_record and "本地记录" in guest.connection_status(),"host timeout is labeled local guest win")
 for net in [host,guest,spectator]:net.leave(false);net.queue_free()
 print("PORTABLE: ",checks," checks; ",failures.size()," failures")
 quit(0 if failures.is_empty() else 1)
