extends "res://tests/test_v012_rules.gd"
const DuelView=preload("res://scripts/duel_view.gd")
func choose_groups(options: Array,picks: Array,index: int=0) -> Dictionary:
 var t=options[index].duplicate(true);t.erase("selection");t.picks=picks;return t
func cat_trigger(c: Dictionary,k: String,t: Dictionary={"none":true},data: Dictionary={}):
 var source=c.duplicate(true)
 e.damage_context={"source":source,"combat":false,"single":true}
 expect(e.Cat.resolve_trigger(e,{"source":source,"effect":k,"owner":c.owner,"target":t,"data":data,"optional":false,"name":e.cards[c.card_id].name}),"trigger contract "+k)
 e.damage_context={}
func check_needle_wait():
 fresh();var needle_view=DuelView.new();needle_view.engine=e
 var needle_discard_a=put("164","hand",1);var needle_discard_b=put("164","hand",1)
 var needle_big=put("50","field",1);var needle_small=put("51","field",1)
 expect(needle_view.free_main(),"needle fixture starts in free main phase")
 resolve_spell("spell-fdf-121")
 expect(e.pending.get("kind","")=="effect_choice" and e.pending.owner==1 and e.pending.trigger.effect=="cat:atonement_discard","needle waits for opponent discard")
 expect(not needle_view.free_main(),"needle discard hides end main phase")
 e.phase="end";e.cleanup_end()
 expect(not e.cleanup_done and e.pending.trigger.effect=="cat:atonement_discard","end cleanup waits for opponent choice")
 e.phase="main"
 var needle_turn=e.turn;e.pass_priority(0);e.finish_turn()
 expect(e.turn==needle_turn and e.phase=="main","needle discard blocks turn end")
 e.choose_effect(choose_groups(e.pending.options,[[e.Cat.ref(e,needle_discard_a),e.Cat.ref(e,needle_discard_b)]]))
 expect(e.pending.get("kind","")=="effect_choice" and e.pending.owner==1 and e.pending.trigger.effect=="cat:move","needle waits for opponent sacrifice")
 expect(not needle_view.free_main(),"needle sacrifice hides end main phase")
 e.pass_priority(0);e.finish_turn()
 expect(e.turn==needle_turn and needle_big.zone=="field","needle sacrifice blocks turn end")
 e.choose_effect(choose_groups(e.pending.options,[[e.ref_target(needle_big)]]))
 expect(e.pending.is_empty() and needle_big.zone=="grave" and needle_small.zone=="field" and needle_view.free_main(),"needle resumes only after opponent finishes")
 needle_view.free()
func run():
 var saved=FileAccess.get_file_as_string(Store.SAVE_PATH)
 check_needle_wait()
 fresh();var a=put("character-fdf-100");var sp=e.stat(a,"spirit");var pw=e.stat(a,"power");var hp=e.stat(a,"health")
 put("99","grave",1);put("96","grave",1);put("50","grave",1)
 expect(e.stat(a,"spirit")==sp+2 and e.stat(a,"power")==pw and e.stat(a,"health")==hp,"Murasa +X modifies spirit only, counts opposing spells")
 e.players[1].deck.resize(20);var b=put("50","field",1);cat_trigger(a,a.card_id);expect(b.minus_counters==1,"Murasa end step shrinks enemies at 20 cards")
 fresh();a=put("character-fdn-013");b=put("2");expect(e.stat(a,"power")==e.cards[a.card_id].power+1 and e.stat(a,"spirit")==e.cards[a.card_id].spirit+1,"forest fairy counts another fairy")
 fresh();a=put("character-fdf-117");a.leader_counters=1;b=put("token-fdf-131");expect(e.stat(b,"power")==4 and e.stat(b,"health")==4 and e.stat(b,"spirit")==4,"Nue boosts intimidating units")
 var base=b.card_id;e.Cat.unknown(e,a);expect(e.cards[a.card_id].name=="不明物体" and e.cards[a.card_id].kind=="单位" and not e.Cat.has(e,a,"character-fdf-117:self"),"Nue transformed unit loses self ability")
 e.move_to(a,"hand");expect(a.card_id=="character-fdf-117","transformation resets on leaving battlefield")
 fresh();a=put("character-fdn-007");e.players[0].leader=a;a.zone="exile";e.players[0].field.erase(a);e.players[0].exile.append(a)
 for id in ["50","51","52","53","54","55"]:put(id)
 b=put("2","hand");expect(e.field_error(b,0).is_empty(),"designated habitat permits fairy at full field even while exiled")
 fresh();a=put("character-fdf-104");for id in ["50","51","52","53","54"]:put(id)
 b=e.Cat.token(e,0,"虫群",1,1,1,["黄"]);expect(not b.is_empty() and e.field_slots(0)==6,"Wriggle token can enter a full six slot battlefield")
 fresh();a=put("character-fdn-007");b=put("character-fdn-006");e.Cat.State.sync_fairies(e)
 expect(e.Cat.has(e,a,"character-fdn-006") and e.cards[a.card_id].copy_source_id=="character-fdn-007","habitat inherits fairy activated abilities")
 e.move_to(b,"hand");e.judge();expect(not e.Cat.has(e,a,"character-fdn-006"),"habitat stops inheriting after fairy leaves")
 e.move_to(a,"grave");expect(a.card_id=="character-fdn-007" and not a.get("inherited_self",false),"habitat leaves as original card")
 fresh();a=put("character-fdf-098")
 expect(not e.available_actions(0,a.uid,true).any(func(action):return action.type=="extension" and action.key=="character-fdf-098"),"Tewi has no advance tap activation")
 expect(not e.extension_activation_error(0,a,a.card_id).is_empty() and not e.commit_extension(0,a.uid,{"none":true},[],a.card_id).is_empty() and not a.tapped and e.players[0].get("mana",[]).is_empty(),"Tewi cannot float yellow-green mana before a payment")
 var paired=e.payment(0,{"黄":1,"绿":1})
 expect(paired.ways==1 and paired.plan.size()==1 and paired.plan[0].uid==a.uid and paired.plan[0].color=="黄/绿","Tewi is one atomic yellow-green payment source")
 expect(e.payment(0,{"黄":1}).ways==0 and e.payment(0,{"绿":1}).ways==0,"Tewi cannot split yellow and green across payments")
 var tewi_spell=put("character-smm05","hand")
 expect(e.commit_cast(0,tewi_spell.uid,{},paired.plan).is_empty() and a.tapped and e.players[0].get("mana",[]).is_empty() and e.stack.size()==1,"casting a yellow-green card taps Tewi at payment, without floating mana")
 expect(not e.source_resources(0).any(func(r):return r.uid==a.uid) and e.payment(0,{"黄":1,"绿":1}).ways==0,"tapped Tewi cannot be offered for another payment")
 fresh();a=put("character-fdf-098");b=put("character-fdf-101","field",1);b.locked_name=e.cards[a.card_id].name
 expect(not e.source_resources(0).any(func(r):return r.uid==a.uid) and e.payment(0,{"黄":1,"绿":1}).ways==0,"Tewi cannot pay while its ability is locked")
 fresh();a=put("spell-ucs-031","field",1);b=put("50");expect(not e.can_attack(0,b.uid),"Private Square prevents unpaid attack");var resource=put("164","palette")
 expect(e.can_attack(0,b.uid),"attack becomes available with tax mana");e.attack(0,b.uid,{},[]);expect(resource.tapped and not e.combat.is_empty(),"attack commits tax before declaration")
 fresh();mana();a=put("spell-fdn-015","field",1);b=put("character-fdf-110","field",1);var c=put("spell-fdf-049","hand")
 var cost=e.cast_cost(0,c,e.ref_target(b));expect(cost.get("红/蓝/绿/黄/黑",0)==3,"fog taxes spells targeting opposing Oni by three")
 a=put("character-fdn-027");expect(e.extension_cost(0,a,a.card_id,e.ref_target(b)).get("红/蓝/绿/黄/黑",0)==3,"fog taxes activated abilities too")
 fresh();a=put("character-ucs-046");expect(e.targets_for("spell-fdf-049",0).all(func(t):return not t.has("player")),"Nitori removes both players from spell targets")
 fresh();a=put("character-ucs-061");b=put("50");c=put("spell-fdf-049","hand",1);e.cards[c.card_id].fast=true
 expect(not e.targets_for(c.card_id,1).any(func(t):return t.get("uid")==b.uid),"Tenshi protects allied units from high speed spell targets")
 e.cards[c.card_id].fast=false;expect(e.targets_for(c.card_id,1).any(func(t):return t.get("uid")==b.uid),"Tenshi permits regular spell targets")
 fresh();a=put("character-fdn-045");expect(not e.can_attack(0,a.uid),"Goliath cannot attack without Alice");e.Roster.on_phase(e,"end");expect(e.triggers.is_empty(),"Goliath doesn't trigger without Alice")
 put("character-fdf-112");expect(e.can_attack(0,a.uid),"Alice enables Goliath attack");e.Roster.on_phase(e,"end");expect(e.triggers.size()==1,"Alice enables Goliath end trigger")
 fresh();put("spell-fdf-044");a=put("50");expect(not e.can_attack(0,a.uid),"law fire blocks counterless units");a.plus_counters=1;expect(e.can_attack(0,a.uid),"law fire allows units carrying counters")
 fresh();a=put("character-fdf-090");b=put("50","field",1);e.attack(0,a.uid);e.pass_priority(e.priority);e.pass_priority(e.priority)
 expect(e.pending.get("kind")=="block" and e.must_block(),"Reisen creates mandatory block decision");e.block([]);expect(e.pending.get("kind")=="block","empty block rejected when a blocker exists")
 fresh();a=put("spell-fdn-019");b=put("character-fdn-021");e.move_to(b,"grave",false);expect(e.triggers.size()==2,"price of life doubles own death trigger");settle();expect(e.players[0].hand.size()==8,"doubled death draw resolves twice")
 fresh();a=put("character-ucs-066");b=put("character-fdn-021");e.move_to(b,"grave",false);expect(e.triggers.is_empty(),"Yachie suppresses death abilities")
 fresh();a=put("character-fdf-041");b=put("spell-fdf-040");b.timer=2;e.Roster.on_phase(e,"end");expect(e.triggers.size()==2,"Sakuya doubles friendly time spell trigger");settle();expect(e.players[1].life==18,"both duplicated time effects resolve")
 fresh();a=put("character-fdf-119");c=put("spell-fdf-049","hand");e.Roster.on_cast(e,c,0,"hand");e.Roster.on_cast(e,c,0,"hand");expect(e.triggers.size()==1,"Patchouli once per turn role spell damage");expect(not e.triggers[0].ability_text.is_empty(),"catalogue trigger has readable caption")
 fresh();a=put("character-htk-005");b=put("50");c=put("51");e.sacrifice(b);e.sacrifice(c);expect(e.triggers.size()==1,"Doremy coalesces several sacrifices in same action")
 fresh();a=put("character-fdn-004");e.move_to(a,"grave",false);settle();expect(a.zone=="hand","Mokou returns to hand after death")
 fresh();a=put("character-fdn-042");b=put("50","field",1);e.damage_context={"source":b,"combat":false,"single":true};e.damage_target(e.ref_target(a),1);e.move_to(a,"grave",false);settle();expect(e.delayed.size()==1,"Utsuho remembers noncombat damage before death")
 e.turn+=1;e.run_delayed("prepare");settle();expect(a.zone=="field","Utsuho returns next prepare")
 fresh();a=put("character-fdn-042");e.move_to(a,"grave",false);expect(e.delayed.is_empty(),"Utsuho no return when not hit by noncombat damage")
 fresh();a=put("character-fdf-069");a.plus_counters=2;var power=e.stat(a,"power");b=put("50","field",1);b.plus_counters=20;e.move_to(a,"grave",false);e.pump_choices()
 e.choose_effect(choose_groups(e.pending.options,[[e.ref_target(b)]]));settle();expect(b.damage==power,"Kyouko death uses last battlefield power")
 fresh();a=put("field-rei-013");b=put("50","field",1);cat_trigger(a,a.card_id,{"picks":[[e.ref_target(b)]]});expect(b.zone=="exile","castle temporarily exiles unit");e.move_to(a,"grave");settle();expect(b.zone=="field" and b.owner==1,"castle leaving returns captured unit")
 fresh();a=put("character-ucs-021");b=e.players[0].deck[0];cat_trigger(a,a.card_id);e.choose_effect(choose_groups(e.pending.options,[[Pack.ref(e,b)]]));expect(b.zone=="exile" and b.dream==1,"Merry searches and places dream counter")
 a=put("character-ucs-020");cat_trigger(a,a.card_id);expect(b.zone=="hand" and not b.has("dream"),"Renko recovers dream marked exile")
 fresh();mana();a=put("character-ucs-068");b=put("50","hand");e.Roster.to_top(e,b);expect(e.Cat.may_peek(e,0) and e.cast_error(0,b.uid).is_empty(),"Okina enables top unit cast");var beneath=e.players[0].deck[1];expect(not e.Cat.State.permission(e,beneath,0),"Okina doesn't grant deeper library access")
 fresh();mana();a=put("character-fdf-102");a.leader_counters=1;b=put("spell-fdf-049","palette");expect(e.cast_error(0,b.uid).is_empty() and e.cast_cost(0,b).values().all(func(v):return v==0),"Youmu casts role spell free from palette")
 expect(e.commit_cast(0,b.uid,{"player":1},[]).is_empty(),"palette cast commits");settle();c=put("spell-fdf-049","palette");expect(not e.Cat.State.permission(e,c,0),"palette self ability limited to once per own turn")
 fresh();a=put("character-fdf-029","grave");b=put("spell-fdf-045","hand");expect(e.Cat.State.role_present(e,b,0),"grave Komachi supplies character constraint")
 fresh();a=put("character-fdf-046","hand");mana();var o=e.targets_for(a.card_id,0,a.uid);var t=o[1];var before=e.cast_cost(0,a,o[0]).get("绿",0);expect(e.cast_cost(0,a,t).get("绿",0)==before+1,"Ichirin optional green additional cost")
 b=put("50","field",1);b.plus_counters=5;expect(e.commit_cast(0,a.uid,t,e.payment(0,e.cast_cost(0,a,t)).plan).is_empty(),"Ichirin additional payment commits");settle();expect(not e.combat.is_empty() or not e.combat_queue.is_empty(),"Ichirin starts actual battle with block window")
 fresh();mana();put("character-fdf-112");a=put("spell-fdf-030","hand");b=put("7","hand");o=e.targets_for(a.card_id,0,a.uid);expect(not o.is_empty(),"alternate doll pitch choices exist")
 fresh();a=put("character-fdf-091");b=put("50","grave");e.gain_life(0,1);e.gain_life(0,1);expect(e.triggers.size()==1,"Remilia recovery once per turn even with multiple life gains")
 fresh();a=put("character-fdn-036");b=put("character-fdn-038");e.move_to(b,"hand");expect(e.triggers.size()==2,"tengu bounce triggers own and Aya abilities");settle();expect(e.players[0].field.any(func(u):return u.card_id=="token-fdn-082"),"Aya creates news token")
 fresh();a=put("token-fdf-127");act(a,a.card_id);expect(a.zone=="void" and e.players[0].life==21,"grilled lamprey sacrifices for one life")
 fresh();a=put("token-fdf-129");act(a,a.card_id,{"player":0});expect(a.zone=="void","keystone token disappears after sacrifice");e.damage_target({"player":0},3);expect(e.players[0].life==18,"keystone shields one damage to player")
 fresh();a=put("item-ucs-013");b=put("74");expect(not e.has_leader_ability(b),"ordinary self card starts without self ability");act(a,a.card_id);expect(e.has_leader_ability(b),"headpiece grants self abilities this turn")
 fresh();mana();a=put("item-fdn-044");b=put("50","grave");act(a,a.card_id,choose_groups(e.Extra.activation_options(e,a,a.card_id),[[Pack.ref(e,b)]]));expect(b.zone=="deck" and a.tapped and e.players[0].life==21,"carrot recycles chosen grave card and heals")
 fresh();mana();a=put("character-ucs-065");b=put("50","hand");pw=e.stat(a,"power");sp=e.stat(a,"spirit");act(a,"character-ucs-065:spirit",choose_groups(e.Extra.activation_options(e,a,"character-ucs-065:spirit"),[[Pack.ref(e,b)]]));expect(b.zone=="grave" and e.stat(a,"power")==sp and e.stat(a,"spirit")==pw,"Seija discards and swaps power/spirit")
 fresh();a=put("character-fdf-111","grave");b=put("164","palette");b.poverty=3;o=e.Extra.activation_options(e,a,a.card_id);t=Pack.ai_target(e,0,o,a.card_id);act(a,a.card_id,t);expect(a.zone=="field" and b.poverty==0 and e.players[1].life==17,"Tojiko removes three poverty counters and resurrects")
 fresh();a=put("spell-fdn-002");a.timer=3;b=put("50");e.players[0].life=2;e.gain_life(0,9);expect(e.players[0].life==2,"Volcano prevents life gain");e.damage_target({"player":0},10);e.judge();expect(e.players[0].life==1 and e.winner==-2,"Volcano floors life at one with a unit")
 fresh();resolve_spell("spell-fdf-013");expect(e.players[0].field.size()==3 and e.players[0].hand.size()==3,"sky keystones creates three and draws three")
 fresh();resolve_spell("spell-fdf-084");expect(e.players[0].field.size()==2 and e.players[0].palette.size()==1 and e.players[0].palette[0].tapped,"guardian keystones creates two and ramps tapped")
 fresh();resolve_spell("spell-fdf-062");a=e.units(0)[0];e.Roster.on_attack(e,a);settle();expect(a.plus_counters==2,"Imp Swarm tokens gain two counters on attack")
 fresh();c=resolve_spell("spell-fdn-040");a=e.units(0)[0];expect(c.zone=="palette" and c.tapped and e.cards[a.card_id].power==4 and e.Extra.keyword(e,a,"先制"),"possession creates halfghost then enters tapped palette")
 b=put("spell-fdn-012");b.timer=5;e.phase="end";e.run_delayed("end");settle();expect(a.zone=="field" and e.field_slots(0)==0,"halfghost song cancels end sacrifice and field slot")
 fresh();a=put("50");a.plus_counters=10;c=resolve_spell("spell-fdn-003");t=choose_groups(e.pending.options,[[e.ref_target(a)],[e.ref_target(a)],[e.ref_target(a)],[e.ref_target(a)],[e.ref_target(a)]]);e.choose_effect(t);expect(a.damage==5 and e.players[0].life==10,"Phoenix allocates five damage then sets life ten")
 fresh();a=put("50");a.plus_counters=10;resolve_spell("spell-fdf-049",e.ref_target(a));expect(a.damage==6 and e.players[0].hand.size()==2,"Future slash deals six and draws two")
 fresh();a=put("50");resolve_spell("spell-fdf-038",{"extra":3});expect(e.players[0].hand.size()==4 and e.players[0].life==8,"rainbow underworld optional extra draw pays four life each")
 fresh();a=put("character-fdf-029","grave");b=put("spell-fdf-045","grave");o=e.targets_for("spell-fdf-064",0);expect(not o.is_empty(),"Mooned Insect finds corresponding role pair");c=resolve_spell("spell-fdf-064",o[0]);expect(a.zone=="hand" and b.zone=="hand" and c.zone=="exile","Mooned Insect recovers both and exiles itself")
 fresh();a=put("7");b=put("50");pw=e.cards[a.card_id].name;resolve_spell("spell-ucs-057",{"picks":[[e.ref_target(a)],[e.ref_target(b)]]});expect(e.cards[a.card_id].name==pw and e.stat(a,"power")==e.stat(b,"power"),"first doll copies stats but preserves name")
 e.move_to(a,"hand");expect(a.card_id=="7","copied doll restores identity on zone change")
 fresh();a=put("character-fdn-038");b=put("50");sp=e.stat(b,"spirit");resolve_spell("spell-fdn-039",{"picks":[[e.ref_target(a)],[e.ref_target(b)]]});expect(a.zone=="hand" and e.stat(b,"spirit")==sp+1 and e.Extra.keyword(e,b,"不能被阻挡"),"tengu flow bounces one and buffs another")
 fresh();a=put("spell-fdf-040");a.timer=2;resolve_spell("spell-fdf-055",dict(Pack.ref(e,a),{"mode":"放置2个计时"}));expect(a.timer==4,"Clock Corpse adds two time counters")
 fresh();a=put("character-fdf-091");var pwr=e.stat(a,"power");resolve_spell("spell-fdn-008",e.ref_target(a));expect(e.stat(a,"power")==pwr+4 and e.players[1].night_lock==e.turn,"Night King buffs vampire and locks opponent for turn")
 b=put("character-fdn-021","field",1);e.move_to(b,"grave",false);expect(e.triggers.is_empty(),"Night King prevents opposing triggers after resolving")
 fresh();a=put("7","field");b=put("8","grave");c=put("character-fdn-045","grave");var spell=put("spell-fdn-046","hand");put("character-fdf-112");mana()
 o=e.targets_for(spell.card_id,0,spell.uid);t=choose_groups(o,[o[0].selection[0].pool]);expect(Pack.choice_valid(e,o,t),"Goliath experiment three distinct dolls form valid cost")
 var cast_result=e.commit_cast(0,spell.uid,t,e.payment(0,e.cast_cost(0,spell,t)).plan);expect(cast_result.is_empty(),"Goliath experiment pays additional cost "+cast_result);settle();expect(c.zone=="field","Goliath experiment searches paid doll back into battlefield")
 fresh();a=put("82");var four=4;resolve_spell("spell-fdf-063",{"picks":[[{"player":1}],[e.ref_target(a)]]});expect(e.players[1].life==16 and a.plus_counters==four,"Kuji Kiri damage and counters")
 fresh();a=put("50");a.plus_counters=10;resolve_spell("spell-fdf-031",{"picks":[[{"player":1}],[e.ref_target(a)]]});expect(e.players[1].life==16 and not a.tapped,"Flower Land damage and untap")
 fresh();resolve_spell("spell-ucs-022");o=e.pending.options;t=choose_groups(o,[[o[0].selection[0].pool.filter(func(r):return r.outside_id=="character-ucs-020")[0]],[o[0].selection[1].pool.filter(func(r):return r.outside_id=="character-ucs-021")[0]]]);e.choose_effect(t)
 expect(e.players[0].hand.size()==2 and e.players[0].hand.all(func(u):return not e.cards[u.card_id].constructible),"outside game spell adds dream units which remain nonconstructible")
 fresh();a=put("character-fdf-101");e.Extra.on_enter(e,a);e.pump_choices();o=e.pending.options;var name=e.cards["character-fdf-098"].name;e.choose_effect(o.filter(func(r):return r.card_name==name)[0]);one();b=put("character-fdf-098");expect(not e.extension_activation_error(0,b,b.card_id).is_empty(),"Momiji declared name locks matching mana ability")
 expect(saved==FileAccess.get_file_as_string(Store.SAVE_PATH),"saved decks unchanged")
 print("V013_RULES: ",checks," checks; ",failures," failures");quit(1 if failures else 0)
