extends "res://tests/test_v010_ui.gd"
func capture(name:String):
 if DisplayServer.get_name()=="headless":return
 await RenderingServer.frame_post_draw
 root.get_texture().get_image().save_png("res://work/v012/"+name+".png")
func run():
 var saved=FileAccess.get_file_as_string(Store.SAVE_PATH)
 app=load("res://main.tscn").instantiate();root.add_child(app);await process_frame
 app.load_test_decks();app.begin_battle(true);view=app.duel_view;view.set_process(false);e=view.engine
 clean(true)
 var original=e.make_card("99",1,"stack")
 var entry={"id":e.next_stack,"kind":"card","card":original,"owner":1,"target":{"player":0},"name":e.cards[original.card_id].name}
 e.next_stack+=1;e.stack.append(entry)
 for i in range(3):put("166","palette")
 var pilgrimage=put("spell-fdn-066","hand")
 expect(e.commit_cast(0,pilgrimage.uid,{"none":true},e.payment(0,e.cast_cost(0,pilgrimage)).plan).is_empty(),"pilgrimage casts without choosing a stack card")
 e.presentation_events.clear();view.render();await settle();view.render()
 expect(e.stack.back().target=={"none":true} and view.table.targetable_stacks.is_empty(),"pilgrimage cast does not expose a stack target")
 resolve();e.presentation_events.clear();view.render();await settle();view.render()
 expect(e.pending.get("kind","")=="effect_choice" and view.picker.available_refs().has({"stack_id":entry.id}) and entry.id in view.table.targetable_stacks,"pilgrimage resolution highlights the remaining spell")
 view.choose_target({"stack_id":entry.id});view.confirm_trigger()
 expect(e.pending.is_empty() and entry.get("rewritten_fairy",false) and pilgrimage.zone=="grave","pilgrimage UI choice completes the rewrite")
 clean(true);var spell=put("spell-htk-003","hand");put("character-htk-001","field");put("164","field");put("167","field");put("167","palette");put("168","palette");put("164","palette")
 var grave=put("50","grave");view.render();await settle();view.request_cast(spell.uid)
 expect(view.picker.available().any(func(a):return a.kind=="mode" and a.value=="移回手牌"),"emotion first mode available before choosing target")
 view.inline_pick(view.picker.available().filter(func(a):return a.kind=="mode" and a.value=="移回手牌")[0]);await settle()
 expect(view.picker.available().any(func(a):return a.kind=="target" and a.value.get("uid",-1)==grave.uid),"emotion recovery exposes the grave target")
 var atom=view.picker.available().filter(func(a):return a.kind=="target" and a.value.get("uid",-1)==grave.uid)[0];view.inline_pick(atom);await settle();await finish_group()
 await press("造成1点伤害");view.choose_target({"player":1});await finish_group();await settle();await capture("emotions-confirm")
 expect(view.picker.ready(),"emotion second mode is independently chosen")
 await press("发动")
 expect(spell.zone=="stack","mode spell enters stack after confirmation")
 resolve();view.render();await settle();expect(grave.zone=="hand" and e.players[1].life==19,"UI resolves recovery and player damage")
 clean(true);var unit=put("character-lof-001","field");unit.leader_counters=1;unit.courage=3;view.render();await settle();view.inspect_card(unit.card_id,unit.uid)
 expect(view.inspection_text.get_parsed_text().contains("勇气等级：3"),"counter amount visible in inspection")
 expect(e.available_actions(0,unit.uid).filter(func(a):return a.type=="extension").size()==2,"Cirno exposes two separate abilities")
 await capture("courage-preview")
 clean(true);unit=put("87","field");e.Extra.on_enter(e,unit);e.pump_choices();resolve();view.render();await settle()
 var tokens=e.units(0).filter(func(u):return u.card_id=="token_halfghost")
 expect(tokens.size()==1,"Youmu creates actual runtime halfghost")
 if not tokens.is_empty():
  view.inspect_card("token_halfghost",tokens[0].uid);await settle()
  expect(app.texture("token_halfghost")==app.texture("token-ucs-099"),"runtime halfghost uses replaced canonical artwork")
  await capture("halfghost-replaced")
 clean(true);unit=put("character-htk-001","field");unit.leader_counters=1;e.Roster.on_phase(e,"prepare");e.pump_choices();view.render();await settle()
 view.choose_target({"player":1});await press("确定");resolve();view.render();await settle()
 expect(e.pending.get("owner",-1)==0 and view.picker.available().any(func(a):return a.value=="怒"),"Kokoro leader allows player mood choice")
 await press("怒");await press("确定");view.render();await settle()
 expect(e.players[0].field.any(func(c):return c.card_id=="token-htk-032"),"mood UI creates supplied mask token")
 await capture("mask-created")
 expect(FileAccess.get_file_as_string(Store.SAVE_PATH)==saved,"UI keeps saved decks unchanged")
 print("V012_UI: %d checks; %d failures" % [checks,failures.size()]);quit(0 if failures.is_empty() else 1)
