extends "res://tests/test_v092.gd"
func capture(name: String):
 if DisplayServer.get_name()=="headless": return
 view.update_badge_positions()
 view.banner.visible=false
 await RenderingServer.frame_post_draw
 root.get_texture().get_image().save_png("res://work/v094-"+name+".png")
func tagged(node: Node,key: String) -> Array:
 var found=[]
 if node.has_meta(key): found.append(node)
 for child in node.get_children(): found.append_array(tagged(child,key))
 return found
func run():
 var saved=FileAccess.get_file_as_string(Store.SAVE_PATH)
 app=load("res://main.tscn").instantiate(); root.add_child(app); await process_frame
 app.load_legacy_test_decks(); app.begin_battle(true); view=app.duel_view; view.set_process(false); e=view.engine
 clean()
 var sunny=e.make_card("1",0,"hand"); e.enter_field(sunny,0)
 var friend=put("53","field"); var enemy=put("54","field",1)
 e.pump_choices(); e.presentation_events.clear(); view.reveal_player.reset(); view.render(); await settle()
 expect(e.pending.get("kind")=="effect_choice" and e.stack.size()==1,"mandatory Sunny trigger is already on stack before target selection")
 var id=e.stack[0].id; var next=e.next_stack; var revision=e.revision
 expect(e.stack[0].get("awaiting_target",false) and e.stack[0].target.is_empty(),"provisional stack entry records incomplete target declaration")
 expect(not view.modal and find_button(view.ui,"不使用")==null,"mandatory target selection is inline and cannot be declined")
 expect([sunny.uid,friend.uid,enemy.uid].all(func(uid): return uid in view.highlights()),"Sunny can target self, friendly or opposing unit")
 expect(view.table.visuals["card_"+str(sunny.uid)].get_node("SummoningMist").visible,"summoning sickness has a textless mist on the field")
 expect(view.stack_panel.tiles.has(id) and not view.stack_panel.tiles[id].tile.has_node("SummoningMist"),"ability card in stack rail has no summoning mist")
 expect(view.stack_panel.tiles[id].caption.text=="进场：目标单位本回合获得疾行。","stack caption names only the active Sunny ability")
 expect(not view.stack_panel.tiles[id].tile.get_meta("selected"),"mandatory stack entry does not inherit selected gold outline")
 e.pass_priority(e.priority); e.pass_priority(e.priority)
 expect(e.stack.size()==1 and e.revision==revision,"unconfirmed mandatory target blocks both priority passes")
 expect(not e.extension_activation_error(0,put("71","field")).is_empty(),"activated abilities cannot precede pending triggers")
 e.choose_effect({}); e.choose_effect({"uid":999,"epoch":0})
 expect(e.pending.get("stack_id")==id and e.stack.size()==1,"mandatory trigger rejects decline and invalid target")
 await click(point(enemy.uid)); await click(Vector2(1030,560),MOUSE_BUTTON_RIGHT)
 expect(e.pending.get("stack_id")==id and not view.picker.ready(),"right click clears target selection but keeps mandatory stack entry")
 await capture("mandatory-before-target")
 await click(point(sunny.uid)); await press("确定"); await settle()
 expect(e.pending.is_empty() and e.stack.size()==1 and e.stack[0].id==id and e.next_stack==next,"target confirmation finalizes existing stack entry exactly once")
 expect(not e.stack[0].has("awaiting_target") and e.stack[0].target.uid==sunny.uid,"selected self target is committed")
 expect(view.stack_target_arrows().size()==1,"finalized mandatory ability gains its target arrow")
 resolve(); view.render(); await settle()
 expect(e.has_haste(sunny) and not view.stack_panel.tiles.has(id),"mandatory ability resolves normally and its caption disappears")
 e.players[0].turns+=1; view.render()
 expect(not view.table.visuals["card_"+str(sunny.uid)].get_node("SummoningMist").visible,"mist ends when summoning sickness ends")
 clean(); sunny=e.make_card("1",0,"hand"); e.enter_field(sunny,0); e.pump_choices(); e.presentation_events.clear(); view.reveal_player.reset(); view.render()
 expect(view.table.visuals["card_"+str(sunny.uid)].get_node("SummoningMist").visible,"newly entered unit creates a sickness period")
 clean()
 var yuyuko=put("71","field"); yuyuko.leader=true
 var victim=put("53","field"); e.move_to(victim,"grave"); e.pump_choices(); view.render(); await settle()
 var prompt=tagged(view.ui,"optional_trigger_prompt")
 expect(prompt.size()==1 and prompt[0].text=="是否发动华胥的亡灵「西行寺幽幽子」的触发效果","optional trigger has the requested explicit question")
 expect(prompt.size()==1 and prompt[0].global_position.x>=1300 and prompt[0].global_position.y<find_button(view.ui,"确定").global_position.y,"optional question sits above bottom-right confirmation")
 expect(prompt[0].get_global_rect().end.x<=1580 and prompt[0].get_line_count()>=2,"long card name wraps inside right-side question instead of overflowing")
 expect(e.stack.size()==1 and e.pending.get("kind")=="effect_choice","optional trigger waits for confirmation on stack")
 await capture("optional-question")
 await press("不使用")
 expect(e.stack.is_empty() and e.usage_count(yuyuko.uid,"death_ping")==0,"declining optional trigger leaves stack and usage unchanged")
 victim=put("53","field"); e.move_to(victim,"grave"); e.pump_choices(); view.render(); await settle()
 view.choose_target({"player":1}); await press("确定"); await settle()
 var caption=view.stack_panel.tiles[e.stack.back().id].caption.text
 expect(caption=="自机能力：对目标造成1点伤害。" and "牺牲" not in caption,"Yuyuko stack caption distinguishes death trigger from sacrifice ability")
 resolve(); expect(e.players[1].life==19 and e.usage_count(yuyuko.uid,"death_ping")==1,"optional death trigger still deals one damage and counts one use")
 # APNAP ordering with an optional and mandatory trigger controlled by the same player.
 clean()
 var red=put("14","field"); var draw_card=put("5","grave"); var opposing=put("14","field",1)
 e.Extra.event(e,opposing,"enter_drain",false)
 e.Extra.event(e,red,"enter_drain",false)
 e.Extra.event(e,draw_card,"death_draw_life",true)
 e.pump_choices(); view.render(); await settle()
 expect(e.pending.get("kind")=="trigger_order" and e.pending.owner==0,"active player orders triggers first even when queued second")
 var cards=tagged(view.ui,"trigger_index")
 expect(cards.size()==2 and view.modal_root.get_child(0).get_global_rect().get_center().distance_to(Vector2(800,450))<1,"simultaneous triggers use separate card faces in centered panel")
 var saved_pending=e.pending.duplicate(true)
 await press("观察战场")
 expect(view.observing and not view.modal_root.visible and e.pending==saved_pending,"trigger ordering can pause to observe without changing choices")
 await press("返回选择")
 await capture("trigger-order")
 await click(cards[1].get_global_rect().get_center())
 expect(e.pending.get("kind")=="effect_choice" and e.pending.trigger.effect=="death_draw_life","clicked trigger card is processed before the other same-controller trigger")
 await press("不使用")
 expect(e.pending.is_empty() and e.stack.size()==2 and e.stack[0].owner==0 and e.stack[1].owner==1,"remaining mandatory triggers enter in active/nonactive controller order")
 await settle(); await capture("multiple-stack-captions")
 expect(e.stack.all(func(s): return view.stack_panel.tiles.has(s.id)),"each stacked ability has its own caption")
 view.update_badge_positions()
 var first_caption=view.stack_panel.tiles[e.stack[0].id].caption.get_global_rect()
 var second_caption=view.stack_panel.tiles[e.stack[1].id].caption.get_global_rect()
 expect(not first_caption.intersects(second_caption),"multiple ability captions do not overlap below the stack")
 resolve(); resolve(); expect(e.players[0].life==19 and e.players[1].life==19,"ordered mandatory triggers resolve last-in-first-out without duplication")
 clean()
 var brave1=put("54","field"); var brave2=put("70","field")
 brave1.attacked=true; brave2.attacked=true; brave1.tapped=true; brave2.tapped=true
 brave1.brave_attack_turn=e.turn; brave2.brave_attack_turn=e.turn
 e.advance_phase()
 expect(e.phase=="end" and e.pending.is_empty() and e.stack.is_empty() and not brave1.tapped and not brave2.tapped,"brave untaps directly at end phase")
 clean()
 var attacker=put("53","field"); view.render(); await settle(); view.object_clicked(attacker.uid)
 expect(find_button(view.ui,"攻击").global_position.x>=1300,"attack confirmation is on the right")
 expect(find_button(view.ui,"全响应")!=null and find_button(view.ui,"不响应")!=null,"response controls remain available")
 view.clear_attack_preview(); view.settings_menu()
 expect(view.modal_root.get_child(0).get_global_rect().get_center().distance_to(Vector2(800,450))<1,"settings actions stay inside centered dialog")
 await capture("right-settings")
 view.close_overlay(); view.render(); await settle()
 # Sickness is shown for both players, with selection still using yellow borders.
 var sick_enemy=e.make_card("53",1,"hand"); e.enter_field(sick_enemy,1); view.render(); await settle()
 expect(view.table.visuals["card_"+str(sick_enemy.uid)].get_node("SummoningMist").visible,"opponent's newly entered units also show the mist")
 await capture("sickness-mist")
 expect(FileAccess.get_file_as_string(Store.SAVE_PATH)==saved,"player deck file unchanged")
 print("V094_TEST: ",checks," checks; ",failures," failures"); quit(0 if failures.is_empty() else 1)
