extends "res://tests/test_v09_rules.gd"
const Caption=preload("res://scripts/rules/ability_caption.gd")
func run():
 var saved=FileAccess.get_file_as_string(Store.SAVE_PATH)
 fresh()
 for id in ["91","133","rec_unit_097","soi_unit_086"]:
  expect(e.cards.has(id) and DB.IDS.has(id),"new database card registered: "+id)
  expect(FileAccess.file_exists(e.cards[id].image),"new card art exists: "+id)
 # End-step recovery works on an ordinary Orin, but only own non-leader units.
 var orin=put("91"); var dead=put("15","grave"); put("71","grave"); put("53","grave",1); put("96","grave")
 e.advance_phase(); e.pump_choices()
 expect(e.phase=="end" and e.pending.get("kind")=="effect_choice" and e.pending.trigger.optional,"Orin end step offers optional recovery")
 expect(e.pending.options.size()==1 and e.pending.options[0].uid==dead.uid,"Orin recovery excludes enemy cards, spells and printed leaders")
 e.choose_effect(e.pending.options[0]); one()
 expect(dead.zone=="hand" and e.pending.is_empty(),"ordinary Orin recovers to hand without leader replacement")
 # The replacement is a choice during resolution, not another stack object.
 fresh(); orin=put("91"); orin.leader=true; dead=put("15","grave")
 e.move_to(dead,"hand"); e.pump_choices()
 expect(dead.zone=="grave" and e.pending.get("kind")=="grave_replacement" and e.stack.is_empty(),"leader Orin pauses grave return for replacement choice")
 e.choose_grave_replacement(true)
 expect(dead.zone=="field" and e.stack.is_empty(),"replacement places unit directly on battlefield")
 fresh(); orin=put("91"); orin.leader=true; dead=put("15","grave")
 e.move_to(dead,"hand"); e.pump_choices(); e.choose_grave_replacement(false)
 expect(dead.zone=="hand" and e.pending.is_empty(),"declining replacement keeps original return-to-hand action")
 fresh(); orin=put("91"); dead=put("15","grave"); put("170")
 e.move_to(dead,"hand"); e.pump_choices()
 expect(e.pending.get("kind")=="grave_replacement","shrine enables ordinary Orin replacement")
 e.choose_grave_replacement(true); expect(dead.zone=="field","shrine replacement completes")
 fresh(); orin=put("91"); orin.leader_counters=1; dead=put("15","grave")
 e.move_to(dead,"hand"); e.pump_choices()
 expect(e.pending.get("kind")=="grave_replacement","leader counter enables Orin replacement")
 fresh(); orin=put("91"); orin.leader=true; dead=put("rec_unit_097","grave")
 e.move_to(dead,"hand"); e.pump_choices()
 expect(dead.zone=="hand" and e.pending.is_empty(),"power threshold rejects a larger returned unit")
 fresh(); orin=put("91"); orin.leader=true
 for i in range(5): put("53")
 dead=put("15","grave"); e.move_to(dead,"hand"); e.pump_choices()
 expect(dead.zone=="hand" and e.pending.is_empty(),"full battlefield keeps legal return to hand")
 fresh(); orin=put("91"); orin.leader=true; dead=put("15","grave")
 e.move_to(dead,"hand"); e.pump_choices(); e.move_to(dead,"exile"); e.choose_grave_replacement(true)
 expect(dead.zone=="exile","replacement rechecks physical card epoch and zone")
 fresh(); orin=put("91"); orin.leader=true; dead=put("1","grave")
 # Sunny has 2 power, so increase Orin to make this return eligible.
 orin.plus_counters=2; e.move_to(dead,"hand"); e.pump_choices(); e.choose_grave_replacement(true)
 expect(dead.zone=="field" and e.pending.get("kind")=="effect_choice" and e.stack.size()==1,"reanimation runs normal mandatory enter trigger")
 # Nue's ordinary copy has keywords, but no leader enter choice.
 fresh(); var nue=enter("soi_unit_086")
 expect(e.pending.is_empty() and e.stack.is_empty() and e.has_haste(nue),"ordinary Nue has haste without leader enter ability")
 for mode in ["造成2点伤害","横置","抓一张牌"]:
  fresh(); var other=put("91","field",1); var own=put("91")
  nue=e.make_card("soi_unit_086",0,"hand",true); e.enter_field(nue,0); e.pump_choices()
  expect(e.pending.get("kind")=="effect_choice" and e.pending.trigger.optional,"Nue leader enter choice: "+mode)
  var options=e.pending.options
  expect(options.any(func(t): return t.get("uid")==nue.uid) and options.any(func(t): return t.get("uid")==other.uid),"Nue can target either side including itself: "+mode)
  var chosen=options.filter(func(t): return t.mode==mode and (t.get("none",false) or t.get("uid")==other.uid))[0]
  e.choose_effect(chosen)
  expect(Caption.text(e.stack.back())=="自机能力："+mode+"。","stack caption identifies selected Nue mode: "+mode)
  one()
  expect(other.damage==2 if mode=="造成2点伤害" else other.tapped if mode=="横置" else e.players[0].hand.size()==1,"Nue mode resolves: "+mode)
 fresh(); put("170"); nue=enter("soi_unit_086")
 expect(e.pending.get("kind")=="effect_choice","shrine enables ordinary Nue enter ability")
 e.choose_effect({}); expect(e.stack.is_empty(),"optional Nue trigger can be declined")
 # Menace/威吓 is enforced both by blocker presentation and commit validation.
 fresh(); nue=put("soi_unit_086"); var blocker=put("91","field",1)
 e.attack(0,nue.uid); expect(e.legal_blockers().is_empty(),"one available unit cannot block menace")
 one(); expect(e.pending.is_empty() and not e.combat.blocked,"menace skips impossible single-block prompt")
 one(); expect(e.players[1].life==18,"unblocked menace deals spirit damage")
 fresh(); nue=put("soi_unit_086"); blocker=put("91","field",1); var second=put("91","field",1)
 e.attack(0,nue.uid); one(); e.block([blocker.uid])
 expect(e.pending.get("kind")=="block" and not blocker.tapped,"menace rejects exactly one selected blocker")
 e.block([blocker.uid,second.uid])
 expect(e.combat.blockers.size()==2 and blocker.tapped and second.tapped,"two blockers can block menace")
 fresh(); nue=put("soi_unit_086"); put("91","field",1); put("91","field",1)
 e.attack(0,nue.uid); one(); e.ai_step(1)
 expect(e.combat.blockers.size()==2 and e.pending.is_empty(),"AI chooses two blockers for menace")
 # Spell-selected battle does not tap or require an attack-ready unit.
 fresh(); mana(); var fighter=put("91"); fighter.entered_turns=e.players[0].turns; var enemy=put("91","field",1)
 var options=e.targets_for("133",0)
 expect(options.size()==1 and options[0].parts[0].uid==fighter.uid and options[0].parts[1].uid==enemy.uid,"new spell selects one own and one opposing unit")
 var spell=put("133","hand"); var error=e.commit_cast(0,spell.uid,options[0],e.payment(0,e.cast_cost(0,spell)).plan)
 expect(error.is_empty(),"new battle spell can be cast")
 one(); expect(e.combat.get("forced",false) and e.combat.step=="block_window" and not fighter.tapped,"spell creates battle response window without attack declaration")
 one(); expect(fighter.damage==1 and enemy.damage==1,"spell battle deals reciprocal combat damage")
 fresh(); var ally=put("91"); enemy=put("91","field",1); options=e.targets_for("133",0)
 e.move_to(enemy,"exile"); e.Extra.spell_resolve(e,{"card":put("133","hand"),"owner":0,"target":options[0]}); e.pump_choices()
 expect(e.combat.is_empty() and e.combat_queue.is_empty(),"spell does not start battle with invalid target")
 fresh(); var mokou=put("rec_unit_097","grave"); var red=put("165","palette")
 error=e.commit_extension(0,mokou.uid,{"none":true},e.payment(0,{"红":1}).plan); one()
 expect(error.is_empty() and red.tapped and mokou.zone=="hand","new Mokou pays one red and returns itself")
 expect(FileAccess.get_file_as_string(Store.SAVE_PATH)==saved,"real saved decks unchanged")
 var report="%d checks; %d failures\n%s" % [checks,failures.size(),"\n".join(failures)]
 FileAccess.open("res://work/v095-rules-tests.txt",FileAccess.WRITE).store_string(report)
 print("V095_RULES: "+report); quit(0 if failures.is_empty() else 1)
