extends "res://tests/test_v092.gd"
func run():
 var saved=FileAccess.get_file_as_string(Store.SAVE_PATH)
 app=load("res://main.tscn").instantiate(); root.add_child(app); await process_frame
 app.load_test_decks(); app.begin_battle(true); view=app.duel_view; view.set_process(false); e=view.engine
 # A unique-payment unit is still private until the explicit confirmation.
 clean(); view.auto_pay=true
 var unit=put("53","hand"); var yellow=put("164","palette")
 view.render(); await settle(); var before=snapshot()
 await drag(view.hand_nodes[unit.uid].get_global_rect().get_center(),Vector2(900,490))
 expect(not view.modal and view.local.get("mode")=="target" and find_button(view.ui,"确定")!=null,"drag opens bottom-right confirmation without a modal")
 expect(snapshot()==before and unit.zone=="hand" and not yellow.tapped,"unique auto-payment waits for explicit confirmation")
 await click(Vector2(1050,550),MOUSE_BUTTON_RIGHT)
 expect(view.local.is_empty() and snapshot()==before,"right click outside cancels before automatic payment")
 view.request_cast(unit.uid); await press("确定")
 expect(unit.zone=="stack" and yellow.tapped,"confirmed unique payment commits the unit once")
 expect(view.stack_target_arrows().is_empty(),"untargeted unit creates no target arrow")
 # Battlefield targets and player objects are highlighted, selected privately, reselectable.
 clean(); view.auto_pay=true
 var spell=put("96","hand"); var friendly=put("53","field"); var enemy=put("54","field",1)
 put("165","palette"); put("164","palette")
 e.players[0].life=27; e.players[1].life=8; view.render(); await settle()
 expect(view.life_widgets[0].bar.value==20 and "27" in view.life_widgets[0].button.text,"life above 20 shows the true number with a full bar")
 expect(view.life_widgets[1].button.get_global_rect().encloses(view.life_widgets[1].bar.get_global_rect()),"health bar remains inside its player object")
 expect(view.life_widgets[1].bar.value==8 and view.life_widgets[1].bar.max_value==20,"life below 20 uses proportional fill")
 before=snapshot(); view.request_cast(spell.uid)
 expect(not view.modal and [friendly.uid,enemy.uid].all(func(uid): return uid in view.highlights()),"targeted card uses battlefield blue outlines instead of a popup")
 expect(view.life_widgets[0].legal and view.life_widgets[1].legal,"both players are highlighted when legal targets")
 await click(point(enemy.uid))
 expect(view.picker.ready() and enemy.uid in view.selected_uids() and snapshot()==before,"selecting target turns it gold without payment or a public action")
 await click(view.life_widgets[0].button.get_global_rect().get_center())
 expect(view.life_widgets[0].selected and view.picker.option()=={"player":0},"player can replace the preselected unit as target")
 await click(point(enemy.uid)); await capture("inline-target")
 await click(Vector2(1000,570),MOUSE_BUTTON_RIGHT)
 expect(view.local.is_empty() and snapshot()==before,"right click cancels the entire targeted card declaration")
 view.request_cast(spell.uid); await click(point(enemy.uid)); await press("确定")
 if view.local.get("mode")=="payment_offer": await press("自动支付")
 await settle()
 expect(spell.zone=="stack" and e.stack.back().target.uid==enemy.uid,"confirmation preserves the declared battlefield target")
 expect(view.stack_target_arrows().size()==1 and view.stack_target_arrows()[0].target.uid==enemy.uid,"stack arrow points to the selected unit")
 expect(not view.table.descriptors["card_"+str(spell.uid)].gold,"committed source has no yellow border")
 await capture("stack-arrow-unit")
 resolve(); view.render(); await settle()
 expect(view.stack_target_arrows().is_empty(),"resolved stack entry removes its arrow")
 # Manual payment is entirely refundable, including multicolor source selection.
 clean(); view.auto_pay=false
 spell=put("96","hand"); var red=put("165","palette"); put("165","palette"); put("164","palette")
 view.render(); await settle(); before=snapshot(); view.request_cast(spell.uid)
 await click(view.life_widgets[1].button.get_global_rect().get_center()); await press("确定")
 expect(view.local.mode=="payment" and not view.modal,"manual payment follows confirmed target inline")
 view.reserve_resource(red.uid)
 expect(not view.local.plan.is_empty() and not red.tapped and snapshot()==before,"manual payment reserves resources privately")
 await click(Vector2(600,570),MOUSE_BUTTON_RIGHT)
 expect(view.local.is_empty() and not red.tapped and snapshot()==before,"right click during payment refunds every reservation")
 # Multiple auto-payment choices stay inline and remain cancellable.
 view.auto_pay=true; view.request_cast(spell.uid); view.choose_target({"player":1}); await press("确定")
 expect(view.local.get("mode")=="payment_offer" and not view.modal,"ambiguous payment asks inline instead of opening a modal")
 await click(Vector2(950,560),MOUSE_BUTTON_RIGHT)
 expect(snapshot()==before and view.local.is_empty(),"cancelling auto-payment offer is also private")
 # Player-directed arrow and response stack selection.
 view.request_cast(spell.uid); view.choose_target({"player":1}); await press("确定"); await press("自动支付"); await settle()
 expect(view.stack_target_arrows().size()==1 and view.stack_target_arrows()[0].target=={"player":1},"damage spell arrow points at opponent's life object")
 await capture("stack-arrow-player")
 clean(); view.auto_pay=true
 var hostile=put("96","hand",1); put("165","palette",1); put("164","palette",1)
 var counter=put("100","hand"); put("70","field"); put("164","palette"); put("164","palette")
 e.priority=1; var error=e.commit_cast(1,hostile.uid,{"player":0},e.payment(1,e.cards["96"].cost).plan)
 view.render(); await settle(); view.request_cast(counter.uid)
 expect(error.is_empty() and view.table.descriptors["card_"+str(hostile.uid)].blue,"legal stack counter-target is blue")
 await click(point(hostile.uid))
 expect(view.picker.ready() and view.table.descriptors["card_"+str(hostile.uid)].gold,"selected stack counter-target is gold")
 await press("确定"); await settle()
 expect(counter.zone=="stack" and view.stack_target_arrows().size()==2,"counter adds an arrow to its stack target alongside the original arrow")
 await capture("stack-arrow-counter")
 resolve(); view.render(); await settle()
 expect(hostile.zone=="grave" and view.stack_target_arrows().is_empty(),"countered and resolved entries leave no dangling arrows")
 # Yuyuko: one death -> one optional choice -> one point, at most twice per turn.
 clean(); view.auto_pay=true
 var leader=e.players[0].leader; leader.card_id="71"; e.enter_field(leader,0)
 var victim=put("53","field"); view.render(); await settle()
 var action=e.extra_action(leader); before=snapshot(); view.execute_action(action)
 expect(not view.modal and victim.uid in view.highlights(),"Yuyuko sacrifice ability targets directly on battlefield")
 await click(point(victim.uid))
 expect(victim.zone=="field" and snapshot()==before,"sacrifice is not paid before confirmation")
 await press("确定")
 expect(victim.zone=="grave" and e.pending.get("kind")=="effect_choice","confirmed sacrifice offers the separate death trigger")
 expect(e.pending.trigger.data.amount==1 and e.pending.trigger.data.limit==2,"database binds one damage and two uses per turn")
 before=snapshot(); await click(view.life_widgets[1].button.get_global_rect().get_center())
 expect(snapshot()==before and not view.modal,"death trigger target selection does not fire immediately")
 await press("确定")
 expect(e.stack.back().effect=="leader_death_damage" and e.usage_count(leader.uid,"death_ping")==1,"first use enters stack and counts exactly once")
 await settle(); await capture("yuyuko-target-arrow")
 resolve(); view.render(); await settle()
 expect(e.players[1].life==19,"first Yuyuko trigger deals exactly one damage")
 resolve(); view.render(); await settle()
 victim=put("53","field"); var death_snapshot=victim.duplicate(true)
 e.move_to(victim,"grave"); e.Extra.on_death(e,victim,death_snapshot); e.pump_choices(); view.render()
 expect(e.triggers.is_empty() and e.pending.trigger.effect=="leader_death_damage","same death cannot enqueue duplicate Yuyuko triggers")
 expect(not view.picker.ready(),"second death starts with no target inherited from the first")
 await click(view.life_widgets[0].button.get_global_rect().get_center()); await press("确定"); resolve(); view.render(); await settle()
 expect(e.players[0].life==19 and e.players[1].life==19 and e.usage_count(leader.uid,"death_ping")==2,"second activation chooses a separate target and deals one damage")
 victim=put("53","field"); e.move_to(victim,"grave"); e.pump_choices(); view.render()
 expect(e.pending.is_empty() and e.stack.is_empty(),"third death cannot activate a third time in the same turn")
 e.start_turn(1); e.phase="main"; victim=put("53","field"); e.move_to(victim,"grave"); e.pump_choices(); view.render()
 expect(e.pending.get("kind")=="effect_choice" and e.usage_count(leader.uid,"death_ping")==0,"use limit resets on the next turn")
 await press("不使用")
 expect(e.pending.is_empty() and e.usage_count(leader.uid,"death_ping")==0,"declining optional trigger does not consume a use")
 # Two-color manual payment stays inline and cancellation leaves both sources untouched.
 clean(); view.auto_pay=false
 spell=put("96","hand"); var dual=put("170","palette"); put("170","palette")
 view.render(); await settle(); before=snapshot(); view.request_cast(spell.uid); view.choose_target({"player":1}); await press("确定")
 view.reserve_resource(dual.uid)
 expect(view.local.mode=="payment_color" and not view.modal,"multicolor payment uses inline color buttons")
 await press("红")
 expect(view.local.plan==[{"uid":dual.uid,"color":"红"}] and snapshot()==before,"inline color choice only reserves the selected color")
 await click(Vector2(930,550),MOUSE_BUTTON_RIGHT)
 expect(snapshot()==before and view.local.is_empty(),"cancelling multicolor payment restores the original private state")
 # A compound grave/field trigger walks through its legal target stages without a popup.
 clean(); view.auto_pay=true
 var dead=put("53","grave"); enemy=put("54","field",1)
 var aya=e.make_card("18",0,"hand"); e.enter_field(aya,0); e.pump_choices(); view.render(); await settle()
 var atom=view.picker.available()[0]
 await press(view.target_caption(atom.value))
 expect(not view.modal and view.life_widgets[1].legal and enemy.uid in view.highlights(),"after grave selection, the next compound target is highlighted on the battlefield")
 await click(view.life_widgets[1].button.get_global_rect().get_center()); await press("确定"); await settle()
 expect(e.stack.back().target.parts.size()==2 and view.stack_target_arrows().size()==2,"compound trigger has arrows to both actual targets")
 resolve(); view.render(); await settle()
 expect(dead.zone=="hand" and e.players[1].life==19,"compound grave-return trigger resolves with the selected player target")
 # Targeting a hand card is a click, not a second cast/drag.
 clean(); view.auto_pay=true
 var yoshika=put("61","grave"); var discard=put("53","hand"); put("61","palette"); put("61","palette")
 view.render(); await settle(); view.execute_action(e.extra_action(yoshika))
 expect(discard.uid in view.highlights() and not view.modal,"hand card is highlighted for additional discard cost")
 await click(view.hand_nodes[discard.uid].get_global_rect().get_center())
 expect(view.picker.ready() and discard.uid in view.selected_uids() and discard.zone=="hand","hand target can be selected without discarding yet")
 await press("确定")
 if view.local.get("mode")=="payment_offer": await press("自动支付")
 resolve(); view.render(); await settle()
 expect(yoshika.zone=="field" and yoshika.tapped and discard.zone=="grave","confirmed hand-cost ability discards then reanimates normally")
 # Multi-part, mode and extra-cost choices stay expressible without modal targets.
 var Picker=load("res://scripts/target_picker.gd")
 var choices=Picker.new(); choices.configure([{"parts":[{"mode":"伤害","uid":1,"epoch":0},{"mode":"横置","uid":2,"epoch":0}]},{"parts":[{"mode":"抓牌","none":true},{"mode":"横置","uid":2,"epoch":0}]}],"compound")
 choices.select({"kind":"mode","value":"伤害"}); choices.select_target({"uid":1,"epoch":0}); choices.select_target({"uid":2,"epoch":0})
 expect(choices.ready() and choices.option().parts.size()==2 and choices.selected_refs().size()==2,"compound mode choices retain both independently selected targets")
 choices.configure([{"uid":2,"epoch":0,"sacrifice":{"uid":1,"epoch":0},"sacrifice_value":3}],"cost")
 choices.select_target({"uid":1,"epoch":0}); expect(not choices.ready(),"additional sacrifice selection still requires the spell target")
 choices.select_target({"uid":2,"epoch":0}); expect(choices.ready() and choices.option().sacrifice_value==3,"additional costs preserve the complete legal engine option")
 choices.configure([{"uid":1,"epoch":0},{"uid":2,"epoch":0},{"parts":[{"uid":1,"epoch":0},{"uid":2,"epoch":0}]}],"unordered",true)
 choices.select_target({"uid":2,"epoch":0}); choices.select_target({"uid":1,"epoch":0})
 expect(choices.ready() and choices.option().get("parts",[]).size()==2 and choices.option().parts[0].uid==1,"unordered two-target choice accepts either click order and submits canonical legal option")
 expect(FileAccess.get_file_as_string(Store.SAVE_PATH)==saved,"real saved decks remain unchanged")
 var report=FileAccess.open("res://work/v093-tests.txt",FileAccess.WRITE); report.store_string("%d checks; %d failures\n%s" % [checks,failures.size(),"\n".join(failures)])
 print("V093_TEST: %d checks; %d failures" % [checks,failures.size()]); quit(0 if failures.is_empty() else 1)
func capture(name: String):
 if DisplayServer.get_name()=="headless": return
 await RenderingServer.frame_post_draw
 root.get_texture().get_image().save_png("res://work/v093-"+name+".png")

