extends "res://tests/test_v012_ui.gd"
func capture(name:String):
 if DisplayServer.get_name()=="headless":return
 await RenderingServer.frame_post_draw
 root.get_texture().get_image().save_png("res://work/v013/"+name+".png")
func run():
 var saved=FileAccess.get_file_as_string(Store.SAVE_PATH)
 app=load("res://main.tscn").instantiate();root.add_child(app);await process_frame
 app.load_test_decks();app.begin_battle(true);view=app.duel_view;view.set_process(false);e=view.engine
 clean(true);var actor=put("character-fdf-101","field");e.Extra.on_enter(e,actor);e.pump_choices();view.render();await settle()
 var fields=view.hud.find_children("*","LineEdit",true,false)
 expect(fields.size()==1,"name declaration has search input")
 if not fields.is_empty():fields[0].text="因幡帝";fields[0].text_changed.emit(fields[0].text)
 await capture("declare-name")
 var name=e.cards["character-fdf-098"].name;await press(name);await press("确定")
 expect(e.pending.is_empty() and actor.locked_name==name,"declared name confirmed through UI")
 clean(true);actor=put("character-ucs-068","field");var top=put("50","hand");e.Roster.to_top(e,top);view.debug_mode=false;view.browse_zone(0,"deck");await settle()
 var visible=view.browser_cards.get_children().filter(func(row):return row.get_meta("display_id","")!="back")
 expect(visible.size()==1 and visible[0].get_meta("display_id")==top.card_id,"normal library browser reveals only permitted top card");await capture("library-top");view.close_debug()
 clean(true);actor=put("character-fdf-098","field");e.Cat.add_mana(e,0,["黄","绿"]);var card=put("item-fdn-044","hand");view.auto_pay=false;view.request_cast(card.uid);await settle();await press("确定")
 expect(view.local.get("mode")=="payment","manual payment opens with generated mana")
 await capture("floating-mana")
 for r in e.payment(0,view.local_cost()).plan:view.reserve_resource(r.uid)
 await press("确认支付");expect(card.zone=="stack","generated mana paid through manual UI")
 clean(true);actor=put("50","field");put("spell-ucs-031","field",1);put("164","palette");view.auto_pay=false;view.begin_attack_payment(actor.uid);await settle()
 expect(view.local.get("mode")=="payment" and e.combat.is_empty(),"attack tax is privately selectable before attack")
 view.cancel_cast();expect(not actor.tapped and e.combat.is_empty(),"attack payment cancellation leaves attack undeclared")
 clean(true);card=put("spell-ucs-022","hand");e.Cat.spell_resolve(e,{"card":card,"kind":"card","owner":0,"target":{"none":true}});view.render();await settle()
 var choices=view.picker.available();expect(choices.any(func(a):return a.kind=="mode"),"outside game selector lists dream character names")
 var option=choices.filter(func(a):return a.kind=="mode")[0];view.inline_pick(option);await settle()
 expect(view.picker.available().any(func(a):return a.kind=="target" and a.value.has("outside_id")),"outside game card target is selectable")
 var button_name=e.cards[view.picker.available().filter(func(a):return a.kind=="target")[0].value.outside_id].name
 await press(button_name);await finish_group();await settle();await finish_group();await press("确定")
 expect(e.pending.is_empty() and e.players[0].hand.size()>=1,"outside game choice can complete through UI")
 clean(true);card=put("spell-fdf-028","grave");var red=put("165","palette");var black=put("168","palette")
 e.Cat.Units.resolve(e,{"source":card.duplicate(true),"effect":"cat:nuclear_return","owner":0,"target":{"none":true},"data":{},"name":e.cards[card.card_id].name})
 view.auto_pay=false;view.render();await settle();await press("支付费用");await press("确定")
 expect(view.local.get("action")=="choice_payment" and card.zone=="grave" and not red.tapped,"trigger payment opens private manual selection")
 view.cancel_cast();expect(card.zone=="grave" and not red.tapped and not e.pending.is_empty(),"canceling trigger payment preserves pending choice and resources")
 await settle();await press("支付费用");await press("确定");view.reserve_resource(red.uid);view.reserve_resource(black.uid);await press("确认支付")
 expect(card.zone=="hand" and red.tapped and black.tapped,"UI trigger cost returns spell to hand after paying")
 clean(true);put("character-fdf-119","field");card=put("spell-fdf-078","exile");red=put("165","palette");var victim=put("50","field",1)
 e.Cat.grant_cast(e,card,0,false,{"红":1});view.auto_pay=false;view.render();await settle();view.choose_target(e.ref_target(victim));await press("确定")
 expect(view.local.get("action")=="choice_payment" and e.stack.is_empty(),"revealed-card casting offers private manual cost")
 view.reserve_resource(red.uid);await press("确认支付");expect(card.zone=="stack" and red.tapped,"revealed-card payment submits normal stack entry")
 view.render();await settle();await finish_group();await press("确定")
 resolve();resolve();expect(victim.zone=="grave","revealed Agni resolves its normal damage after Patchouli cast trigger")
 expect(FileAccess.get_file_as_string(Store.SAVE_PATH)==saved,"new UI keeps saved decks unchanged")
 print("V013_UI: ",checks," checks; ",failures," failures");quit(0 if failures.is_empty() else 1)
