extends "res://tests/test_v092.gd"
func run():
 var saved=FileAccess.get_file_as_string(Store.SAVE_PATH)
 app=load("res://main.tscn").instantiate(); root.add_child(app); await process_frame
 app.load_legacy_test_decks(); app.begin_battle(true); view=app.duel_view; view.set_process(false); e=view.engine
 # A unique-payment unit is still private until the explicit confirmation.
 clean(); view.auto_pay=true
 var unit=put("53","hand"); var yellow=put("164","palette")
 view.render(); await settle(); var before=snapshot()
 await drag(view.hand_nodes[unit.uid].get_global_rect().get_center(),Vector2(900,490))
 expect(not view.modal and view.local.get("mode")=="target" and find_button(view.ui,"确定")!=null,"drag opens bottom-right confirmation without a modal")
 expect(snapshot()==before and unit.zone=="hand" and not yellow.tapped,"unique auto-payment waits for explicit confirmation")
 await click(Vector2(1050,550),MOUSE_BUTTON_RIGHT)
 expect(view.local.is_empty() and snapshot()==before,"right click outside cancels before automatic payment")
 view.request_cast(unit.uid); await press("确定")
 expect(unit.zone=="stack" and yellow.tapped,"confirmed unique payment commits the unit once")
 expect(view.stack_target_arrows().is_empty(),"untargeted unit creates no target arrow")
 # Battlefield targets and player objects are highlighted, selected privately, reselectable.
 clean(); view.auto_pay=true
 var spell=put("96","hand"); var friendly=put("53","field"); var enemy=put("54","field",1)
 put("165","palette"); put("164","palette")
 e.players[0].life=27; e.players[1].life=8; view.render(); await settle()
 expect(view.life_widgets[0].bar.value==20 and "27" in view.life_widgets[0].button.text,"life above 20 shows the true number with a full bar")
 expect(view.life_widgets[1].button.get_global_rect().encloses(view.life_widgets[1].bar.get_global_rect()),"health bar remains inside its player object")
 expect(view.life_widgets[1].bar.value==8 and view.life_widgets[1].bar.max_value==20,"life below 20 uses proportional fill")
 before=snapshot(); view.request_cast(spell.uid)
 expect(not view.modal and [friendly.uid,enemy.uid].all(func(uid): return uid in view.highlights()),"targeted card uses battlefield blue outlines instead of a popup")
 expect(view.life_widgets[0].legal and view.life_widgets[1].legal,"both players are highlighted when legal targets")
 await click(point(enemy.uid))
 expect(view.picker.ready() and enemy.uid in view.selected_uids() and snapshot()==before,"selecting target turns it gold without payment or a public action")
 await click(view.life_widgets[0].button.get_global_rect().get_center())
 expect(view.life_widgets[0].selected and view.picker.option()=={"player":0},"player can replace the preselected unit as target")
 await click(point(enemy.uid)); await capture("inline-target")
 await click(Vector2(1000,570),MOUSE_BUTTON_RIGHT)
 expect(view.local.is_empty() and snapshot()==before,"right click cancels the entire targeted card declaration")
 view.request_cast(spell.uid); await click(point(enemy.uid)); await press("确定")
 if view.local.get("mode")=="payment_offer": await press("自动支付")
 await settle()
 expect(spell.zone=="stack" and e.stack.back().target.uid==enemy.uid,"confirmation preserves the declared battlefield target")
 expect(view.stack_target_arrows().size()==1 and view.stack_target_arrows()[0].target.uid==enemy.uid,"stack arrow points to the selected unit")
 expect(not view.stack_panel.tiles[e.stack.back().id].tile.get_meta("selected"),"committed source has no yellow border")
 await capture("stack-arrow-unit")
 resolve(); view.render(); await settle()
 expect(view.stack_target_arrows().is_empty(),"resolved stack entry removes its arrow")
 # Manual payment is entirely refundable, including multicolor source selection.
 clean(); view.auto_pay=false
 spell=put("96","hand"); var red=put("165","palette"); put("165","palette"); put("164","palette")
 view.render(); await settle(); before=snapshot(); view.request_cast(spell.uid)
 await click(view.life_widgets[1].button.get_global_rect().get_center()); await press("确定")
 expect(view.local.mode=="payment" and not view.modal,"manual payment follows confirmed target inline")
 view.reserve_resource(red.uid)
 expect(not view.local.plan.is_empty() and not red.tapped and snapshot()==before,"manual payment reserves resources privately")
 await click(Vector2(600,570),MOUSE_BUTTON_RIGHT)
 expect(view.local.is_empty() and not red.tapped and snapshot()==before,"right click during payment refunds every reservation")
 # Multiple auto-payment choices stay inline and remain cancellable.
 view.auto_pay=true; view.request_cast(spell.uid); view.choose_target({"player":1}); await press("确定")
 expect(view.local.get("mode")=="payment_offer" and not view.modal,"ambiguous payment asks inline instead of opening a modal")
 await click(Vector2(950,560),MOUSE_BUTTON_RIGHT)
 expect(snapshot()==before and view.local.is_empty(),"cancelling auto-payment offer is also private")
 # Player-directed arrow and response stack selection.
 view.request_cast(spell.uid); view.choose_target({"player":1}); await press("确定"); await press("自动支付"); await settle()
 expect(view.stack_target_arrows().size()==1 and view.stack_target_arrows()[0].target=={"player":1},"damage spell arrow points at opponent's life object")
 await capture("stack-arrow-player")
 clean(); view.auto_pay=true
 var hostile=put("96","hand",1); put("165","palette",1); put("164","palette",1)
 var counter=put("100","hand"); put("70","field"); put("164","palette"); put("164","palette")
 e.priority=1; var error=e.commit_cast(1,hostile.uid,{"player":0},e.payment(1,e.cards["96"].cost).plan)
 view.render(); await settle(); view.request_cast(counter.uid)
 expect(error.is_empty() and view.stack_panel.tiles[e.stack[0].id].tile.get_meta("legal"),"legal stack counter-target is blue")
 await click(view.stack_panel.card_rect(hostile.uid).get_center())
 expect(view.picker.ready() and view.stack_panel.tiles[e.stack[0].id].tile.get_meta("selected"),"selected stack counter-target is gold")
 await press("确定"); await settle()
 expect(counter.zone=="stack" and view.stack_target_arrows().size()==2,"counter adds an arrow to its stack target alongside the original arrow")
 await capture("stack-arrow-counter")
 resolve(); view.render(); await settle()
 expect(hostile.zone=="grave" and view.stack_target_arrows().is_empty(),"countered and resolved entries leave no dangling arrows")
 expect(FileAccess.get_file_as_string(Store.SAVE_PATH)==saved,"saved decks unchanged")
 print("V016_TARGETS: ",checks," checks; ",failures," failures")
 quit(0 if failures.is_empty() else 1)
