extends "res://tests/test_v011_rules.gd"
func run():
 fresh();var a=put("50");var b=put("51");resolve_spell("spell-ucs-008");expect(a.plus_counters==1 and b.plus_counters==1,"Dawn gives each own unit a counter")
 fresh();a=put("51","field",1);resolve_spell("spell-ucs-029",e.ref_target(a));expect(a.zone=="grave","Present Slash destroys cost at most three")
 fresh();a=put("164","palette");b=put("165","palette",1);resolve_spell("spell-ucs-026");expect(a.zone=="grave" and b.zone=="grave","Three-step destroys both entire palettes")
 fresh();var list=[]
 for i in range(5):a=put("164","palette");a.tapped=true;list.append(a)
 var options=e.targets_for("spell-ucs-014",0);expect(options[0].selection[0].max==4,"reset-four target cap")
 resolve_spell("spell-ucs-014",selected(options,[e.Pack.refs(e,list.slice(0,4))]));expect(list.slice(0,4).all(func(c):return not c.tapped) and list[4].tapped,"only four selected palette cards reset")
 fresh();put("74");put("2");put("166","palette");resolve_spell("spell-ucs-027",{"player":1});expect(e.players[1].life==17,"color damage counts three unique field colors, not green palette")
 fresh();var anthem=resolve_spell("spell-ucs-019");a=put("51","hand");expect(anthem.zone=="field" and e.cast_cost(0,a).is_empty() and e.cast_error(0,a.uid).is_empty(),"perpetual anthem permits no-color-cost casts")
 b=put("124","hand");expect(e.targets_for(b.card_id,0,b.uid).all(func(t):return t.get("x",0)==0),"free alternative cost restricts X to zero")
 fresh();a=put("character-ucs-048");e.judge();expect(a.zone=="grave","France doll has zero toughness without Alice")
 fresh();b=put("77");a=put("character-ucs-048");put("7");expect(e.stat(a,"health")==2,"France counts itself and the other doll while Alice is present");e.move_to(b,"grave");e.judge();expect(a.zone=="grave","France loses static bonus immediately without Alice")
 fresh();e.players[0].life=10;put("51","hand",1);enter("character-ucs-042");settle();expect(e.players[0].life==12 and e.players[0].hand.size()==1,"Parsee independently catches up on life and hand")
 fresh();e.players[0].leader.timer=2;enter("character-ucs-032");settle();expect(e.players[0].leader.timer==1,"Sakuya can remove one leader timer on entry")
 fresh();a=put("51","hand");b=put("50","field",1);enter("character-ucs-038");settle();expect(a.zone=="grave" and b.zone=="grave","Orin optional discard during ETB resolution destroys selected ordinary enemy")
 fresh();a=put("character-ucs-071");a.leader_counters=1;b=put("50","field",1);Roster.on_phase(e,"end");settle();expect(b.scare==1 and e.stat(a,"power")==1 and e.stat(a,"spirit")==1 and e.players[0].grave.size()==1 and e.players[1].grave.size()==1,"Kogasa scare buffs self and mills both players")
 a.entered_turns=0;e.priority=0;e.attack(0,a.uid);expect(e.legal_blockers().is_empty(),"scared unit cannot block leader Kogasa")
 fresh();a=put("character-ucs-072");a.leader_counters=1
 for i in range(5):put("51")
 roster_trigger(a,"kanako_cast");expect(e.units(0).size()==10 and e.field_slots(0)==6,"Kanako cast creates four no-slot brave pillars")
 Roster.on_phase(e,"end");settle();expect(e.units(0).all(func(c):return c.plus_counters==1),"Kanako leader boosts all ten units at end")
 fresh();mana();a=put("character-ucs-069","hand");a.leader=true;b=put("50");var enemy=put("50","field",1);put("51")
 expect(e.cast_cost(0,a,{"x":3}).get("黄")==2,"Miko discount counts units in pairs on both sides")
 put("168","field");put("164","field");var cost=e.cast_cost(0,a,{"x":3});var error=e.commit_cast(0,a.uid,{"none":true,"mode":"X = 3","x":3},e.payment(0,cost).plan);expect(error.is_empty(),"Miko X card is cast: "+error)
 one();expect(e.pending.get("kind")=="effect_choice" and e.pending.options[0].selection.size()==3,"Miko ETB allocates each of three damage points")
 options=e.pending.options;e.choose_effect(selected(options,[[e.ref_target(enemy)],[e.ref_target(enemy)],[e.ref_target(b)]]));one();expect(enemy.damage==2 and b.damage==1,"Miko aggregates repeated choices to a 2/1 damage split")
 fresh();a=put("spell-ucs-011");e.flip_coin(0);e.pump_choices();expect(e.pending.get("kind")=="effect_choice","coin roll publishes mandatory Rose damage with target choice");e.choose_effect({"player":1});one();expect(e.players[1].life==18,"coin anthem deals two to selected target")
 fresh();put("item-ucs-012","field",1);a=put("34");var before=e.players[1].life
 var t={"owner":0,"source":a.duplicate(true),"effect":"hourai_ping","roster":true,"extended":true,"optional":false,"name":"ping"}
 e.push_trigger(t,{"player":1});e.pump_choices();one();expect(e.pending.get("kind")=="effect_choice" and e.pending.owner==0,"backpack tax asks ability controller to pay")
 e.choose_effect({"none":true,"mode":"不支付"});settle();expect(e.players[1].life==before and e.stack.is_empty(),"declining tax counters the original ability")
 fresh();put("item-ucs-012","field",1);a=put("34");var resource=put("164","palette");t={"owner":0,"source":a.duplicate(true),"effect":"hourai_ping","roster":true,"extended":true,"optional":false,"name":"ping"}
 e.push_trigger(t,{"player":1});e.pump_choices();one();options=e.pending.options;var pay=options.filter(func(o):return o.get("uid")==resource.uid)[0];e.choose_effect(pay);settle();expect(resource.tapped and e.players[1].life==19,"paying any color preserves ability and resolves it")
 fresh();put("item-ucs-012","field",1);a=put("34");var enemy_unit=put("51","field",1);t={"owner":0,"source":a.duplicate(true),"effect":"hourai_ping","roster":true,"extended":true,"optional":false,"name":"ping"}
 Roster.event(e,a,"hourai_ping");e.pump_choices();e.choose_effect(e.ref_target(enemy_unit));expect(e.stack.size()==2 and e.stack.back().effect=="backpack_tax","mandatory trigger target completion invokes backpack exactly once")
 expect(e.cards["token-ucs-099"].token and not e.cards["token-ucs-099"].constructible,"supplied half-ghost image stays outside normal deck construction")
 fresh();mana();put("173");a=put("113","grave");error=e.commit_cast(0,a.uid,{"none":true},e.payment(0,e.cast_cost(0,a)).plan);settle();expect(error.is_empty() and a.zone=="field" and a.exile_on_grave,"Heart permission survives a time spell entering field")
 a.timer=0;e.judge();expect(a.zone=="exile","Heart time spell is exiled when its timer ends")
 fresh();mana();put("74");a=put("47");a.tapped=true;b=put("50","field",1);var gun=put("109","hand");error=e.commit_cast(0,gun.uid,e.ref_target(b),e.payment(0,e.cast_cost(0,gun)).plan)
 expect(error.is_empty() and not e.Pack.response_locked(e,0) and e.Pack.response_locked(e,1),"Gungnir response prohibition applies to opponent only")
 settle();expect(not a.tapped and e.stat(a,"power")==e.cards[a.card_id].power+1,"unrespondable Gungnir still causes mandatory own cast triggers")
 expect(Roster.text(e.cards["spell-ucs-011"],"coin_damage")==e.cards["spell-ucs-011"].rules_text,"derived trigger captions use Chinese source ability text")
 print("V011_UCS: %d checks; %d failures" % [checks,failures.size()]);quit(0 if failures.is_empty() else 1)
