extends "res://tests/test_v092.gd"
func capture(name:String):
 if DisplayServer.get_name()=="headless":return
 await RenderingServer.frame_post_draw
 root.get_texture().get_image().save_png("res://work/v017/"+name+".png")
func plan_ids() -> Array:return view.local.plan.map(func(p):return p.uid)
func blue_only() -> Array:return view.payment_sources().filter(func(s):return s.uid not in plan_ids()).map(func(s):return s.uid)
func fixture() -> Dictionary:
 var hand=put("5","hand");var rb=put("34","palette");var gb=put("5","palette");var item=put("167","field")
 return {"hand":hand,"rb":rb,"gb":gb,"item":item}
func run():
 var saved=FileAccess.get_file_as_string(Store.SAVE_PATH)
 app=load("res://main.tscn").instantiate();root.add_child(app);await process_frame
 app.load_test_decks();app.begin_battle(true);view=app.duel_view;view.set_process(false);e=view.engine
 clean();var f=fixture();view.render();await settle();var before=snapshot()
 await click(view.hand_nodes[f.hand.uid].get_global_rect().get_center())
 expect(view.local.mode=="target" and view.picker.ready(),"click immediately prepares the card")
 expect(plan_ids().size()==2 and f.item.uid in plan_ids() and f.gb.uid in plan_ids(),"recommend blue item and green-blue palette")
 expect(view.local.plan.any(func(p):return p.uid==f.gb.uid and p.color=="绿"),"dual palette pays green")
 expect(f.hand.uid in view.selected_uids() and [f.item.uid,f.gb.uid].all(func(u):return view.table.descriptors["card_"+str(u)].gold),"hand and both recommended resources are gold")
 expect(blue_only().is_empty() and find_button(view.ui,"发动")!=null,"complete plan offers activate without unrelated blue resources")
 expect(not view.table.descriptors["card_"+str(f.item.uid)].tapped and snapshot()==before,"recommendation never taps or publicly changes state")
 await capture("recommended-payment")
 await click(point(f.item.uid))
 expect(plan_ids()==[f.gb.uid] and blue_only().size()==2 and f.rb.uid in blue_only() and f.item.uid in blue_only(),"deselecting item exposes only remaining blue producers")
 expect(find_button(view.ui,"发动")==null and not view.local_prompt().begins_with("是否发动"),"incomplete payment hides activate and its question")
 expect(snapshot()==before,"deselect is private")
 await capture("replace-blue-resource")
 await click(point(f.rb.uid))
 expect(view.payment_ready() and f.rb.uid in plan_ids() and f.item.uid not in plan_ids(),"clicking blue replacement restores a payable plan")
 expect(view.local.plan.any(func(p):return p.uid==f.rb.uid and p.color=="蓝"),"replacement color assigned without color popup")
 expect(snapshot()==before and f.hand.zone=="hand","completed replacement still waits for activate")
 await press("发动");await settle()
 expect(f.hand.zone=="stack" and f.gb.tapped and f.rb.tapped and not f.item.tapped,"activate commits exactly the selected payment")
 expect(not view.stack_panel.tiles[e.stack.back().id].tile.get_meta("selected"),"committed stack card has no gold border")
 resolve();view.render();await settle()
 clean();f=fixture();put("24","field");view.render();await settle();before=snapshot();view.request_cast(f.hand.uid)
 expect(plan_ids()==[f.gb.uid] and view.local_cost().get("蓝",0)==0,"Ran discount is applied before recommendation")
 await click(point(f.gb.uid))
 expect(plan_ids().is_empty() and blue_only()==[f.gb.uid],"after Ran only the green-blue palette can fill remaining green")
 await capture("ran-discount")
 await click(point(f.gb.uid));expect(view.payment_ready(),"sole green source can be restored")
 await click(Vector2(800,20),MOUSE_BUTTON_RIGHT)
 expect(view.local.is_empty() and snapshot()==before,"right click cancels entire private declaration")
 view.settings_menu();expect(find_button(view.ui,"自动支付")==null and find_button(view.ui,"手动支付")==null,"settings no longer exposes payment modes");view.close_overlay()
 # Target selection and resource switching coexist; confirmation is a single commit.
 clean();var spell=put("96","hand");var enemy=put("53","field",1);var red=put("165","palette");var yellow=put("164","palette")
 view.render();await settle();before=snapshot();view.request_cast(spell.uid)
 expect(plan_ids().size()==2 and enemy.uid in view.highlights(),"targeted spell recommends payment while highlighting targets")
 expect(find_button(view.ui,"发动").disabled,"targeted spell cannot commit before target chosen")
 await click(point(enemy.uid));expect(view.picker.ready() and snapshot()==before,"battlefield target remains private")
 await click(point(red.uid));expect(not view.payment_ready() and find_button(view.ui,"发动")==null,"targeted spell resource can be deselected")
 await click(point(red.uid));await press("发动");await settle()
 expect(spell.zone=="stack" and e.stack.back().target.uid==enemy.uid and red.tapped and yellow.tapped,"one activate commits target and costs")
 expect(view.stack_target_arrows().size()==1,"target arrow remains after new payment flow")
 resolve();view.render();await settle()
 # Paid activated ability from grave.
 clean();var mokou=put("21","grave");red=put("165","palette");view.render();await settle();before=snapshot()
 view.execute_action(e.extra_action(mokou));expect(plan_ids()==[red.uid],"activated effect recommends its cost immediately")
 await click(point(red.uid));expect(find_button(view.ui,"发动")==null,"effect confirmation hides when its resource is removed")
 await click(point(red.uid));expect(snapshot()==before,"effect reselection is also private")
 await press("发动");await settle();expect(red.tapped and e.stack.size()==1,"activated effect pays once and enters stack")
 resolve();view.render();await settle();expect(mokou.zone=="hand","activated grave return resolves normally")
 # Shared-color cost must find a valid full completion around an already chosen color.
 clean();var blue=put("167","palette");red=put("165","palette")
 var cost={"红/蓝":1,"蓝/绿":1};var fixed=[{"uid":blue.uid,"color":"蓝"}]
 var solution=view.PaymentDraft.solve(e,0,cost,fixed)
 expect(solution.ways>0 and e.payment_valid(0,cost,solution.plan),"hybrid groups backtrack around fixed reservation")
 expect(view.PaymentDraft.solve(e,0,cost,fixed+[fixed[0]]).ways==0,"same resource cannot pay twice")
 expect(view.PaymentDraft.solve(e,0,{"蓝":1},[],[blue.uid]).ways==0,"tap-cost source exclusion respected")
 blue.tapped=true;expect(view.PaymentDraft.solve(e,0,cost,fixed).ways==0,"stale tapped reservation rejected")
 # Potato is only consumed at commit and remains replaceable.
 clean();var unit=put("5","hand");var green=put("166","palette");e.players[0].potato=true
 view.render();await settle();before=snapshot();view.request_cast(unit.uid)
 expect(-100 in plan_ids() and green.uid in plan_ids(),"potato fills only missing color")
 view.reserve_resource(-100);expect(-100 in blue_only() and not view.payment_ready(),"potato can be deselected and reselected")
 view.reserve_resource(-100);expect(snapshot()==before,"potato remains before activate")
 await press("发动");await settle();expect(not e.players[0].potato and unit.zone=="stack","potato disappears only after commit")
 # Free-choice and effect-granted casts still require confirmation.
 clean();unit=put("50","hand");e.players[0].next_free_unit=e.turn;view.render();await settle()
 view.request_cast(unit.uid);await press("不支付颜色使用")
 expect(view.local.plan.is_empty() and unit.zone=="hand","free choice still waits for activate")
 await press("发动");await settle();expect(unit.zone=="stack","free card commits on activate")
 clean();unit=put("5","hand");blue=put("167","palette");green=put("166","palette");e.Cat.grant_cast(e,unit,0,true);view.render();await settle()
 await press("支付颜色使用");await press("确定")
 expect(view.local.get("action")=="choice_payment" and plan_ids().size()==2 and unit.zone=="hand","effect-granted cast recommends resources before commit")
 before=snapshot();view.reserve_resource(blue.uid);view.reserve_resource(blue.uid)
 expect(snapshot()==before,"effect-granted reservation edits stay private")
 await press("发动");await settle();expect(unit.zone=="stack" and blue.tapped and green.tapped,"effect-granted paid cast commits selected resources")
 # Counterspells use the same private recommendation during opponent priority.
 clean();var hostile=put("96","hand",1);put("165","palette",1);put("164","palette",1)
 var counter=put("100","hand");put("70","field");put("164","palette");put("164","palette")
 e.priority=1;e.commit_cast(1,hostile.uid,{"player":0},e.payment(1,e.cast_cost(1,hostile)).plan)
 view.render();await settle();view.request_cast(counter.uid)
 expect(plan_ids().size()==2 and view.stack_panel.tiles[e.stack[0].id].tile.get_meta("legal"),"counter recommends resources and highlights opposing stack target")
 await click(view.stack_panel.card_rect(hostile.uid).get_center())
 expect(view.picker.ready() and counter.zone=="hand","counter target remains uncommitted until activate")
 await press("发动");await settle()
 expect(counter.zone=="stack" and view.stack_target_arrows().size()==2,"counter commits once and retains both stack arrows")
 resolve();view.render();await settle()
 expect(hostile.zone=="grave" and view.stack_target_arrows().is_empty(),"counter resolution clears stack arrows")
 expect(FileAccess.get_file_as_string(Store.SAVE_PATH)==saved,"saved decks unchanged")
 print("V017_PAYMENT: ",checks," checks; ",failures," failures");quit(0 if failures.is_empty() else 1)
