from pathlib import Path
root=Path(__file__).resolve().parents[1]
def edit(path,old,new):
 p=root/path;s=p.read_text(encoding='utf-8-sig');assert old in s,(path,old[:100]);p.write_text(s.replace(old,new),encoding='utf-8')
edit('scripts/duel_view.gd','func render_inline_picker(confirm: Callable,optional: bool=false):\n','func render_inline_picker(confirm: Callable,optional: bool=false):\n var choice_parent=hud\n var wide_choices=false\n')
edit('scripts/duel_view.gd','  if options.size()>16:\n   scroll.position.y=350;scroll.size.y=437','  if options.size()>16:\n   var panel=overlay("选择名称" if options.any(func(a):return a.value is Dictionary and a.value.has("card_name")) else "选择效果")\n   panel.size=Vector2(850,650);center_panel(panel);panel.set_meta("name_picker",true)\n   hud.remove_child(scroll);panel.add_child(scroll)\n   scroll.position=Vector2(24,70);scroll.size=Vector2(802,480)\n   choice_parent=panel;wide_choices=true')
edit('scripts/duel_view.gd','  var button=btn("确定" if local.is_empty() else "发动",Rect2(1330,799,237,49),confirm,true)','  var confirm_rect=Rect2(580,570,240,49) if wide_choices else Rect2(1330,799,237,49)\n  var button=btn("确定" if local.is_empty() else "发动",confirm_rect,confirm,true,choice_parent)')
# The modal is above the entire stack, including input. Observing brings it back.
edit('scripts/duel_view.gd',' modal=true\n var shade=',' modal=true\n if is_instance_valid(stack_panel):stack_panel.hide()\n var shade=')
edit('scripts/duel_view.gd',' modal_root=null\n',' modal_root=null\n if is_instance_valid(stack_panel):stack_panel.visible=not engine.stack.is_empty()\n')
edit('scripts/duel_view.gd',' if is_instance_valid(modal_root): modal_root.visible=not observing',' if is_instance_valid(modal_root): modal_root.visible=not observing\n if is_instance_valid(stack_panel):stack_panel.visible=not engine.stack.is_empty() and (not modal or observing)')
edit('scripts/duel_view.gd','  if d.zone not in ["field","leader"]: continue','  if d.zone not in ["field","palette","leader"]: continue')
edit('scripts/duel_view.gd','  card_badges[key]=parts\n','  var marks=board_counter_text(c)\n  if not marks.is_empty():\n   var mark=txt(marks,Rect2(0,0,100,68),14,Color("#fff2bb"),root)\n   mark.horizontal_alignment=HORIZONTAL_ALIGNMENT_CENTER\n   mark.add_theme_color_override("font_outline_color",Color("#081019"));mark.add_theme_constant_override("outline_size",5)\n   parts.counters=mark\n  if d.get("members",[]).size()>1:\n   var count=txt("×%d" % d.members.size(),Rect2(0,0,80,32),26,host.GOLD,root)\n   count.horizontal_alignment=HORIZONTAL_ALIGNMENT_CENTER;count.add_theme_color_override("font_outline_color",Color("#081019"));count.add_theme_constant_override("outline_size",6)\n   parts.token_count=count\n  card_badges[key]=parts\n')
edit('scripts/duel_view.gd','   if parts.has("courage"):parts.courage.position=Vector2(-rect.size.x/2,-rect.size.y/2-20)','   if parts.has("courage"):parts.courage.position=Vector2(-rect.size.x/2,-rect.size.y/2-20)\n   if parts.has("counters"):parts.counters.position=Vector2(-50,-rect.size.y/2+14)\n   if parts.has("token_count"):parts.token_count.position=Vector2(-40,rect.size.y/2-33)')
edit('scripts/duel_view.gd','func counter_lines(c: Dictionary) -> Array:','func board_counter_text(c: Dictionary) -> String:\n var marks=[]\n for line in counter_lines(c):marks.append(line.replace("属性指示物：","").replace("色指示物", "").replace("：", " "))\n return "\\n".join(marks)\n\nfunc counter_lines(c: Dictionary) -> Array:')
edit('scripts/duel_view.gd',' for name in c.get("counters",{}):',' var ward=0\n for w in c.get("wards",[]):ward+=maxi(0,int(w.get("amount",0)))\n if ward>0:lines.append("防避："+str(ward))\n for name in c.get("counters",{}):')
# Engine objects are never merged. Only identical, unselected keystones share a mesh.
edit('scripts/duel_table.gd','   var list=groups[group]\n   for i in range(list.size()):','   var bundles=[];var keys={}\n   for c in groups[group]:\n    var signature=""\n    if c.get("token",false) and duel.cards[c.card_id].name=="要石" and c.uid not in chosen and not reserved.any(func(r):return r.uid==c.uid):\n     var state=c.duplicate(true)\n     for field in ["uid","epoch","entered","entered_turns"]:state.erase(field)\n     signature=JSON.stringify(state)\n    if not signature.is_empty() and keys.has(signature):bundles[keys[signature]].append(c)\n    else:\n     if not signature.is_empty():keys[signature]=bundles.size()\n     bundles.append([c])\n   var list=bundles.map(func(b):return b[0])\n   for i in range(list.size()):')
edit('scripts/duel_table.gd','    d.group=group','    d.group=group;d.members=bundles[i].map(func(u):return u.uid)')
# Validation errors must survive following acknowledgements / room refreshes.
edit('net/lan_lobby.gd','var deck_index=0','var deck_index=0\nvar last_error=""')
edit('net/lan_lobby.gd','func show_error(message: String):status_label.text=message','func show_error(message: String):\n last_error=message;status_label.text=message\n app.alert(message,"无法进行联机操作")')
edit('net/lan_lobby.gd',' status_label.text=session.notice if not session.notice.is_empty() else session.discovery.error',' status_label.text=last_error if not last_error.is_empty() else session.notice if not session.notice.is_empty() else session.discovery.error')
edit('net/lan_lobby.gd','    if not app.decks.is_empty():session.room_action({"name":"deck","deck":app.decks[deck_index]})','    if app.decks.is_empty():return\n    var deck=app.Store.clean_deck(app.decks[deck_index])\n    var error=app.Store.validate(deck,room.get("strict",true))\n    if not error.is_empty():show_error(error);return\n    last_error="";session.room_action({"name":"deck","deck":deck})')
# Validate an independent data object, never a host-local deck ID or local path.
edit('net/series_controller.gd',' state.decks[seat]=deck.duplicate(true);state.ready[seat]=false',' state.decks[seat]=Store.clean_deck(deck);state.ready[seat]=false')
print('UI / deck submission patch complete')
