from pathlib import Path
p=Path(r'C:\Users\tzx20\Documents\test')
f=p/'scripts/duel_table.gd'
s=f.read_text(encoding='utf-8-sig')
s=s.replace('var camera_distance = 0.82','var camera_distance = 0.82\nvar label_font: SystemFont\nstatic var material_cache = {}')
s=s.replace(' var m=StandardMaterial3D.new()',' var key=str(color)+":"+str(tex.get_instance_id() if tex else 0)\n if material_cache.has(key): return material_cache[key]\n var m=StandardMaterial3D.new()',1)
s=s.replace(' m.cull_mode=BaseMaterial3D.CULL_DISABLED\n return m',' m.cull_mode=BaseMaterial3D.CULL_DISABLED\n material_cache[key]=m\n return m',1)
s=s.replace(' texture_provider=provider',' texture_provider=provider\n label_font=SystemFont.new()\n label_font.font_names=PackedStringArray(["Microsoft YaHei UI","Microsoft YaHei"])')
s=s.replace('var x=-3.0+unit_index*2.4','var x=-4.8+(unit_index%3)*2.4')
s=s.replace('Vector3(x,0.08,0.9*z)','Vector3(x,0.08,(1.65+(unit_index/3)*2.3)*z)')
s=s.replace('Vector3(x,0.1,2.13*z)','Vector3(x,0.14,(2.8+(unit_index/3)*2.3)*z)')
s=s.replace('Vector3(-4.8+group*2.15+n*0.16,0.06+n*0.065,3.3*z),enemy)','Vector3(-4.8+group*2.1+n*0.55,0.06+n*0.03,3.95*z),enemy,true)')
s=s.replace('var at=Vector3(6.0+i*0.27,0.8+i*0.23,-0.65-i*0.23)','var at=Vector3(4.7+i*0.9,1.0+i*0.32,0.8-i*0.35)')
s=s.replace('mesh.rotation.y=deg_to_rad(-8+i*3)','mesh.rotation.y=deg_to_rad(-12+i*6)')
s=s.replace('  area.set_meta("kind","stack"); area.set_meta("stack_id",entry.id)','  area.set_meta("kind","stack"); area.set_meta("stack_id",entry.id)\n  area.set_meta("card_id",id)')
s=s.replace('surface_label("对抗  %d" % duel.stack.size(),Vector3(6.2,0.2,2.3)','surface_label("堆叠  %d" % duel.stack.size(),Vector3(5.9,0.2,3.0)')
s=s.replace(' area.set_meta("kind","object"); area.set_meta("uid",c.uid)',' area.set_meta("kind","object"); area.set_meta("uid",c.uid)\n area.set_meta("card_id",c.card_id)\n if not duel.combat.is_empty() and (duel.combat.attacker.uid==c.uid or duel.combat.blockers.any(func(t): return t.uid==c.uid)):\n  surface_label("攻击" if duel.combat.attacker.uid==c.uid else "阻挡",at+Vector3(0,0.19,0),Color("#ffbc78"),0.004)')
start=s.index('func single_card(')
end=s.index('func pile(',start)
s=s[:start]+s[end:]
s=s.replace(' var font=SystemFont.new()\n font.font_names=PackedStringArray(["Microsoft YaHei UI","Microsoft YaHei"])\n l.font=font',' l.font=label_font')
f.write_text(s,encoding='utf-8')
# Engine: resolve brave on stack; entry triggers only on actual entry.
f=p/'scripts/rules/duel_engine.gd';s=f.read_text(encoding='utf-8-sig')
s=s.replace('func enter_field(c: Dictionary,who: int):','func enter_field(c: Dictionary,who: int) -> bool:')
s=s.replace('if units(who).size()>=6: to_grave(c); return','if units(who).size()>=6: to_grave(c); return false')
s=s.replace('if cards[u.card_id].title==cards[c.card_id].title:\n    to_grave(c); return','if cards[u.card_id].title==cards[c.card_id].title and not cards[c.card_id].title.is_empty():\n    to_grave(c); return false')
s=s.replace('shift(c,"field"); c.entered=turn; players[who].field.append(c)','shift(c,"field"); c.entered=turn; players[who].field.append(c)\n return true')
s=s.replace('   damage_target(e.target,e.amount); note("能力结算")','   if e.get("effect","")=="untap":\n    if target_valid(e.target,true): find_card(e.target.uid).tapped=false\n   else: damage_target(e.target,e.amount)\n   note(e.name+"结算")')
s=s.replace('    if c.attacked and DB.has_ability(cards[c.card_id],"brave"): c.tapped=false','    if c.attacked and DB.has_ability(cards[c.card_id],"brave"):\n     stack.append({"id":next_stack,"kind":"ability","source":c.duplicate(true),"owner":active,"effect":"untap","target":ref_target(c),"name":cards[c.card_id].name+" · 英勇"})\n     next_stack+=1\n   if not stack.is_empty(): note("英勇进入堆叠")')
f.write_text(s,encoding='utf-8')
f=p/'scripts/rules/demo_abilities.gd';s=f.read_text(encoding='utf-8-sig').replace('  engine.enter_field(entry.card,entry.owner)\n  if DB.has_ability(card,"marisa_enter"):','  var entered=engine.enter_field(entry.card,entry.owner)\n  if entered and DB.has_ability(card,"marisa_enter"):');f.write_text(s,encoding='utf-8')
# Avoid nonessential instructional prose, and put recent action outside the hand row.
f=p/'scripts/duel_view.gd';s=f.read_text(encoding='utf-8-sig')
s=s.replace('Rect2(270,856,990,30)','Rect2(335,56,970,28)')
s=s.replace(' txt("保留可用的双色资源，优先保留红薯。",Rect2(32,135,590,38),18,host.WHITE,panel)','')
# Mark the top stack object in the existing HUD for readable names, without card duplicates outside table.
s=s.replace(' render_hand()',' if not engine.stack.is_empty():\n  txt(engine.stack.back().name,Rect2(910,605,650,42),19,host.WHITE)\n render_hand()',1)
f.write_text(s,encoding='utf-8')
# Keep construction ban an invariant for eventual generated-only cards.
f=p/'scripts/deck_store.gd';s=f.read_text(encoding='utf-8-sig')
s=s.replace(' if strict and d.main.size()', ' for id in d.main+d.side+[d.leader]:\n  if not CARDS[id].constructible: return "不能加入常规卡组："+CARDS[id].name\n if strict and d.main.size()')
s=s.replace(' if zone == "leader":',' if not CARDS[id].constructible: return "不能加入常规卡组："+CARDS[id].name\n if zone == "leader":',1)
f.write_text(s,encoding='utf-8')
