from pathlib import Path
p=Path('tests/test_v013_ui.gd');s=p.read_text(encoding='utf-8');at=s.index(' expect(FileAccess.get_file_as_string(Store.SAVE_PATH)==saved')
s=s[:at]+''' clean(true);card=put("spell-fdf-028","grave");var red=put("165","palette");var black=put("168","palette")
 e.Cat.Units.resolve(e,{"source":card.duplicate(true),"effect":"cat:nuclear_return","owner":0,"target":{"none":true},"data":{},"name":e.cards[card.card_id].name})
 view.auto_pay=false;view.render();await settle();await press("支付费用");await press("确定")
 expect(view.local.get("action")=="choice_payment" and card.zone=="grave" and not red.tapped,"trigger payment opens private manual selection")
 view.cancel_cast();expect(card.zone=="grave" and not red.tapped and not e.pending.is_empty(),"canceling trigger payment preserves pending choice and resources")
 await settle();await press("支付费用");await press("确定");view.reserve_resource(red.uid);view.reserve_resource(black.uid);await press("确认支付")
 expect(card.zone=="hand" and red.tapped and black.tapped,"UI trigger cost returns spell to hand after paying")
 clean(true);put("character-fdf-119","field");card=put("spell-fdf-078","exile");red=put("165","palette");var victim=put("50","field",1)
 e.Cat.grant_cast(e,card,0,false,{"红":1});view.auto_pay=false;view.render();await settle();view.choose_target(e.ref_target(victim));await press("确定")
 expect(view.local.get("action")=="choice_payment" and e.stack.is_empty(),"revealed-card casting offers private manual cost")
 view.reserve_resource(red.uid);await press("确认支付");expect(card.zone=="stack" and red.tapped,"revealed-card payment submits normal stack entry")
 resolve();expect(victim.zone=="grave","revealed Agni resolves its normal damage after payment")
'''+s[at:];p.write_text(s,encoding='utf-8')
