from pathlib import Path
import re
R=Path.cwd()
def edit(path,func):
 p=R/path;s=p.read_text(encoding='utf-8-sig');p.write_text(func(s),encoding='utf-8')
def cat(s):
 s=s.replace('const Units=', 'const State=preload("res://scripts/rules/catalogue_state.gd")\nconst Units=',1)
 s=s.replace('static func spell_options(e,id,who):return Spells.options(e,id,who) if id in SPELLS else null','static func spell_options(e,id,who):\n var extra=extra_cast_options(e,id,who)\n return extra if extra!=null else Spells.options(e,id,who) if id in SPELLS else null')
 s=s.replace(' for k in words:d[k]=true',' for k in words:\n  if k.begins_with("防避"):e.Pack.shield(e,e.ref_target(c),[int(k.trim_prefix("防避"))])\n  else:d[k]=true')
 s=s.replace(' if id=="spell-fdf-012":targets=[];for i in range(1,t.get("picks",[]).size()):targets.append_array(t.picks[i])',' if id=="spell-fdf-012":\n  targets=[]\n  for i in range(1,t.get("picks",[]).size()):targets.append_array(t.picks[i])')
 s=s.replace('   for r in t.picks[i]:var key=str(r);counts[key]=int(counts.get(key,0))+1;if counts[key]>2:return false','   for r in t.picks[i]:\n    var key=str(r);counts[key]=int(counts.get(key,0))+1\n    if counts[key]>2:return false')
 return s
edit('scripts/rules/catalogue_abilities.gd',cat)
def roster(s):
 s=s.replace(' e.triggers.append({',' e.Cat.enqueue(e,{')
 s=s.replace(' var n=0\n if has(e.cards[c.card_id],"france_doll")',' var n=Cat.State.stat_adjust(e,c,k)\n if has(e.cards[c.card_id],"france_doll")')
 s=s.replace('static func keyword(e,c: Dictionary,k: String) -> bool:\n','static func keyword(e,c: Dictionary,k: String) -> bool:\n if Cat.State.keyword(e,c,k):return true\n')
 s=s.replace(' if forced(e,c,who): return true',' if forced(e,c,who) or Cat.State.permission(e,c,who): return true')
 s=s.replace(' return forced(e,c,who) or permission(e,c,who) and c.get("excel_access",{}).get("ignore",false)',' return forced(e,c,who) or Cat.State.bypass(e,c,who) or permission(e,c,who) and c.get("excel_access",{}).get("ignore",false)')
 s=s.replace(' return forced(e,c,who) or permission(e,c,who) and c.zone=="exile" or',' return (forced(e,c,who) and e.forced_cast.get("free",true)) or Cat.State.free(e,c,who) or (c.get("excel_access",{}).get("owner",-1)==who and c.excel_access.turn==e.turn) or')
 s=s.replace('static func protected(e,t: Dictionary,who: int,spell: bool) -> bool:\n','static func protected(e,t: Dictionary,who: int,spell: bool) -> bool:\n if Cat.State.protected(e,t,who,spell):return true\n')
 s=s.replace('static func target_survives(e,id: String,t: Dictionary) -> bool:\n','static func target_survives(e,id: String,t: Dictionary) -> bool:\n if id in Cat.SPELLS:return Cat.target_survives(e,id,t)\n')
 s=s.replace('var full=e.field_slots(who)+slots>6','var full=e.field_slots(who)+slots>Cat.field_limit(e,who)')
 # Existing 'grant_cast' used by v0.11 remains free by default.
 return s
edit('scripts/rules/excel_abilities.gd',roster)
def engine(s):
 s=s.replace('var extra_turns=[]','var extra_turns=[]\nvar catalogue_death_depth=0\nvar catalogue_target_fast=false')
 s=s.replace(' Roster.on_coin(self,who)',' Roster.on_coin(self,who);Cat.State.on_coin(self,who,heads)')
 s=s.replace(' if c.get("leader",false) or c.get("leader_counters",0)>0: return true',' if Cat.State.grant_self(self,c) or c.get("leader",false) or c.get("leader_counters",0)>0: return true')
 s=s.replace(' shift(c,"hand"); players[who].hand.append(c)',' shift(c,"hand"); players[who].hand.append(c);Cat.State.on_draw(self,who)')
 s=s.replace(' var old=c.get("zone","")',' var old=c.get("zone","")\n if c.has("copy_original") or c.has("habitat_base"):\n  c.card_id=c.get("copy_original",c.get("habitat_base",c.card_id));c.erase("copy_original");c.erase("habitat_base");c.erase("inherited_self")')
 s=s.replace(' c.leader_counters=0',' c.leader_counters=0\n for k in ["locked_name","rank_target","imp_growth","reisen_illusion","catalogue_access","catalogue_castle","dream","madness","noncombat_damage_turn"]:c.erase(k)\n if old!="stack" or location!="field":\n  for k in ["ichirin_paid","top_free_damage","haste_on_enter","exiled_hand","paid_dolls"]:c.erase(k)')
 s=s.replace(' if players[who].potato: sources.append',' sources.append_array(players[who].get("mana",[]))\n if players[who].potato: sources.append')
 s=s.replace(' var info=cards[c.card_id]\n if not Pack.fast',' var info=cards[c.card_id]\n var catalogue_error=Cat.State.cast_error(self,c,who)\n if not catalogue_error.is_empty():return catalogue_error\n if not Pack.fast',1)
 s=s.replace('field_slots(who)>=6','field_slots(who)>=Cat.field_limit(self,who)')
 s=s.replace('   var provided=[]','   var provided=[]\n   if Cat.race(self,c,"吸血鬼") and units(who).any(func(u):return Cat.has(self,u,"character-fdn-014")):provided=COLORS.duplicate()',1)
 s=s.replace('  var present=false','  var present=Cat.State.role_present(self,c,who)',1)
 s=s.replace('if payment(who,cast_cost(who,c)).ways==0:','if payment(who,cast_cost(who,c)).ways==0 and not Cat.alternative_affordable(self,c,who):',1)
 s=s.replace(' var extended=Extra.spell_options(self,id,acting)',' catalogue_target_fast=cards[id].fast\n var extended=Extra.spell_options(self,id,acting)',1)
 s=s.replace(' if info.kind=="符卡" or not info.get("variable_cost","").is_empty():',' if info.kind=="符卡" or not info.get("variable_cost","").is_empty() or c.card_id=="character-fdf-046":',1)
 s=s.replace(' var old_zone=c.zone\n # All validation',' var old_zone=c.zone\n # All validation',1)
 s=s.replace(' for reservation in plan:\n  if reservation.uid<0: players[who].potato=false\n  else: tap_card(find_card(reservation.uid))',' Cat.pay(self,who,plan)\n var catalogue_paid=Cat.paid_cast(self,c,target)',1)
 s=s.replace(' shift(c,"stack"); c.owner=who',' shift(c,"stack"); c.owner=who;c.merge(catalogue_paid,true)',1)
 s=s.replace(' triggers.append({"owner":who',' Cat.enqueue(self,{"owner":who',1)
 s=s.replace('  shift(c,"leader"); add_timer(c,0 if Roster.enabled(self,before,"cirno_return") else 2)','  shift(c,"leader"); add_timer(c,0 if Roster.enabled(self,before,"cirno_return") else maxi(0,2-(Cat.with_key(self,c.owner,"field-fdf-107").size() if Cat.race(self,c,"神") else 0)))')
 s=s.replace(' if amount<=0: return\n players[who].life+=amount; Pack.on_gain_life(self,who,amount)',' if amount<=0 or not Cat.with_key(self,-1,"spell-fdn-002").is_empty(): return\n players[who].life+=amount; Pack.on_gain_life(self,who,amount);Cat.State.on_gain(self,who,amount)')
 s=s.replace(' if target.has("player"): players[int(target.player)].life-=amount',' var remaining=0 if target.has("player") else stat(find_card(target.uid),"health")-find_card(target.uid).damage\n if target.has("player"): players[int(target.player)].life-=amount')
 s=s.replace(' Roster.on_damage(self,target,amount)',' Roster.on_damage(self,target,amount);Cat.State.on_damage(self,target,amount,remaining)')
 s=s.replace(' Pack.state_checks(self)',' Cat.State.state_checks(self)\n Pack.state_checks(self)',1)
 s=s.replace(' var old_phase=phase',' var old_phase=phase\n for p in players:p.mana=[]')
 s=s.replace('  players[who].hand.append(p); players[who].palette.append(h)','  players[who].hand.append(p); players[who].palette.append(h);Cat.State.on_palette(self,h)')
 s=s.replace('  note("凭依完成")\n pending={}; priority=active; passes=0; revision+=1','  note("凭依完成")\n  players[who].possession_count=int(players[who].get("possession_count",0))+1\n pending={}; priority=active; passes=0; revision+=1\n if palette_uid>=0 and players[who].get("possession_count",0)<(3 if not Cat.with_key(self,who,"spell-htk-004").is_empty() else 1):offer_possession()\n pump_choices()')
 s=s.replace(' phase="reset"; turn_usage.clear();',' players[who].possession_count=0\n phase="reset"; turn_usage.clear();')
 s=s.replace('players[who].palette.append(c)\n phase="prepare"','players[who].palette.append(c);Cat.State.on_palette(self,c)\n phase="prepare"')
 s=s.replace(' for p in players:\n  p.wards=[]; p.wine=[]',' for p in players:\n  p.wards=[]; p.wine=[];p.mana=[]')
 s=s.replace('and not c.tapped and (not summoning_sick(c) or has_haste(c))','and not c.tapped and Cat.State.can_combat(self,c) and (not summoning_sick(c) or has_haste(c))')
 s=s.replace(' if c.tapped: continue\n  if Roster.enabled',' if c.tapped or not Cat.State.can_combat(self,c): continue\n  if Cat.has(self,attacker,"character-fdn-035") and cards[c.card_id].kind!="自机":continue\n  if Roster.enabled')
 s=s.replace(' for c in chosen: tap_card(c); combat.blockers.append(ref_target(c)); Pack.on_attack_or_block(self,c,false)',' if chosen.is_empty() and not valid.is_empty() and Cat.has(self,find_card(combat.attacker.uid),"character-fdf-090"):return\n for c in chosen:\n  if not Cat.enabled(self,c,"character-ucs-061:self"):tap_card(c)\n  combat.blockers.append(ref_target(c));Pack.on_attack_or_block(self,c,false);Cat.Units.on_block(self,c)\n if not chosen.is_empty():Cat.Units.on_blocked(self,find_card(combat.attacker.uid))')
 s=s.replace(' if not target.is_empty() and (not Pack.direct_attack(self,c)',' if not target.is_empty() and (not (Pack.direct_attack(self,c) or find_card(target.get("uid",-1)).has("rank_target"))')
 s=s.replace(' tap_card(c); c.attacked=true',' tap_card(c); c.attacked=true\n if target.is_empty():players[who].attacked_player_turn=turn',1)
 s=s.replace(' var cost=Pack.cost(self,c,who,cards[c.card_id].cost,target)',' var cost=Pack.cost(self,c,who,cards[c.card_id].cost,target)')
 s=s.replace(' if c.is_empty(): return\n if allow_replacement',' if c.is_empty(): return\n if c.get("stack_copy",false) and c.zone=="stack" and zone!="field":detach(c);shift(c,"void");return\n if allow_replacement',1)
 s=s.replace(' if zone!="leader": players[c.owner][zone].append(c)',' if zone!="leader": players[c.owner][zone].append(c)\n if zone=="palette":Cat.State.on_palette(self,c)')
 s=s.replace(' return units(c.owner).filter(func(u): return Extra.has(cards[u.card_id],"grave_return_replace")',' if Cat.character(self,c,"藤原妹红") and not Cat.with_key(self,c.owner,"spell-fdn-001").is_empty():return Cat.with_key(self,c.owner,"spell-fdn-001")\n return units(c.owner).filter(func(u): return Extra.has(cards[u.card_id],"grave_return_replace")')
 s=s.replace('if to_field and not grave_replacement_sources(c).is_empty(): detach(c); enter_field(c,c.owner)','if to_field and not grave_replacement_sources(c).is_empty():\n   var moon=Cat.character(self,c,"藤原妹红") and not Cat.with_key(self,c.owner,"spell-fdn-001").is_empty();detach(c);enter_field(c,c.owner)\n   if moon and active==c.owner:c.tapped=true')
 s=s.replace(' Roster.Batch.counter(self,c,"timer",amount,c.owner)',' Roster.Batch.counter(self,c,"timer",amount,c.owner)\n if amount>0 and c.zone in ["field","leader"]:\n  for f in Cat.with_key(self,c.owner,"spell-fdf-017"):Cat.events(self,f,"cat:murder_dolls",true,{"amount":amount})')
 s=s.replace(' if Roster.Batch.locked(self,c):',' if Cat.State.activation_locked(self,c):return "该对象的启动能力被禁止"\n if Roster.Batch.locked(self,c):')
 s=s.replace('var zone="grave" if key in ["grave_return","grave_reanimate"] else "field"','var zone="grave" if key in ["grave_return","grave_reanimate","spell-fdf-059","character-fdf-111"] else "field"')
 s=s.replace(' for item in plan:\n  if item.uid<0: players[who].potato=false\n  else: tap_card(find_card(item.uid))',' Cat.pay(self,who,plan)',1)
 s=s.replace(' stack.append({"id":next_stack,"kind":"ability","activation":true',' if key=="character-fdf-098":\n  Cat.add_mana(self,who,["黄","绿"]);revision+=1;return ""\n stack.append({"id":next_stack,"kind":"ability","activation":true',1)
 s=s.replace('func sacrifice(c: Dictionary):\n move_to(c,"grave")','func sacrifice(c: Dictionary):\n if c.is_empty():return\n var before=c.duplicate(true);move_to(c,"grave");Cat.Units.on_sacrifice_or_exile(self,before)\n if is_unit(before):\n  for u in players[before.owner].grave:\n   if Cat.has(self,u,"spell-fdf-047") and units(before.owner).any(func(v):return Cat.character(self,v,"西行寺幽幽子")):Cat.events(self,u,"cat:sacrifice_recover",true)')
 return s
edit('scripts/rules/duel_engine.gd',engine)
def pack(s):
 s=s.replace(' e.triggers.append({',' e.Cat.enqueue(e,{')
 s=s.replace(' return trigger_locked(e) or e.stack.any',' return e.players[who].get("night_lock",-1)==e.turn or e.stack.any(func(s):return s.kind=="card" and e.Cat.has(e,s.card,"spell-fdn-008")) or trigger_locked(e) or e.stack.any')
 s=s.replace(' result=e.Roster.cost(e,c,who,result)',' result=e.Roster.cost(e,c,who,result)\n result=e.Cat.State.cost(e,c,who,result,target)')
 s=s.replace(' if "追击" in info.get("keywords",[])',' if e.Extra.keyword(e,source,"追击")')
 s=s.replace(' return has(e.cards[c.card_id],"flandre_direct") and e.has_leader_ability(c)',' return e.Extra.keyword(e,c,"直接攻击单位") or has(e.cards[c.card_id],"flandre_direct") and e.has_leader_ability(c)')
 return s
edit('scripts/rules/precon_abilities.gd',pack)
def extra(s):
 s=s.replace(' e.triggers.append({',' e.Cat.enqueue(e,{')
 s=s.replace('static func on_death(e,c: Dictionary,before: Dictionary):','static func on_death(e,c: Dictionary,before: Dictionary):\n e.catalogue_death_depth+=1\n _on_death_core(e,c,before)\n e.catalogue_death_depth-=1\nstatic func _on_death_core(e,c: Dictionary,before: Dictionary):')
 s=s.replace(' if not e.is_unit(c): return\n var info=e.cards[c.card_id]',' if not e.is_unit(before): return\n var info=e.cards[before.card_id]')
 return s
edit('scripts/rules/expanded_abilities.gd',extra)
# New zone permissions are usable by AI and the hand region tabs.
edit('scripts/rules/duel_engine.gd',lambda s:s.replace('options.append_array(players[who].deck.filter(func(c): return Extra.has(cards[c.card_id],"deck_damage")))','options.append_array(players[who].palette.filter(func(c):return Cat.State.permission(self,c,who)))\n options.append_array(players[who].deck.filter(func(c): return Extra.has(cards[c.card_id],"deck_damage") or Cat.State.permission(self,c,who)))'))
edit('scripts/duel_view.gd',lambda s:s.replace('for zone in ["grave","exile","deck"]:','for zone in ["grave","exile","deck","palette"]:'))
