from pathlib import Path
import json
R=Path.cwd()
def edit(path,fn):
 p=R/path;s=p.read_text(encoding='utf-8-sig');p.write_text(fn(s),encoding='utf-8')
edit('scripts/rules/catalogue_abilities.gd',lambda s:s.replace('"cat:fight":fight(e,d.ref,aim)','"cat:fight":forced_battle(e,d.ref,aim)').replace('"sacrifice":e.sacrifice(c)','"sacrifice":\n      if not (character(e,c,"半灵") and not with_key(e,c.owner,"spell-fdn-012").is_empty()):e.sacrifice(c)').replace('static func reveal(e,list):','static func reveal(e,list,from_top=true):').replace('c.zone=="deck" and not e.players[c.owner].deck.is_empty() and e.players[c.owner].deck[0].uid==c.uid and c.card_id','from_top and c.zone=="deck" and c.card_id'))
edit('scripts/rules/catalogue_units.gd',lambda s:s.replace('var top=p.deck.slice(maxi(0,p.deck.size()-3)) if k=="character-fdf-092" else p.deck.slice(0,3);C.reveal(e,top)','var top=p.deck.slice(maxi(0,p.deck.size()-3)) if k=="character-fdf-092" else p.deck.slice(0,3);C.reveal(e,top,k!="character-fdf-092")').replace('"character-fdf-046":if same:C.fight(e,C.ref(e,c),a)','"character-fdf-046":if same:C.forced_battle(e,C.ref(e,c),a)').replace('"field-ucs-064":C.fight(e,d.ref,a)','"field-ucs-064":C.forced_battle(e,d.ref,a)').replace('C.reveal(e,[u]);e.move_to(u,"exile");u.dream=1','C.reveal(e,[u],false);e.move_to(u,"exile");u.dream=1'))
edit('scripts/rules/catalogue_spells.gd',lambda s:s.replace('C.reveal(e,list)\n   if d.zone','C.reveal(e,list,false)\n   if d.zone').replace('e.move_to(u,"hand");C.reveal(e,[u])','e.move_to(u,"hand");C.reveal(e,[u],false)').replace('C.reveal(e,list)\n   var eligible','C.reveal(e,list,false)\n   var eligible'))
# Distinct alternatives retain modes and full metadata through the same picker.
edit('scripts/target_picker.gd',lambda s:s.replace('return path.size()>1 or steps(specs[state.index].fixed_option).is_empty()','return path.filter(func(a):return a.kind!="spec").size()>=steps(specs[state.index].fixed_option).filter(func(a):return a.kind!="mode").size()').replace(' if state.index<0: return "选择一项"',' if state.index<0: return "选择一项"\n if specs[state.index].has("fixed_option"):return specs[state.index].get("title","")'))
# Entering timed spells through searches also initializes time counters.
edit('scripts/rules/catalogue_units.gd',lambda s:s.replace(' var C=e.Cat;var who=c.owner\n for k in ENTER:', ' var C=e.Cat;var who=c.owner\n C.State.sync_fairies(e)\n if c.card_id in C.SPELLS and "时符" in e.cards[c.card_id].spell_type:e.add_timer(c,int(c.get("cast_x",0)) if c.card_id=="spell-fdf-024" else e.cards[c.card_id].time)\n if c.get("haste_on_enter",false):C.buff(e,c,0,0,0,["疾行"])\n for word in e.cards[c.card_id].get("keywords",[]):\n  if word.begins_with("防避"):c.wards=c.get("wards",[])+[{"amount":int(word.trim_prefix("防避")),"turn":-1}]\n for k in ENTER:'))
edit('scripts/rules/catalogue_spells.gd',lambda s:s.replace('  if e.enter_field(c,who):\n   e.add_timer(c,int(aim.get("x",0)) if id=="spell-fdf-024" else int(e.cards[id].time))','  c.cast_x=int(aim.get("x",0));e.enter_field(c,who)'))
edit('scripts/rules/precon_abilities.gd',lambda s:s.replace('if w.turn!=e.turn:','if w.turn not in [-1,e.turn]:'))
edit('scripts/rules/excel_abilities.gd',lambda s:s.replace('return r in e.cards[c.card_id].race or "全部" in e.cards[c.card_id].race','return r in e.cards[c.card_id].race or "全部" in e.cards[c.card_id].race or r=="神" and "八百万之神" in e.cards[c.card_id].race'))
# Trigger batches retain a serial across all objects affected by one action.
edit('scripts/rules/catalogue_abilities.gd',lambda s:s.replace(' var count=1\n if e.catalogue_death_depth>0:', ' t.catalogue_serial=e.catalogue_serial\n if t.get("effect","") in ["character-htk-005","cat:nuclear_return","cat:god_damage","character-ucs-044"]:\n  for queued in e.triggers:\n   if queued.get("catalogue_serial",-1)==e.catalogue_serial and queued.source.uid==c.uid and queued.get("effect")==t.effect:\n    if t.effect=="cat:god_damage":queued.data.amount+=t.data.amount\n    return\n var count=1\n if e.catalogue_death_depth>0:').replace('if e.is_unit(c):count+=with_key(e,who,"spell-fdn-019").size()','if who==e.catalogue_death_owner:count+=with_key(e,who,"spell-fdn-019").size()'))
edit('scripts/rules/expanded_abilities.gd',lambda s:s.replace(' e.catalogue_death_depth+=1',' var old_owner=e.catalogue_death_owner;e.catalogue_death_owner=before.owner\n e.catalogue_death_depth+=1').replace(' e.catalogue_death_depth-=1',' e.catalogue_death_depth-=1;e.catalogue_death_owner=old_owner').replace('  "token_sacrifice":\n','  "token_sacrifice":\n   if e.Cat.character(e,source,"半灵") and not e.Cat.with_key(e,who,"spell-fdn-012").is_empty():return\n'))
def engine(s):
 s=s.replace('var catalogue_death_depth=0','var catalogue_death_depth=0\nvar catalogue_death_owner=-1\nvar catalogue_serial=0')
 s=s.replace(' # All validation completes before any public mutation.',' catalogue_serial+=1\n # All validation completes before any public mutation.')
 s=s.replace('  var e=stack.pop_back()','  catalogue_serial+=1\n  var e=stack.pop_back()')
 s=s.replace(' var source=c.duplicate(true)\n if key in Roster.ACTIVATIONS',' catalogue_serial+=1\n var source=c.duplicate(true)\n if key in Roster.ACTIVATIONS')
 s=s.replace('for c in p.field: c.damage=0; c.modifiers=[]; c.spell_damage=false; c.wards=[]; c.base_override={}; c.medicine=[]','for c in p.field: c.damage=0; c.modifiers=[]; c.spell_damage=false; c.wards=c.get("wards",[]).filter(func(w):return w.turn==-1); c.base_override={}; c.medicine=[]')
 s=s.replace(' var cost=Pack.cost(self,c,who,cards[c.card_id].cost,target)',' var cost=Pack.cost(self,c,who,cards[c.card_id].cost,target)\n var tax=Cat.target_tax(self,who,target)\n if tax>0:cost["红/蓝/绿/黄/黑"]=int(cost.get("红/蓝/绿/黄/黑",0))+tax')
 s=s.replace('if not payment_valid(who,Extra.activation_cost(key),plan):','if not payment_valid(who,extension_cost(who,c,key,target),plan):')
 s=s.replace('for reservation in plan:\n  if reservation.uid<0: players[who].potato=false\n  else: tap_card(find_card(reservation.uid))','Cat.pay(self,who,plan)')
 s=s.replace('func attack(who: int,uid: int,target: Dictionary={}):','func attack(who: int,uid: int,target: Dictionary={},plan: Array=[]):')
 s=s.replace(' tap_card(c); c.attacked=true',' var required=attack_cost(who)\n if plan.is_empty():plan=payment(who,required).plan\n if not payment_valid(who,required,plan):return\n Cat.pay(self,who,plan)\n tap_card(c); c.attacked=true',1)
 s=s.replace('and Cat.State.can_combat(self,c) and','and Cat.State.can_combat(self,c) and payment(who,attack_cost(who)).ways>0 and')
 s=s.replace(' if Pack.direct_attack(self,c) and not units(1-who).is_empty() and can_attack(who,c.uid):',' if (Pack.direct_attack(self,c) or units(1-who).any(func(u):return u.has("rank_target"))) and not units(1-who).is_empty() and can_attack(who,c.uid):')
 s=s.replace('  "main":\n   phase="end"','  "main":\n   if units(active).any(func(c):return c.get("madness",0)>0 and not c.attacked and can_attack(active,c.uid)):\n    priority=active;passes=0;note("仍有必须攻击的单位");return\n   phase="end"')
 s=s.replace('func ai_spell_target(who: int,c: Dictionary) -> Dictionary:\n','func ai_spell_target(who: int,c: Dictionary) -> Dictionary:\n if c.card_id=="character-fdf-046":return {"none":true,"mode":"不额外支付","extra_green":false}\n')
 s+='\nfunc attack_cost(who: int) -> Dictionary:\n var n=Cat.with_key(self,1-who,"spell-ucs-031").size()\n return {"红/蓝/绿/黄/黑":n} if n>0 else {}\nfunc extension_cost(who: int,c: Dictionary,key: String,target: Dictionary={}) -> Dictionary:\n var cost=Extra.activation_cost(key).duplicate();var tax=Cat.target_tax(self,who,target)\n if tax>0:cost["红/蓝/绿/黄/黑"]=int(cost.get("红/蓝/绿/黄/黑",0))+tax\n return cost\n'
 return s
edit('scripts/rules/duel_engine.gd',engine)
# Alias is explicit data, while the transformed version changes its actual name.
p=R/'cards/character-fdf-115.json';d=json.loads(p.read_text());d['别名']=['不明物体'];p.write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
