extends "res://tests/test_v011_rules.gd"
const Batch=preload("res://scripts/rules/mask_abilities.gd")
func stacked(id:String,owner:int=1,t:Dictionary={"player":0}) -> Dictionary:
 var c=e.make_card(id,owner,"stack");var s={"id":e.next_stack,"kind":"card","card":c,"owner":owner,"target":t,"name":e.cards[id].name};e.next_stack+=1;e.stack.append(s);return s
func run():
 var saved=FileAccess.get_file_as_string(Store.SAVE_PATH);var all=DB.load_cards()
 expect(all.size()==486 and DB.last_error.is_empty(),"486 definitions load")
 var new_ids=JSON.parse_string(FileAccess.get_file_as_string("res://work/v012/new-ids.json"))
 for id in new_ids:
  expect(all.has(id) and FileAccess.file_exists(all[id].image),"new database record "+id)
  expect(not all[id].abilities.is_empty(),"explicit executable effects "+id)
 for id in ["token-htk-031","token-htk-032","token-htk-033"]:expect(all[id].token and not all[id].constructible and all[id].kind=="道具","mask is nonconstructible item "+id)
 expect(all["token-htk-031"].colors==["黄"] and all["token-htk-032"].colors==["黑"] and all["token-htk-033"].colors==["蓝"],"mask colors from supplied art where token worksheet omits color")
 fresh();var a=put("character-fdn-068");roster_trigger(a,"lily_color",{"color":"红"});expect("红" in Pack.colors(e,a) and "黑" in Pack.colors(e,a),"Lily gains chosen color")
 fresh();var sanae=put("character-lof-003");a=put("50");Roster.plus(e,a,2);expect(a.plus_counters==3,"Sanae adds one counter to batch")
 Batch.counter(e,a,"courage",2,0);expect(a.courage==3,"Sanae modifies named courage counters")
 var b=put("50","field",1);put("character-lof-003","field",1);Roster.plus(e,b,1,0);expect(b.plus_counters==1,"opponent placement does not benefit opposing Sanae")
 Batch.color_counter(e,a,"蓝",0);expect(a.color_counters.count("蓝")==2,"color counters track multiplicity")
 resolve_spell("spell-lof-025",{"uid":a.uid,"epoch":a.epoch,"mode":"指示物翻倍"})
 expect(a.plus_counters==7 and a.courage==7 and a.color_counters.count("蓝")==5,"peach doubles each existing type then applies Sanae replacement")
 var hand=e.players[0].hand.size();resolve_spell("spell-lof-025",{"none":true,"mode":"回复并抓牌"});expect(e.players[0].life==23 and e.players[0].hand.size()==hand+1,"peach life draw mode")
 var palette=e.players[0].palette.size();resolve_spell("spell-lof-025",{"none":true,"mode":"牌库顶放入颜色盘"});expect(e.players[0].palette.size()==palette+1,"peach ramp mode")
 fresh();sanae=put("character-lof-003");sanae.leader_counters=1;a=put("9","hand");Roster.on_cast(e,a,0,"hand");expect(e.triggers.size()==1,"Sanae leader triggers on miracle cast")
 e.pump_choices();e.choose_effect({"selection_id":"sanae_miracle","picks":[[]]});settle();expect(e.players[0].hand.size()==2,"miracle draw survives zero optional unit targets")
 fresh();a=put("character-lof-001");act(a,"courage_ping",{"player":1});expect(a.tapped and a.courage==1 and e.players[1].life==19,"Cirno tap ping and courage")
 expect(not e.extension_activation_error(0,a,"courage_die").is_empty(),"nonleader cannot use Cirno self ability")
 a.leader_counters=1;a.courage=3;b=put("50","field",1);b.plus_counters=10;e.priority=0
 expect(e.commit_extension(0,a.uid,e.ref_target(b),[],"courage_die").is_empty(),"Cirno die ability commits")
 var die=e.stack.back().die;expect(a.courage==1 and die>=1 and die<=6,"two counters paid and one D6 stored on stack")
 settle();expect(b.damage==die and b.tapped,"D6 amount resolves without reroll")
 fresh();a=put("character-lof-001");a.courage=2;b=put("50","field",1);b.plus_counters=10;var other=put("51","field",1);other.plus_counters=10
 resolve_spell("spell-lof-007",selection("spell-lof-007",[[e.ref_target(b),e.ref_target(other)]]));expect(b.damage==3 and other.damage==3 and b.tapped and other.tapped,"icicle counts courage and hits both targets")
 fresh();a=put("character-lof-017");b=put("2");other=put("3");roster_trigger(a,"larva_sacrifice",e.ref_target(a))
 e.choose_effect(selected(e.pending.options,[[e.ref_target(b),e.ref_target(other)]]));expect(b.zone=="grave" and other.zone=="grave" and a.plus_counters==2,"Larva sacrifice and equal counters")
 fresh();a=put("character-htk-001");Roster.on_phase(e,"prepare");e.pump_choices();e.choose_effect({"player":1});one()
 expect(e.pending.owner==1 and e.pending.options.size()==3,"opponent chooses Kokoro first mood")
 e.choose_effect({"mode":"喜","none":true});expect(a.moods==["喜"] and e.players[0].field.any(func(u):return u.card_id=="token-htk-031"),"joy creates small mask")
 a.leader_counters=1;roster_trigger(a,"kokoro_mood",{"player":1});expect(e.pending.owner==0 and e.pending.options.size()==2,"Kokoro self replacement and no repeated mood")
 e.choose_effect({"mode":"怒","none":true});roster_trigger(a,"kokoro_mood",{"player":1});e.choose_effect({"mode":"忧","none":true});e.triggers.clear();Roster.on_phase(e,"prepare");expect(e.triggers.is_empty(),"three exhausted moods cause no impossible prompt")
 fresh();a=Batch.mask(e,0,"031");b=put("50");b.tapped=true;act(a,"mask_joy",e.ref_target(b));expect(a.zone=="void" and not b.tapped,"joy sacrifices token and resets target")
 e.damage_target(e.ref_target(b),20);expect(b.damage==0,"joy prevents all turn damage")
 a=Batch.mask(e,0,"032");var spirit=e.stat(b,"spirit");act(a,"mask_anger",e.ref_target(b));expect(e.stat(b,"spirit")==spirit+2 and e.Extra.keyword(e,b,"歼灭"),"anger grants spirit and annihilate")
 a=Batch.mask(e,0,"033");var p=put("164","palette",1);var q=put("167","palette",1)
 act(a,"mask_sorrow",selected(Batch.activation_options(e,a,"mask_sorrow"),[[Pack.ref(e,p),Pack.ref(e,q)]],1));expect(p.tapped and q.tapped and e.players[0].hand.size()==1,"sorrow taps chosen opponent palette and draws")
 fresh();a=put("character-htk-001");resolve_spell("spell-fdf-083",{"player":1});expect(e.players[0].field.filter(func(u):return u.card_id=="token-htk-032").size()==2 and e.players[1].life==16,"angry mask doubles token creation and damage with Kokoro")
 fresh();var s=stacked("99");resolve_spell("spell-fdn-066",{"stack_id":s.id});expect(s.rewritten_fairy and s.target=={"none":true},"fairy pilgrimage rewrites pending spell")
 one();expect(e.players[0].life==20 and e.units(1).size()==1 and e.stat(e.units(1)[0],"spirit")==3 and e.field_slots(1)==0,"rewritten spell creates 3/3/3 fairy for its controller instead of damage")
 fresh();s=stacked("99");resolve_spell("spell-fdn-069",{"stack_id":s.id});expect(e.stack.is_empty() and e.players[1].deck[2].uid==s.card.uid,"blue flower removes stack card and inserts third")
 fresh();e.players[1].deck.clear();s=stacked("99");resolve_spell("spell-fdn-069",{"stack_id":s.id});expect(e.players[1].deck[0].uid==s.card.uid,"blue flower short library fallback")
 fresh();mana();a=cast_new("spell-htk-018");expect(a.zone=="field" and a.timer==2,"night sakura enters with two time counters")
 b=put("50","grave");Roster.on_phase(e,"end");e.pump_choices();e.choose_effect(Pack.ref(e,b));settle();expect(b.zone=="field","night sakura resurrects selected grave unit")
 a.timer=0;e.judge();expect(a.zone=="grave","time spell expires at zero")
 fresh();a=put("character-htk-002");a.leader_counters=1;b=put("164","hand");expect(e.payment(0,e.cast_cost(0,b)).plan.is_empty() and e.payment(0,e.cast_cost(0,b)).ways>0,"Tokiko discounts first item by two")
 expect(e.commit_cast(0,b.uid,{},[]).is_empty(),"first item may be cast with no resources");settle();var second=put("164","hand");expect(e.cast_cost(0,second).get("黄",0)==2,"discount consumed by first cast")
 act(a,"tokiko_copy",Pack.ref(e,b));var copy=e.players[0].field.filter(func(u):return u.token)[0]
 expect(e.cards[copy.card_id].copy_source_id=="164" and e.source_resources(0).any(func(r):return r.uid==copy.uid),"copied item preserves art and mana ability")
 e.run_delayed("end");settle();expect(copy.zone=="void","item copy sacrificed at next end")
 fresh();a=put("character-fdn-067");b=put("character-lof-001","field",1);e.priority=1
 expect(not e.extension_activation_error(1,b,"courage_ping").is_empty(),"Toyohime prohibits opponent unit activation off-turn")
 var m=Batch.mask(e,1,"032");expect(e.extension_activation_error(1,m,"mask_anger").is_empty(),"Toyohime leaves item activation legal")
 e.active=1;expect(e.extension_activation_error(1,b,"courage_ping").is_empty(),"unit activation legal on controller turn")
 expect(Pack.fast(e,a,0) and e.Extra.keyword(e,a,"退治") and e.Extra.keyword(e,a,"追击"),"Toyohime flash and combat keywords")
 fresh();a=put("character-ucs-007");e.damage_target(e.ref_target(a),5);expect(a.damage==0,"Sannyo prevents noncombat damage")
 b=put("50","field",1);e.combat_hit(b,e.ref_target(a),1);expect(a.damage==1,"Sannyo still receives combat damage")
 fresh();put("164");put("167");b=put("50","grave");var options=e.targets_for("spell-htk-003",0)
 var target=selected(options,[[{"player":1,"mode":"造成1点伤害"}],[{"player":1,"mode":"造成1点伤害"}]])
 expect(Pack.choice_valid(e,options,target),"emotion modes allow repeated identical targets")
 resolve_spell("spell-htk-003",target);expect(e.players[1].life==18,"repeated damage modes resolve in order")
 options=e.targets_for("spell-htk-003",0);var recover=Pack.ref(e,b);recover.mode="移回手牌"
 resolve_spell("spell-htk-003",selected(options,[[recover],[]]));expect(b.zone=="hand","emotion recovery returns chosen unit")
 fresh();put("164");put("167");s=stacked("99");p=put("164","palette",1)
 target=selected(e.targets_for("spell-htk-003",0),[[{"stack_id":s.id,"mode":"反制，除非支付1点"}],[{"player":1,"mode":"造成1点伤害"}]])
 resolve_spell("spell-htk-003",target);expect(e.pending.owner==1,"tax choice belongs to original spell controller")
 var pay=e.pending.options.filter(func(t):return t.get("uid",-1)==p.uid)[0];e.choose_effect(pay)
 expect(p.tapped and e.stack.size()==1 and e.players[1].life==19,"paid tax preserves spell and resumes remaining modes")
 fresh();put("164");s=stacked("99");resolve_spell("spell-htk-003",selected(e.targets_for("spell-htk-003",0),[[{"stack_id":s.id,"mode":"反制，除非支付1点"}]]))
 e.choose_effect({"none":true,"mode":"不支付"});expect(e.stack.is_empty() and s.card.zone=="grave","declining emotion tax counters pending card")
 expect(FileAccess.get_file_as_string(Store.SAVE_PATH)==saved,"saved decks unchanged")
 print("V012_RULES: %d checks; %d failures" % [checks,failures.size()]);quit(0 if failures.is_empty() else 1)
