extends "res://tests/test_v0181_series.gd"
func run():
 var real_decks=Store.load_decks().decks
 Store.Paths.root_override=ProjectSettings.globalize_path("res://work/bugs0921-network/"+str(Time.get_ticks_usec()))
 var custom=real_decks[0].duplicate(true);custom.name="朋友自组-中文名称";custom.id="not-in-host-deck-list"
 check(Store.save_file(custom).is_empty(),"外部自组卡组独立保存")
 custom=Store.read_file(Store.file_paths[custom.id]).deck
 check(Store.validate(custom,true).is_empty() and custom.main.size()==50,"导入卡组50主牌+独立自机通过严格检查")
 host=Session.new();guest=Session.new();root.add_child(host);root.add_child(guest)
 host.initialize(Store.Paths.root().path_join("host"));guest.initialize(Store.Paths.root().path_join("guest"))
 var errors=[];guest.error_raised.connect(func(message):errors.append(message))
 check(host.create_room(3,true,47987,"127.0.0.1").is_empty(),"严格BO3房间开启")
 guest.join_room("127.0.0.1",47987)
 check(await until(func():return not host.applicant.is_empty()),"自组卡组客机申请加入")
 check(await until(func():return guest.join_stage=="approval"),"客机明确显示等待房主接受")
 host.accept_applicant(true);check(await until(func():return host.can_act() and guest.can_act()),"两端连接完成")
 host.room_action({"name":"deck","deck":real_decks[-1]})
 check(await until(func():return host.can_act() and guest.can_act()),"房主牌组提交确认")
 guest.room_action({"name":"deck","deck":custom})
 check(await until(func():return guest.can_act() and host.series.state.decks[1].get("id")==custom.id),"真实ENet传输客机自组卡组，不依赖房主本地ID")
 check(host.series.state.decks[1]==custom and guest.room.own_deck==custom,"两端主牌备牌自机内容一致")
 await prepare()
 check(host.authority.players[1].deck.size()+host.authority.players[1].hand.size()==50,"对局初始化主牌50不含自机")
 check(host.authority.players[1].leader.card_id==custom.leader,"自机在独立区域正确生成")
 check(errors.is_empty(),"完整导入加入开局流程无错误")
 await concede(0)
 var invalid=custom.duplicate(true);invalid.main.append(invalid.main[0])
 guest.room_action({"name":"deck","deck":invalid})
 check(await until(func():return not errors.is_empty() and guest.can_act()),"非法51主牌明确返回错误且客机不锁死")
 check("主卡组需要 50 张" in errors.back(),"错误内容明确区分主卡组和自机")
 host.leave();guest.leave();await process_frame
 host.create_room(3,true,47987,"127.0.0.1");guest.fingerprint="different-build";errors.clear();guest.join_room("127.0.0.1",47987)
 check(await until(func():return guest.rejected and not errors.is_empty()),"不同规则版本的入房拒绝送达客机")
 check("版本不一致" in errors.back() and "pck" in errors.back(),"拒绝说明两端完整发行包须相同")
 host.leave();guest.leave();errors.clear();guest.join_room("127.0.0.1",47998)
 guest.check_join_timeout(guest.remote_last_seen+12001)
 check(guest.rejected and not guest.joining and not errors.is_empty() and "无法连接房主" in errors.back(),"初次连接超时明确提示地址及网络问题，不无限等待")
 host.leave();guest.leave();host.queue_free();guest.queue_free();await process_frame
 print("BUGS0921 NETWORK ",checks," checks; ",failures," failures")
 quit(0 if failures.is_empty() else 1)
