extends "res://tests/test_v09_rules.gd"
const Pack=preload("res://scripts/rules/precon_abilities.gd")
const Picker=preload("res://scripts/target_picker.gd")
func settle():
 for i in range(160):
  if e.winner!=-2: return
  e.pump_choices()
  if not e.pending.is_empty():
   match e.pending.kind:
    "trigger_order": e.choose_trigger_order(0)
    "effect_choice": e.choose_effect(Pack.ai_target(e,e.pending.owner,e.pending.options,e.pending.trigger.effect))
    "leader_return": e.choose_return(false)
    "trigger": e.choose_trigger({})
    "timer": e.choose_timer(0)
    _: return
  elif not e.stack.is_empty(): one()
  else: return
 expect(false,"settlement finished without looping")
func selected(options: Array,picks: Array,index: int=0) -> Dictionary:
 return {"selection_id":options[index].selection_id,"picks":picks}
func trigger(c: Dictionary,key: String,target: Dictionary={"none":true},data: Dictionary={}):
 Pack.resolve_trigger(e,{"precon":true,"source":c.duplicate(true),"effect":key,"owner":c.owner,"target":target,"data":data,"optional":false})
func cast_new(id: String,target: Dictionary={}) -> Dictionary:
 var c=put(id,"hand"); var options=e.targets_for(id,0)
 if target.is_empty(): target=Pack.ai_target(e,0,options,Pack.key(e.cards[id],Pack.SPELLS)) if not options.is_empty() else {}
 var error=e.commit_cast(0,c.uid,target,e.payment(0,e.cast_cost(0,c,target)).plan)
 expect(error.is_empty(),"cast "+id+" "+error)
 settle(); e.priority=0
 return c
func activate(c: Dictionary,t: Dictionary):
 var k=e.Extra.activation_kind(e.cards[c.card_id]); e.priority=c.owner
 var error=e.commit_extension(c.owner,c.uid,t,e.payment(c.owner,e.Extra.activation_cost(k)).plan)
 expect(error.is_empty(),"activate "+k+" "+error); settle(); e.priority=0
func spell_context(c: Dictionary,single: bool=true): e.damage_context={"source":c,"single":single,"combat":false}
func run():
 var saved=FileAccess.get_file_as_string(Store.SAVE_PATH)
 var cards=DB.load_cards()
 expect(cards.size()>=132 and cards.values().filter(func(c):return c.get("token",false)).size()>=8,"original pool and eight unconstructible tokens remain available")
 var templates=JSON.parse_string(FileAccess.get_file_as_string("res://data/test_precons.json")).decks
 for deck in templates:
  expect(Store.validate(deck,true).is_empty(),deck.name+" passes strict 50+1 validation")
  expect(deck.main.size()==50 and deck.side.is_empty() and deck.main.all(func(id): return cards[id].constructible),deck.name+" excludes all tokens")
 expect(templates[0].main.count("spell-rei-011")==3 and templates[0].main.count("170")==1,"photo's three Dream Orbs and one Hakurei Shrine preserved")
 var limited=templates[1].duplicate(true); limited.main[0]="spell-mar-004"
 expect(not Store.validate(limited,true).is_empty(),"limited spells reject a third copy")
 expect(cards["character-rei-001"].kind=="自机" and "退治" in cards["character-rei-001"].rules_text,"Reimu leader ability restored from supplied art")
 expect(cards["token-fdf-133"].power==2 and "吸血1" in cards["token-fdf-133"].keywords,"vampire token uses actual supplied 2/2 art and lifesteal")
 # Dynamic choices are bounded; no permutation expansion even with many fields.
 fresh(); var a=put("character-rei-001"); mana()
 for i in range(12): put("170")
 var options=e.targets_for("spell-rei-002",0)
 expect(options.size()==1 and options[0].selection[0].max==12,"spread targets use a linear selection descriptor")
 var picker=Picker.new(); picker.configure(options,"spread")
 expect(not picker.ready() and picker.select_target({"player":1}),"dynamic picker starts private and can choose player")
 expect(not picker.select_target({"player":1}),"duplicate target forbidden")
 picker.select(picker.available().filter(func(x): return x.kind=="finish_group")[0])
 expect(picker.ready() and Pack.choice_valid(e,options,picker.option()),"early finish produces a valid selected target list")
 # All-colors in field/palette, cost flexibility, support, Iku flash.
 fresh(); var lily=put("character-soi-006","palette")
 expect(e.source_resources(0)[0].colors.size()==5,"Lily provides all five colors in palette")
 var spring=put("spell-mar-013","hand")
 expect(e.cast_cost(0,spring)=={"红/蓝/绿/黄/黑":1},"chromatic Spring accepts any one color")
 var patch=put("character-mar-ex01"); patch.leader_counters=1
 var spell=put("99","hand"); expect(e.cast_cost(0,spell)=={"红/蓝/绿/黄/黑":3},"active Patchouli leader grants chromatic spell costs")
 patch.leader_counters=0; expect(e.cast_cost(0,spell)!= {"红/蓝/绿/黄/黑":3},"ordinary Patchouli copy has no leader aura")
 fresh(); mana(); e.players[0].leader.card_id="character-mar-ex"
 spell=put("spell-fdf-023","hand"); e.active=1; e.phase="prepare"
 expect(e.cast_error(0,spell.uid).is_empty(),"Meteor support works with Marisa still in leader zone")
 var slow=put("spell-rei-006","hand"); expect(not e.cast_error(0,slow.uid).is_empty(),"ordinary non-symbol spell is not fast")
 put("character-mar-024"); expect(e.cast_error(0,slow.uid).is_empty(),"Iku grants fast timing without ignoring costs")
 fresh(); mana(); a=put("character-rei-001"); a.leader_counters=1
 for i in range(3): put("spell-rei-011","palette")
 expect(e.has_haste(a) and e.Extra.keyword(e,a,"退治"),"Reimu self ability grants exterminate and conditional haste")
 var ordinary=put("character-rei-017"); expect(e.Extra.keyword(e,ordinary,"退治") and Pack.fast(e,ordinary,0),"small-path Reimu has unconditional exterminate and flash")
 # Basic spells and conditional costs.
 fresh(); mana(); var before=e.players[0].palette.size(); cast_new("spell-soi-098")
 expect(e.players[0].palette.size()==before+1 and e.players[0].palette.back().tapped,"Human/God ramp enters tapped")
 cast_new("spell-rei-015"); expect(e.players[0].palette.size()==before+3,"Mountain River ramps two")
 fresh(); mana(); put("70"); put("68"); spell=put("spell-rei-006","hand")
 expect(e.cast_cost(0,spell).get("黄",0)==0,"Promise discounts exactly two differently named leader units")
 e.commit_cast(0,spell.uid,{"none":true},e.payment(0,e.cast_cost(0,spell)).plan); settle()
 expect(e.players[0].hand.size()==3,"Promise draws three")
 fresh(); mana(); put("68"); put("field-mar-006"); spell=put("spell-mar-002","hand")
 expect(e.cast_cost(0,spell).get("黄")==4,"shop applies Master Spark alias reduction")
 a=put("54","field",1); a.modifiers=[{"血量":8}]
 options=e.targets_for(spell.card_id,0); var target=selected(options,[[e.ref_target(a),{"player":1}]])
 expect(e.commit_cast(0,spell.uid,target,e.payment(0,e.cast_cost(0,spell)).plan).is_empty(),"Double Spark declares two targets")
 settle(); expect(a.damage==6 and e.players[1].life==14,"Double Spark deals six to each distinct target")
 fresh(); mana(); put("70"); a=put("54","field",1); put("170"); put("170")
 options=e.targets_for("spell-rei-002",0); cast_new("spell-rei-002",selected(options,[[{"player":1},e.ref_target(a)]]))
 expect(e.players[1].life==19 and a.damage==2,"Spread damage follows chosen order 1 then 2")
 fresh(); mana(); a=put("70"); a.plus_counters=1; var b=put("54","field",1)
 cast_new("spell-fdf-011"); expect(e.stat(a,"power")==5 and e.stat(b,"health")==2,"barrier replaces base stats before applying counters")
 fresh(); mana(); a=put("70"); cast_new("spell-rei-010",e.ref_target(a))
 expect(e.stat(a,"spirit")==6 and e.players[0].life==26,"Yin Yang adds four spirit and heals Reimu's resulting spirit")
 fresh(); mana(); put("70"); put("spell-rei-011","palette"); put("99","palette",1); b=put("54","field",1)
 cast_new("spell-rei-011",e.ref_target(b)); expect(b.zone=="field" and b.damage==4,"Dream Orbs counts role spells in both palettes")
 fresh(); mana(); b=put("54","field",1); cast_new("spell-fdf-054",{"uid":b.uid,"epoch":b.epoch,"mode":"造成1点伤害，抓1张牌"})
 expect(b.damage==1 and e.players[0].hand.size()==1,"Cloud mode damage plus draw")
 fresh(); mana(); put("68"); put("spell-mar-012","grave"); cast_new("spell-mar-012",selected(e.targets_for("spell-mar-012",0),[[{"player":1}]]))
 expect(e.players[1].life==19 and e.players[0].hand.size()==2,"Shoot Moon counts prior grave copies only")
 fresh(); mana(); a=put("53"); cast_new("spell-mar-013",{"uid":a.uid,"epoch":a.epoch,"color":"黑"})
 expect("黑" in Pack.colors(e,a) and e.players[0].hand.size()==1,"Spring adds persistent color counter and draws")
 fresh(); mana(); put("68"); a=put("53"); b=put("character-fdf-116","field",1); var four=put("54")
 cast_new("spell-fdf-036"); expect(a.zone=="grave" and b.zone=="grave" and four.damage==0,"Stardust distinguishes costs below, above, and exactly four")
 fresh(); mana(); put("70"); var palette=[]
 for i in range(4): palette.append(put("164","palette",1))
 options=e.targets_for("spell-fdf-007",0); cast_new("spell-fdf-007",selected(options,[[Pack.ref(e,palette[0]),Pack.ref(e,palette[1]),Pack.ref(e,palette[2])]]))
 expect(e.players[1].palette.size()==1 and e.players[1].grave.size()==3,"Eight-way circle removes exactly three selected palette cards")
 # Counters, payment privacy, and unrespondable spell.
 fresh(); mana(); put("70"); b=put("53","hand",1); e.shift(b,"stack"); e.players[1].hand.erase(b)
 e.stack.append({"id":77,"kind":"card","card":b,"owner":1,"name":e.cards[b.card_id].name,"target":{}})
 cast_new("spell-rei-012",{"stack_id":77}); expect(b.zone=="grave","Scatter seal counters only cost three or less")
 fresh(); mana(); e.players[0].leader.card_id="70"; var shown=put("100","hand"); b=e.make_card("164",1,"stack")
 e.stack.append({"id":77,"kind":"card","card":b,"owner":1,"name":e.cards[b.card_id].name,"target":{}})
 options=e.targets_for("spell-mar-007",0); cast_new("spell-mar-007",selected(options,[[Pack.ref(e,shown)],[{"stack_id":77}]]))
 expect(shown.zone=="hand" and b.zone=="grave","Spirit Strike reveals a matching role spell without discarding it")
 fresh(); mana(); put("68"); spell=put("spell-mar-004","hand"); e.Pack.shield(e,{"player":1},[999])
 expect(e.commit_cast(0,spell.uid,{"player":1},e.payment(0,e.cast_cost(0,spell)).plan).is_empty(),"silent spark is cast normally")
 var response=put("100","hand",1); expect(not e.cast_error(1,response.uid).is_empty() and not e.has_response(1),"silent spell prevents responses while on stack")
 one(); expect(e.players[1].life==15 and e.unpreventable_turn==e.turn,"silent spark disables prevention for the turn")
 # Shields consume independently, and damage source context controls furnace.
 fresh(); mana(); put("68"); a=put("54"); cast_new("spell-fdf-019",e.ref_target(a))
 expect(a.wards.size()==2,"new Escape Velocity art grants two independent prevent-three shields")
 e.damage_target(e.ref_target(a),2); expect(a.damage==0 and a.wards.size()==1,"small damage consumes only first shield")
 e.damage_target(e.ref_target(a),5); expect(a.damage==2 and a.wards.is_empty(),"next damage consumes remaining shield")
 fresh(); a=put("character-fdf-070"); activate(a,{"player":0})
 expect(a.zone=="grave" and e.players[0].wards.size()==5,"Letty sacrifices for five independent prevention instances")
 e.damage_target({"player":0},3); expect(e.players[0].life==20 and e.players[0].wards.size()==2,"three damage consumes three prevent-one abilities")
 fresh(); put("item-mar-017"); a=put("53"); spell_context(a); e.damage_target({"player":1},2)
 expect(e.players[1].life==17,"furnace increases a unit's single-target noncombat damage")
 spell_context(a,false); e.damage_target({"player":1},2); expect(e.players[1].life==15,"furnace does not increase a multiple-target damage effect")
 e.combat_hit(a,{"player":1},2); expect(e.players[1].life==13,"furnace never increases combat damage")
 fresh(); mana(); a=put("70"); cast_new("spell-mar-014"); e.damage_target(e.ref_target(a),5)
 expect(a.damage==0,"Paranoid Lost prevents noncombat damage to self-unit category")
 e.combat_hit(put("53","field",1),e.ref_target(a),1); expect(a.damage==1,"Paranoid does not prevent combat damage")
 # Enter triggers, searching and complete resolution choices.
 fresh(); a=enter("character-soi-018"); settle(); expect(e.players[0].palette.size()==1 and e.players[0].palette[0].tapped,"Yuuka enter ramps tapped")
 fresh(); mana(); a=enter("character-rei-007"); settle(); expect(a.plus_counters==2,"explorer checks eight palette cards and gains two counters")
 fresh(); a=put("53"); b=enter("character-rec-096"); settle(); expect(a.plus_counters==1 and b.plus_counters==1,"Tewi can enhance herself and other own units")
 fresh(); b=put("170","field",1); a=enter("character-rec-104"); settle(); expect(b.zone=="grave","Kosuzu can destroy opposing fields")
 fresh(); e.active=1; a=enter("character-rei-022"); settle()
 expect(a.get("wards",[]).size()+e.players[0].get("wards",[]).size()==1,"Shou's opponent-turn enter offers next damage prevention")
 fresh(); a=enter("character-rei-022"); settle(); expect(a.get("wards",[]).is_empty(),"Shou has no enter shield on own turn")
 fresh(); b=put("99","grave"); a=enter("character-fdf-116"); settle(); expect(b.zone=="hand","Eirin enters and returns a grave spell")
 fresh(); e.players[0].deck=[]; var search=put("99","deck"); a=enter("character-mar-ex"); settle()
 expect(search.zone=="hand" and e.pending.is_empty(),"Marisa search resolves through region selection without extra priority")
 fresh(); e.players[0].deck=[]; search=put("164","deck"); a=enter("character-mar-025"); settle()
 expect(search.zone=="hand","Tokiko searches a cost-two artifact")
 fresh(); a=put("53"); b=enter("field-rei-005"); e.choose_effect(e.ref_target(a)); settle(); e.tap_card(a); e.start_turn(0)
 expect(a.tapped,"binding field prevents reset while source remains")
 e.move_to(b,"grave"); e.start_turn(0); expect(not a.tapped,"binding reset lock ends when its source leaves")
 fresh(); a=put("53","field",1); b=enter("field-smm-004"); settle()
 expect(a.zone=="exile","Shining Castle temporarily exiles a non-self unit")
 e.move_to(b,"grave"); expect(a.zone=="field" and a.owner==1,"Castle returns its linked card under original owner")
 fresh(); a=put("53","field",1); b=enter("character-fdf-ex02"); settle(); expect(a.zone=="exile","Yukari enter may target opponent units")
 e.start_turn(0); settle(); expect(a.zone=="field" and a.owner==1,"Yukari returns at controller's next prepare")
 fresh(); a=put("character-fdf-ex02"); a.leader_counters=1; b=put("53"); mana(); activate(a,e.ref_target(b))
 expect(b.zone=="exile" and not e.extension_activation_error(0,a).is_empty(),"Yukari active blink is limited to once per turn")
 fresh(); a=enter("character-rei-ex01"); settle(); var n=e.players[0].hand.size(); e.move_to(a,"grave"); settle()
 expect(e.players[0].hand.size()==n+2,"Larva draws twice on death alongside crystal")
 fresh(); a=put("character-rei-023"); b=put("164","palette"); b.tapped=true; activate(a,Pack.ref(e,b))
 expect(a.tapped and not b.tapped,"Minoriko taps to reset palette")
 # End/prepare triggers and multi-stage swaps.
 fresh(); a=put("character-rei-026"); e.advance_phase(); settle(); expect(a.plus_counters==1,"Sanae adds a counter at end phase")
 fresh(); a=put("character-mar-020"); b=put("164"); a.tapped=true; b.tapped=true
 e.advance_phase(); settle(); expect(not a.tapped and not b.tapped,"experimental Marisa untaps up to two permanents")
 fresh(); a=put("character-mar-021"); b=put("53","hand"); var p=put("164","palette")
 e.advance_phase(); settle(); expect(b.zone=="palette" and p.zone=="hand","Patchouli swaps hand and palette during end resolution")
 fresh(); a=put("spell-fdf-054","hand"); b=enter("character-mar-022"); settle()
 expect(a.zone=="exile" and e.cast_cost(0,a).is_empty(),"Seiran stores a small blue spell for free future use")
 e.phase="main"; e.priority=0; var enemy=put("54","field",1)
 expect(e.commit_cast(0,a.uid,{"uid":enemy.uid,"epoch":enemy.epoch,"mode":"造成2点伤害"},[]).is_empty(),"Seiran spell can be cast from exile")
 settle(); expect(enemy.damage==2 and a.zone=="grave","free exiled spell resolves and loses its permission")
 fresh(); p=put("164","palette"); b=enter("character-mar-023"); settle()
 expect(p.zone=="grave" and e.players[0].palette.size()==1 and not e.players[0].palette[0].tapped,"Koakuma replaces selected palette with untapped top card")
 fresh(); put("99","hand"); put("53","hand"); b=enter("character-fdf-099"); settle()
 expect(e.players[0].hand.size()==3 and e.players[0].palette.is_empty(),"Mike puts in two, returns two, and draws for role spell")
 fresh(); e.players[0].deck=[]; put("53","deck"); var chosen=put("99","deck"); put("164","deck"); b=enter("character-mar-ex01"); settle()
 expect(chosen.zone=="hand" and e.players[0].deck.size()==2,"Seven-day Patchouli reveals top three and randomizes unchosen bottom cards")
 fresh(); a=put("character-fdf-095"); e.start_turn(0); settle()
 var wines=e.players[0].field.filter(func(c): return c.card_id=="token-fdf-128")
 expect(wines.size()==1 and wines[0].token,"Miyoi creates a real temporary artifact instance during prepare")
 activate(wines[0],{"color":"黄"}); spell=put("99","hand")
 expect(e.cast_cost(0,spell).get("黄")==2 and wines[0].zone=="void","wine vanishes after sacrifice and discounts next role spell")
 # Timed card abilities remain on stack after removing the last timer.
 fresh(); mana(); put("68"); a=cast_new("spell-mar-003")
 expect(a.zone=="field" and a.timer==4,"Laser resolves as time spell with four counters")
 a.timer=1; b=put("170","field",1); activate(a,{"uid":b.uid,"epoch":b.epoch,"zone":"field","mode":"消灭结界或道具"})
 expect(a.zone=="grave" and b.zone=="grave","last Laser timer sends source to grave while ability still resolves")
 fresh(); mana(); put("68"); a=cast_new("spell-mar-003"); activate(a,{"player":0,"mode":"防避4"})
 expect(a.timer==3 and e.players[0].wards.size()==1,"Laser prevention mode pays yellow and a timer")
 # Activated costs, counters, and source snapshots.
 fresh(); a=put("field-rei-003"); put("70"); e.stack.append({"id":77,"kind":"ability","activation":true,"source":put("53","field",1).duplicate(true),"effect":"exile_grave","target":{},"owner":1,"name":"ability"})
 activate(a,{"stack_id":77}); expect(a.zone=="grave" and e.players[0].hand.size()==1,"Watch circle sacrifices, counters active ability and optionally draws")
 fresh(); a=put("field-rei-004"); b=put("54","field",1); e.tap_card(b); b.tapped=false
 activate(a,e.ref_target(b)); expect(b.zone=="field" and b.damage==4,"Standing circle remembers earlier tap even after untap")
 fresh(); a=put("character-mar-ex"); a.leader_counters=1
 var costs=[put("spell-rei-006","grave"),put("spell-fdf-054","grave"),put("100","grave")]; var recovered=put("99","grave")
 options=Pack.activation_options(e,a,"marisa_recover")
 var pool=options[0].selection[0].pool; target=selected(options,[[pool[0],pool[1],pool[2]],[options[0].selection[1].pool[0]]])
 activate(a,target); expect(recovered.zone=="hand" and costs.all(func(c): return c.zone=="exile"),"Marisa exiles three different names as a cost and recovers Spark")
 fresh(); a=put("character-fdf-ex05"); a.leader_counters=1; b=put("53"); e.players[1].deck=[]; var stolen=put("164","deck",1)
 options=Pack.activation_options(e,a,"keine_devour"); activate(a,selected(options,[[e.ref_target(b)]]))
 expect(b.zone=="grave" and stolen.zone=="exile" and Pack.cast_from(e,stolen,0),"Keine sacrifice exiles opposing top card with her permission")
 mana(); e.priority=0; expect(e.commit_cast(0,stolen.uid,{},e.payment(0,e.cast_cost(0,stolen)).plan).is_empty(),"Keine can use opponent-owned exiled card")
 settle(); expect(stolen.zone=="field" and stolen.owner==0 and stolen.original_owner==1,"stolen permanent is controlled by caster, retains original ownership")
 e.move_to(stolen,"grave"); expect(stolen.owner==1 and stolen in e.players[1].grave,"stolen permanent returns to owner's grave")
 fresh(); mana(); put("character-soi-006"); a=cast_new("character-fdf-ex03",{"none":true,"x":3,"mode":"X = 3"})
 expect(a.plus_counters==3 and e.stat(a,"power")==5 and e.players[0].life==23,"Byakuren X is paid, enters with counters, and gains X life")
 # Triggered damage, pursuit and direct attack.
 fresh(); a=put("character-fdf-ex04"); a.leader_counters=1; b=put("54","field",1)
 e.tap_card(b); e.pump_choices(); settle(); expect(b.damage==1,"Tenshi leader triggers once when opponent unit becomes tapped")
 fresh(); a=put("character-ucs-060"); a.tapped=true; e.combat_hit(a,{"player":1},2); e.pump_choices(); settle()
 expect(not a.tapped,"pursuit resets after first own-turn combat damage")
 a.tapped=true; e.combat_hit(a,{"player":1},2); e.pump_choices(); settle(); expect(a.tapped,"pursuit does not reset twice in one turn")
 fresh(); a=put("token-fdf-130"); e.attack(0,a.uid); settle(); expect(a.plus_counters==2,"Oni attack trigger adds two counters before combat")
 fresh(); a=put("token-fdf-133"); e.combat_hit(a,{"player":1},2)
 expect(e.players[0].life==21 and e.field_slots(0)==0,"vampire token lifesteal and no battlefield slot")
 fresh(); a=put("token-fdn-085"); e.judge(); expect(a.zone=="void","illusion token vanishes without a Reisen-named unit")
 fresh(); a=put("character-fdf-ex01"); a.leader_counters=1; b=put("54","field",1)
 e.attack(0,a.uid,e.ref_target(b)); expect(e.combat.get("direct",false) and a.skip_reset,"Flandre can declare direct unit attack")
 one(); expect(e.pending.is_empty() and e.combat.step=="block_window","direct attack never asks for other blockers")
 e.combat={}; e.start_turn(0); expect(a.tapped and not a.skip_reset,"direct attack skips exactly next own reset")
 # Rain aura, life-triggered anthem and Eirin's cast-trigger medicine.
 fresh(); a=put("53"); b=put("field-fdn-016"); expect(e.stat(a,"power")==3 and e.Extra.keyword(e,a,"英勇"),"rain field grants stats and brave dynamically")
 e.move_to(b,"grave"); expect(e.stat(a,"power")==2 and not e.Extra.keyword(e,a,"英勇"),"rain benefits end when source leaves")
 fresh(); mana(); a=put("character-fdf-116","hand"); a.leader_counters=1; put("character-soi-006")
 # Use actual designated commander identity for the on-cast self ability.
 e.players[0].hand.erase(a); e.players[0].leader.card_id=a.card_id; a=e.players[0].leader
 expect(e.commit_cast(0,a.uid,{},e.payment(0,e.cast_cost(0,a)).plan).is_empty(),"Eirin cast succeeds with leader color constraint")
 settle(); var medicines=e.players[0].field.filter(func(c): return c.card_id=="token-ucs-093")
 expect(medicines.size()==1,"Eirin creates medicine on cast")
 b=put("53"); activate(medicines[0],e.ref_target(b)); e.move_to(b,"grave"); settle()
 expect(b.zone=="field" and medicines[0].zone=="void","medicine sacrifices and returns protected unit after death")
 fresh(); a=put("spell-fdf-ex05"); b=put("70","grave"); e.gain_life(0,1); e.pump_choices(); settle()
 expect(b.zone=="field","scarlet anthem returns a human when life is gained on own turn")
 fresh(); a=put("field-fdf-108"); e.damage_target({"player":0},3); e.pump_choices()
 expect(e.stack.size()==1 and e.stack[0].effect=="old_city_heal","old city queues a coin flip after damage of at least three")
 # A response can change the number of fields before Spread resolves.
 fresh(); mana(); put("character-rei-001"); a=put("170"); b=put("170"); var victim=put("54","field",1)
 spell=put("spell-rei-002","hand")
 target={"selection_id":"spread_damage","picks":[[e.ref_target(victim),{"player":1}]]}
 expect(e.commit_cast(0,spell.uid,target,e.payment(0,e.cast_cost(0,spell)).plan).is_empty(),"Spread commits two targets before a response removes a field")
 e.move_to(a,"grave"); e.move_to(victim,"exile")
 settle()
 expect(e.players[1].life==20,"Spread rechecks field count and never renumbers a vanished first target")
 fresh(); mana(); put("character-rei-001"); a=put("170"); spell=put("spell-rei-002","hand")
 target={"selection_id":"spread_damage","picks":[[{"player":1}]]}
 expect(e.commit_cast(0,spell.uid,target,e.payment(0,e.cast_cost(0,spell)).plan).is_empty(),"Spread commits before a response removes its final field")
 e.move_to(a,"grave"); settle()
 expect(e.players[1].life==20,"Spread deals no damage if its last field is removed in response")
 expect(Pack.single_damage_target({"effect":"enter_grave_damage","target":{"parts":[{"uid":10,"zone":"grave"},{"player":1}]}}),"recovery choice does not hide the single damage target from furnace")
 fresh(); a=put("spell-mar-003"); a.timer=0;var sakuya=put("75");sakuya.leader_counters=1
 e.add_timer(a,1);e.pump_choices();e.choose_timer(-1)
 expect(a.zone=="grave","timer replacement reaching zero performs state-based removal immediately")
 fresh(); e.stack.append({"id":77,"owner":0})
 expect(Pack.ai_target(e,0,[{"stack_id":77}],"counter_three").is_empty(),"AI declines to counter its own spell")
 expect(FileAccess.get_file_as_string(Store.SAVE_PATH)==saved,"rule tests do not modify saved decks")
 print("V010_RULES: %d checks; %d failures" % [checks,failures.size()]); quit(0 if failures.is_empty() else 1)
